### ISSUE TITLE
最小化挂起后，歌曲播放结束会立刻关闭

### ISSUE THREAD

**Issue by efsg** [HyPlayer/HyPlayer#10]

**Comment by kengwang** [comment]
本地测试中暂时没有出现此问题,您可以查看应用设置中 `后台应用` 是否开启. 这通常是默认开启的.

**Comment by efsg** [comment]
> 本地测试中暂时没有出现此问题,您可以查看应用设置中 `后台应用` 是否开启. 这通常是默认开启的.

我看了下应用设置里后台应用默认就开启了，我系统版本是1909

**Comment by efsg** [comment]
> 本地测试中暂时没有出现此问题,您可以查看应用设置中 `后台应用` 是否开启. 这通常是默认开启的.

![image](https://user-images.githubusercontent.com/39408740/110633982-66abe500-81e4-11eb-8e6b-65a73b960ef2.png)
我今天试了下直接在前台播放完就直接未响应了

**Comment by kengwang** [comment]
试试新版是否要好一点, 新版我大重构了一遍, 不再用UWP原生的播放列表算法了,而是HyPlayer自己控制播放. 应该会好得多
一会儿就会把新版给 @aaaaaaccd 让他在微软商店更新

**Comment by efsg** [comment]
> 试试新版是否要好一点, 新版我大重构了一遍, 不再用UWP原生的播放列表算法了,而是HyPlayer自己控制播放. 应该会好得多
> 一会儿就会把新版给 @aaaaaaccd 让他在微软商店更新

今天试了下最新的包还是一样的问题，在商店安装也一样

**Comment by kengwang** [comment]
> 
> 
> > 试试新版是否要好一点, 新版我大重构了一遍, 不再用UWP原生的播放列表算法了,而是HyPlayer自己控制播放. 应该会好得多
> > 一会儿就会把新版给 @aaaaaaccd 让他在微软商店更新
> 
> 今天试了下最新的包还是一样的问题，在商店安装也一样

上周没有商店更新,因为 @aaaaaaccd 说要大改之后再发

**Comment by kengwang** [comment]
已经发布了，可以试试新版本。 此Issue暂时关闭

**Comment by youlan2333** [comment]
问题复现，具体表现为最小化窗口歌曲播放结束后会偶发暂停
Version 2.1.38.6000(PackagelD:48848aaaaaaccd.HyPlayer)
