### ISSUE TITLE
Proposal: Migrate to WinUI3 and/or Uno Platform

### ISSUE THREAD

**Issue by EP012014** [HyPlayer/HyPlayer#100]
Microsoft recently announced that UWP will be in maintenance mode and will only receive security fixes.

Currently, migrating to WinUI3 or Uno Platform is considerable and meets the expectation of the future developing trend.

WinUI3 uses a similar development way and is the superset of Universal Windows Platform. With it, we can still base on WinRT apis while using some of the Win32 features such as transparent overlap window for desktop lyrics.

Uno Platform is a third-party port of the WinRT apis and UWP to other platforms, like WASM. We can expand HyPlayer's audience by doing that and get good support.

**Comment by kengwang** [comment]
经过决议, 先迁移至 WinUI 3, 再根据情况决定是否迁移 Uno Platform
