### ISSUE TITLE
播放失败

### ISSUE THREAD

**Issue by soda-sugar** [HyPlayer/HyPlayer#101]
> 感谢您对 HyPlayer 提出建议和反馈,有了您的支持 HyPlayer 将会更好
>
> 在提交Issue时,为了保证您的Issue方便排查,减少沟通成本
>
> 请完善下方的内容, 这段引用起来的文字可以将其删除

## BUG 反馈

**何处触发：**

无法播放
**实际行为描述：**

海外ip 所有曲目均无法播放

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**

怎样才能再次触发这个问题？若无法复现可直接写 无法复现

**配置与环境：**

- 音乐链接：（如果有，请提供一个触发此问题的 音乐）
- HyPlayer 版本：2.1.6
- 系统版本：（正在使用的操作系统, cmd中输入`winver` 即可查看详细信息）

**截图（若有）**

<img width="223" alt="未命名图片" src="https://user-images.githubusercontent.com/93513955/139641066-536ffbc4-4bfe-4cbe-ae4b-4dac17554e91.png">

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

提供尽可能多的相关信息。

**修复思路：**

**Comment by kengwang** [comment]
针对这种情况有几种办法:
* 在实验室设置 `X-Forwarded-IP`
* 开小飞机,关掉网络环回(方法见 README),设置代理.
