### ISSUE TITLE
Hyplayer后台播放音乐一段时间后界面卡住无法操作

### ISSUE THREAD

**Issue by MkfsSion** [HyPlayer/HyPlayer#103]
## BUG 反馈

**何处触发：打开HyPlayer播放音乐，界面最小化后播放一段时间音乐后切回界面

这个问题出在程序的哪一个具体功能？

**实际行为描述：HyPlayer界面卡住无法操作，音乐仍在播放

触发问题后造成了什么效果及影响？

**预期的行为：HyPlayer无法操作，必须关闭重开

这个功能应该有怎样的效果和影响？

**复现步骤：正常操作界面

怎样才能再次触发这个问题？若无法复现可直接写 无法复现

打开Hyplayer播放音乐，界面最小化后播放一段时间音乐后切回界面

**配置与环境：Windows 11 Enterprise 21H2 Build 22000.282

- 音乐链接：无
- HyPlayer 版本：V2.1.5
- 系统版本：Windows 11 Enterprise 21H2 Build 22000.282

**截图（若有）**

**报错信息**

**补充信息：**

**修复思路：**

**Comment by EP012014** [comment]
这个是内存管理有关的问题，我们会在之后的版本中不采用过于激进的内存管理策略

**Comment by kengwang** [comment]
我也遇到了, 问题需要被排查

**Comment by kengwang** [comment]
完了,我这边必发作了.

**Comment by OptimusPrimeme** [comment]
这个问题怎么解决？到现在一直都不能用，已经开启了高级设置里的“频繁内存回收”
