### ISSUE TITLE
海外手机号无法使用手机号登陆

### ISSUE THREAD

**Issue by NAKASASA** [HyPlayer/HyPlayer#105]
## BUG 反馈

**何处触发：**

登录时触发

**实际行为描述：**

非大陆手机号无法登录
不论是直接输入还是+(国家区号)都不行

**截图（若有）**

![Screenshot 2021-11-19 112040](https://user-images.githubusercontent.com/43770381/142559450-8e37e460-de5c-4660-b6ec-6bc333e45e19.png)

**Comment by kengwang** [comment]
因为默认+86了,之后改为识别到+就用+后的

**Comment by kengwang** [comment]
新版 Commit 已经修复, 将在不久后发布正式版
![image](https://user-images.githubusercontent.com/30862240/146648892-e2c305ca-c34d-4bea-b72e-f70244a82a5d.png)
届时,使用这种格式即可登录
