### ISSUE TITLE
播放页内方形专辑图片的阴影显示位置错误

### ISSUE THREAD

**Issue by ClementLevi** [HyPlayer/HyPlayer#106]
## BUG 反馈

**何处触发：**

播放页面的专辑图片

**实际行为描述：**

当设置内勾选专辑旋转，但不勾选圆形专辑图片时，阴影将为方形，且在背景板上来回移动；此时几个容器的分界线很是清晰

**预期的行为：**

阴影应当在原地进行角度旋转

**复现步骤：**

设置内勾选专辑旋转，但不勾选圆形专辑图片

**配置与环境：**

- HyPlayer 版本：2.1.6.0 Windows Store的版本UWP
- 系统版本：Win10 21H1 19043.1348

**截图（若有）**

![image](https://user-images.githubusercontent.com/35921237/142634638-4e0700f3-3167-43ad-93a0-ff39c7345e87.png)

**修复思路：**

阴影应当在原地进行角度旋转

**Comment by kengwang** [comment]
??????
我觉得没人会点击唱片旋转后又不点圆形的吧😂
所以做的时候都是同时开的
因为我想有人想要圆形不旋转所以才独立开的

**Comment by ClementLevi** [comment]
然后就很不幸地被我找出这个bug了

**Comment by kengwang** [comment]
将会强制将唱片旋转后同时选中圆形
