### ISSUE TITLE
小窗模式下错误地渲染了另一张旋转的专辑图

### ISSUE THREAD

**Issue by ClementLevi** [HyPlayer/HyPlayer#107]
## BUG 反馈

**何处触发：**

从播放页切换到小窗模式时即可发生。

经测试，不论是否开启专辑图片旋转或圆形图片，该现象都可复现.

**实际行为描述：**

产生了如截图一般的异常图片；

若在其上单击左键，将会召唤出或销毁滚动歌词。

且暂停播放键可能会无法正常点击。

**复现步骤：**

从正常的播放页进入小窗模式时，从窗口下方将光标划入至左侧（正常窗口模式下专辑旋转图片应当处于的位置），调出播放进度条时偶发。这一异常的旋转图片也偶尔地会持续一整首歌，但一旦正常地销毁数次后或许不再出现。

**配置与环境：**

- HyPlayer 版本：2.1.6.0 Windows Store的版本UWP
- 系统版本：Win10 21H1 19043.1348

**截图（若有）**

![image](https://user-images.githubusercontent.com/35921237/142635450-b44c3e27-afbf-4199-a9cc-96465f8bc5a9.png)

同时值得注意的是，小窗模式下的播放器浮在了snipaste的捕获页面之上，仍然以动态状态存在

**P.S.**
如果小窗模式下的播放条不要那么大就好了，挺挡视线的

**Comment by ClementLevi** [comment]
我擦 二次元

**Comment by kengwang** [comment]
小窗模式再重构之后会重新设计
现在这个我用着都烦

**Comment by kengwang** [comment]
小窗将会变成纯小窗. 小窗将会单独出一个页面来显示, 就不会出现这种奇奇怪怪的问题了

**Comment by kengwang** [comment]
小窗已经改好
