### ISSUE TITLE
HTTPS 强制性验证导致无法使用解锁

### ISSUE THREAD

**Issue by ttyy114** [HyPlayer/HyPlayer#108]
## BUG 反馈

**何处触发：路由器开启音乐解锁 软件就连不上网络

这个问题出在程序的哪一个具体功能？ 连接网络

**实际行为描述：**

触发问题后造成了什么效果及影响 ：软件连不上网络

**复现步骤：路由器开启音乐解锁 

**配置与环境：**

- HyPlayer 版本：2.1.6
- 系统版本：Win10 21H1

**Comment by kengwang** [comment]
因为 HyPlayer 强制验证了 HTTPS 证书导致可能无法使用解锁相关. 在二次重构之后将会允许 Fallback 到 HTTP
