### ISSUE TITLE
软件似乎和代理软件冲突

### ISSUE THREAD

**Issue by LostMyMind** [HyPlayer/HyPlayer#11]
软件是最新的1.0.12.0版本，电脑是win10专业版20H2，代理软件是clash，开启代理软件的情况下播放器会加载不出首页，几秒后自动关闭，关闭代理软件后一切正常，代理节点是香港节点。
能否如同桌面版网易云一样加一个代理设置？默认是不使用代理。
另外请问下后续有没有考虑加个去掉毛玻璃效果的开关？歌词页直接用封面当背景，或者只对歌词部分制造毛玻璃效果。

**Comment by Funny-T** [comment]
你需要解除uwp回环，这是Windows8.1开始引入的特性

**Comment by aaaaaaccd** [comment]
UWP应用特性导致无法本地回环，可以用Powershell关掉限制
关于GUI的一切需要等到GUI完全完成后再加入设置选项，不然会很麻烦
