### ISSUE TITLE
搜索电台后闪退

### ISSUE THREAD

**Issue by Ben-YuqiLu** [HyPlayer/HyPlayer#110]
## BUG 反馈

**何处触发：**

搜索功能

**实际行为描述：**

无报错提示后程序闪退

**预期的行为：**

列表中应显示电台的搜索结果

**复现步骤：**

搜索栏搜索任意关键词后选择电台，程序闪退

**配置与环境：**

- 音乐链接：所有音乐均可以触发该bug
- HyPlayer 版本：2.1.6.0
- 系统版本：21H2 (22000.318)

**截图（若有）**

无

**报错信息**

无报错窗口弹出

**补充信息：**

无

**修复思路：**

**Comment by kengwang** [comment]
稍等,正在测试
如果可以的话提供下复现步骤的搜索内容

**Comment by kengwang** [comment]
好像是网易云音乐那边改了返回内容.

**Comment by kengwang** [comment]
经测试不是网易云音乐改变了返回值,而是封面图片处理不当导致的
