### ISSUE TITLE
希望支持 Dolby Atoms 类型识别

### ISSUE THREAD

**Issue by Druadach** [HyPlayer/HyPlayer#111]
希望增加 Dolby Atoms 杜比全景声动态调整支持，目前 HyPlayer 被自动识别为了游戏类型，而非音乐类型。

[![olBV2R.jpg](https://z3.ax1x.com/2021/11/30/olBV2R.jpg)](https://imgtu.com/i/olBV2R)

**Comment by kengwang** [comment]
这个的话似乎没有相关的 API 来实现，我们在申请 SMTC 时声明了是一个音乐播放的
