### ISSUE TITLE
喜欢图标辨识度不高

### ISSUE THREAD

**Issue by blanketbathe** [HyPlayer/HyPlayer#113]
容易误认为已喜欢

**Comment by kengwang** [comment]
收到,之后版本将会改成图标颜色为红色

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/146646663-2d1c9d88-e341-4c64-99a4-2ae7a8e3f115.png)
这样咋样?

**Comment by blanketbathe** [comment]
非常好

**Comment by blanketbathe** [comment]
哈哈，今天的黑白喜欢属实把我整糊涂了
