### ISSUE TITLE
播放界面几率卡死

### ISSUE THREAD

**Issue by wenweneqi** [HyPlayer/HyPlayer#114]
## BUG 反馈

**何处触发：播放界面

这个问题出在程序的哪一个具体功能？

**实际行为描述：终止播放无限循环，提示播放失败

触发问题后造成了什么效果及影响？

**预期的行为：下一首

这个功能应该有怎样的效果和影响？

**复现步骤：直接播放有几率出现

怎样才能再次触发这个问题？若无法复现可直接写 无法复现

**配置与环境：win10 21H2

- 音乐链接：（如果有，请提供一个触发此问题的 音乐）
- HyPlayer 版本：（2.1.6.0）
- 系统版本：（win10 21H2

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**报错信息**

```
Msg：
```

**补充信息：**

提供尽可能多的相关信息。

**修复思路：获取歌单信息的时候减慢点获取速度，网差的时候几率更大

**Comment by kengwang** [comment]
此问题出现在遇到了 无法播放的歌曲 上. 判断将会在之后重写

**Comment by wenweneqi** [comment]
> 此问题出现在遇到了 无法播放的歌曲 上. 判断将会在之后重写

![QQ截图20211218212529](https://user-images.githubusercontent.com/61258915/146642788-99b67bca-db98-4d8b-8f1d-bf8ac22c9da5.png)

**Comment by kengwang** [comment]
此问题为已知问题, 将会在重构版本中修复

**Comment by kengwang** [comment]
此项目也将在12月底之前将所有可修复的公开问题解决并发布最后一个重构前版本.
之后将全力进行重构操作

**Comment by wenweneqi** [comment]
> 此项目也将在12月底之前将所有可修复的公开问题解决并发布最后一个重构前版本. 之后将全力进行重构操作

ok，大佬这是24小时高强度网上冲浪吗，🤣

**Comment by kengwang** [comment]
正在尝试修复

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/146648473-ea575e32-7d1c-4f23-b11b-9059d32469fa.png)
不知道为什么,我这边放的起

**Comment by kengwang** [comment]
此问题已经修复

**Comment by kengwang** [comment]
将会在今晚发布并在近期推送到商店.
2.1.8 将作为最后一个旧版本. 之后将会将全部精力移到重构上
