### ISSUE TITLE
键盘操作音乐播放

### ISSUE THREAD

**Issue by wenweneqi** [HyPlayer/HyPlayer#115]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个程序更好。**
> 当你确定你的想法满足以上条件之后，请删除本段文本并继续。

**这是什么方面的想法？**

**_新增功能_** 

**这个想法具体是要实现什么？**

_**快捷键切换音乐**_

**这个想法实现后有什么帮助？**

_不用鼠标点来点去的了_

**是否有具体的实现思路？**

**补充信息：**

**Comment by kengwang** [comment]
Duplicated #112 
请关注这个 Issue.
此 Issue 关闭
