### ISSUE TITLE
关于喜欢图标的建议

### ISSUE THREAD

**Issue by blanketbathe** [HyPlayer/HyPlayer#116]
我认为现在的喜欢与不喜欢之间存在误解的可能依旧，建议不喜欢为空心心形，喜欢状态无需变化

**Comment by kengwang** [comment]
嗯,确实是. 我再考虑考虑,弄个 2.1.8. 把一些遗留问题给修了

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/147850050-a3257e7f-bfa2-4863-a087-212d33e7e438.png)
Done
