### ISSUE TITLE
下载歌单遇到无版权音乐会直接停止

### ISSUE THREAD

**Issue by Sakura1338** [HyPlayer/HyPlayer#119]
## BUG 反馈

**何处触发：

下载存在无版权音乐的歌单

**实际行为描述：**

如列表中存在无版权音乐，就会导致下载列表暂停，需要手动暂停无版权音乐下载才能继续下载

**预期的行为：**

会自动跳过无版权音乐的下载，并标注

**配置与环境：**

- 音乐链接：https://music.163.com/#/song?id=27485090 song?id=26608719
- HyPlayer 版本：2.1.8
- 系统版本：21H2

**截图（若有）**

![image](https://user-images.githubusercontent.com/61232882/148642408-85aac52f-0a1b-41db-9ec6-e035dd93683b.png)
![image](https://user-images.githubusercontent.com/61232882/148642477-5e1728fa-c225-4555-9818-b0f793653548.png)

**修复思路：**
自动跳过无版权音乐的下载

**Comment by kengwang** [comment]
收到,下个版本修

**Comment by kengwang** [comment]
Fixed in #121
