### ISSUE TITLE
关于HyPlayer已上架遇到的问题

### ISSUE THREAD

**Issue by Gaoyifei1011** [HyPlayer/HyPlayer#12]
侧边栏的透明度没有主界面的透明，希望优化一下
![image](https://user-images.githubusercontent.com/49179966/111056865-99442f00-84bd-11eb-9272-60f586da7a40.png)
点击登录后若想要取消登录操作没有找到关闭按钮，需要重新打开应用
![image](https://user-images.githubusercontent.com/49179966/111056884-e1fbe800-84bd-11eb-82ac-ccccd3661983.png)
应用磁贴上面没有显示出名称
![image](https://user-images.githubusercontent.com/49179966/111056895-fdff8980-84bd-11eb-885f-fff1b6fe5158.png)

**Comment by kengwang** [comment]
感谢指出,这个我assign给@aaaaaaccd, UI的事情他负责
assign @aaaaaaccd

**Comment by aaaaaaccd** [comment]
谢谢反馈，最近正在重新设计UI

**Comment by kengwang** [comment]
关于那个磁贴之后会显示当前播放的歌曲信息
