### ISSUE TITLE
菜单详情，头部上下滚动会出现白条，无法固定到最顶部

### ISSUE THREAD

**Issue by Q-Tai-mu** [HyPlayer/HyPlayer#122]
## BUG 反馈

**何处触发：鼠标滚动，歌曲菜单，来回上线滚动

这个问题出在程序的哪一个具体功能？

**实际行为描述：基本上所有菜单详情都有这个效果

触发问题后造成了什么效果及影响？

**预期的行为：应该是在滚歌曲列表时，菜单描述固定头部不动

这个功能应该有怎样的效果和影响？

**复现步骤：** 打开应用 选择发现发现音乐下的主页，随便选一个歌单，鼠标来回上下滚动，就会触发空白条

怎样才能再次触发这个问题？若无法复现可直接写 无法复现

**配置与环境：**  windows 10 ，版本号：20H2 ,操作系统内部版本：19042.1466 

- 音乐链接：歌单为：”你有多久没有对一个人心动过了“
- HyPlayer 版本：（Release 2。1.8，Commit 版则写 Commit 编号）
- 系统版本：（正在使用的操作系统, cmd中输入`winver` 即可查看详细信息）

**截图（若有）**
![T% GJ($SUI}Z92ARWUV7R{O](https://user-images.githubusercontent.com/58099119/149914864-d96c47b6-2523-40d9-a461-a4ca72e06fbe.png)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**报错信息** 

```
请在此处填写报错框中的相关信息
```

**补充信息：**

提供尽可能多的相关信息。

**修复思路：**

**Comment by kengwang** [comment]
Hi~ 这个就是这么设计的, 在往下滑动时隐藏,向上滑动时显示

**Comment by kengwang** [comment]
方便一些千曲歌单好翻到头

**Comment by kengwang** [comment]
确实, 我也被这种整烦了. 我一会儿改改

**Comment by kengwang** [comment]
Fixed in 66febca61701836c573a15b9c13795f306f3acb7
