### ISSUE TITLE
令部分文本可选中/复制

### ISSUE THREAD

**Issue by QZLin** [HyPlayer/HyPlayer#123]
**这是什么方面的想法？**
现有内容的优化

**这个想法具体是要实现什么？**
令部分文本**可选中/复制**，如歌曲播放界面的歌曲名，歌手，专辑，歌词

**这个想法实现后有什么帮助？**
可以轻松的利用歌曲名等文本的全部或部分，直接复制用于分享或搜索，而无须重新输入。

**是否有具体的实现思路？**
UI控件类型/属性调整

**补充信息：**

**Comment by kengwang** [comment]
可以考虑考虑

**Comment by kengwang** [comment]
要不就在旧版中实现了吧

**Comment by kengwang** [comment]
! Need Further Discussion !:
具体是在那些地方呢?

**Comment by QZLin** [comment]
这是基于我个人使用经验的建议
* 播放页面：
曲名，歌手，专辑，以及歌词
* 专辑页面：
专辑，歌手，描述
* 歌手页面：
歌手名，描述
* (?不确定)电台页面:
名称，描述
* ?歌单页面
名称，描述
![image](https://user-images.githubusercontent.com/38138000/151654851-8927940f-bd13-4dcf-bdc7-c396c24f70cd.png)
专辑页面
![image](https://user-images.githubusercontent.com/38138000/151655325-5b6093e4-05b7-492a-bfe6-707c2ae3fb43.png)
歌手页面
![image](https://user-images.githubusercontent.com/38138000/151655469-9ab324ee-0588-4573-8ce8-45a813f81902.png)

**Comment by kengwang** [comment]
好的, 我尝试实现下

**Comment by kengwang** [comment]
歌词的话我单独开个 Issue, 因为我的想法是另一种方式实现歌词复制

**Comment by kengwang** [comment]
#127 讨论关于歌词复制的问题

**Comment by kengwang** [comment]
See a21c73064d5d370daf2a8db122cd82d8ffaa31f4
