### ISSUE TITLE
使用蓝牙耳机播放导致耳机卡退

### ISSUE THREAD

**Issue by BlackalSaka** [HyPlayer/HyPlayer#124]
## BUG 反馈

**何处触发：**

点击播放时

**实际行为描述：**

使用蓝牙耳机，一点击播放后蓝牙耳机就会自己卡退，之后就会使用系统扬声器播放

**配置与环境：**

- 耳机型号：漫步者W800BT
- HyPlayer 版本：2.1.9.0
- 系统版本：20H2 (19042.1466)

**补充信息：**

在chrome浏览器中播放视频时也有同样的问题，解决办法
> https://blog.csdn.net/nishigesb123/article/details/115529155
> 浏览器地址栏输入：
> chrome://flags/#hardware-media-key-handling
> 搜索 Hardware Media Key Handling 
> 改为 disable

**修复思路：**

也许和上面的有关？

**Comment by kengwang** [comment]
感谢, 我会在今晚晚些时候试试用蓝牙耳机.

**Comment by kengwang** [comment]
经过测试, 我这边的蓝牙耳机不会出现此问题. 
看了下 Chrome 解决方法, 是禁用掉了 耳机的按键媒体控制.
这个因为一些限制不能禁用掉.

如果需要进一步排查可以发一下在 HyPlayer 设置 - 关于 中的设备识别码, 我看看这边有没有报错

**Comment by BlackalSaka** [comment]
感谢，看来是我的这款耳机有bug了😥
刚才又试了一下，开机后首次打开播放是正常的，这是正常点击暂停、手动切换下一曲都是没有问题的；
但是一旦是歌曲播放完后自动切到下一曲，耳机就被卡退了，然后无论再怎么重启耳机都不行了。

设备识别码：6d3bb03b-63b7-419b-cfe3-85d10ddd71ee
