### ISSUE TITLE
[Feat] AB 区段循环

### ISSUE THREAD

**Issue by kengwang** [HyPlayer/HyPlayer#126]
**这是什么方面的想法？**

新增功能

**这个想法具体是要实现什么？**

AB 区段循环

**这个想法实现后有什么帮助？**

允许进行 AB 区段循环

**Comment by Raspberry-Monster** [comment]
Achieved in https://github.com/HyPlayer/HyPlayer/commit/f363648b456f2f3ed1b48c77cee9087dc502b9c1
