### ISSUE TITLE
登录行为的建议

### ISSUE THREAD

**Issue by Weilet** [HyPlayer/HyPlayer#129]
**登录行为**

用户体验

**登录一个未绑定手机的账号应该给出合适的提示**

**让登录行为更明确**

**未绑定手机的账号返回的数据应该是有别于已绑定的，可以通过这个判断**

**目前登录未绑定手机的账号会变为网易云音乐的官方账号，用户遇到会感到迷惑，但是这个问题的优先级其实不高，可以放在后面解决**

**Comment by kengwang** [comment]
收到，我看看相关代码


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月30日 22:59:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HyPlayer/HyPlayer] 登录行为的建议 (Issue #129)




 
登录行为
 
用户体验
 
登录一个未绑定手机的账号应该给出合适的提示
 
让登录行为更明确
 
未绑定手机的账号返回的数据应该是有别于已绑定的，可以通过这个判断
 
目前登录未绑定手机的账号会变为网易云音乐的官方账号，用户遇到会感到迷惑，但是这个问题的优先级其实不高，可以放在后面解决

**Comment by kengwang** [comment]
未绑定的账号是通过什么登录的? 邮箱?

**Comment by Weilet** [comment]
> 未绑定的账号是通过什么登录的? 邮箱?

通过邮箱登录的

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/151706259-c339a4f6-a8cd-4dbf-ae80-1255e46108e9.png)
弄了弄, 现在会这样提示下

**Comment by kengwang** [comment]
语句改成 `此账号未进行手机号验证, 请使用网易云音乐客户端登录后再继续操作`
