### ISSUE TITLE
Xbox 掉后台问题跟踪

### ISSUE THREAD

**Issue by Xiepoder** [HyPlayer/HyPlayer#13]
xbox版本可以用吗？会掉后台吗？

**Comment by aaaaaaccd** [comment]
可以用，但是后台不知道

**Comment by aaaaaaccd** [comment]
如果有问题的话欢迎汇报，因为我目前没有实机调试

**Comment by kengwang** [comment]
后台按照微软的文档来说不会掉。我是严格按照自定义播放列表+后台播放走的。

**Comment by kengwang** [comment]
因为此问题一直复现,此Issue作为开山鼻祖,重新Open

**Comment by joebnb** [comment]
hello，我是从xbox store 来的，感谢创作了这么好的一个应用，store 里面已经有很多评论了，有空可以去看看，我来评论是为了了解下掉后台的事情，以及后续的更新，store里有个aaaaacccc的作者说十月会发布新版，可是十二月了新版一直没有发布，请问这个问题还会修复吗?

**Comment by EP012014** [comment]
> 

我们目前在对整个应用进行重构，瞄准一月上旬发布新版
至于掉后台是因为内存占用超限导致的，这个Xbox的限制也很迷，我们只能尽量调查

**Comment by kengwang** [comment]
目前播放模块已经重构完成，首先可能会将 Xbox 版本独立出来，尽量减少内存开支来挂住后台。
PS. PC 新版已经发布最后一个旧版本 （2.1.7），之后将会于1月份发布 3.0.0 重构版本。

**Comment by joebnb** [comment]
![image](https://user-images.githubusercontent.com/1646883/147213342-48a5cc90-b3be-4bdb-a419-30d700651055.png)

https://docs.microsoft.com/en-us/windows/uwp/launch-resume/reduce-memory-usage

看到你在开发者论坛的主题了，希望可以帮助到

**Comment by joebnb** [comment]
![image](https://user-images.githubusercontent.com/1646883/147215654-20feae2e-9682-4258-8908-0490895c9f04.png)

https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/legacy-background-media-playback

似乎他们这个架构会好一点点，就只把播放器和列表作为服务放到background里，然后前台完全是UI和一些额外的东西。

前台和后台交互去控制音频播放和播放列表，再提供一个当前正在播放的交互接口供前台唤起后同步信息，不知道HYplayer是不是就是按照这样去做的。

**Comment by kengwang** [comment]
> ![image](https://user-images.githubusercontent.com/1646883/147215654-20feae2e-9682-4258-8908-0490895c9f04.png)
> 
> https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/legacy-background-media-playback
> 
> 似乎他们这个架构会好一点点，就只把播放器和列表作为服务放到background里，然后前台完全是UI和一些额外的东西。
> 
> 前台和后台交互去控制音频播放和播放列表，再提供一个当前正在播放的交互接口供前台唤起后同步信息，不知道HYplayer是不是就是按照这样去做的。

此架构似乎已经过时, 目前采用的是新架构

**Comment by joebnb** [comment]
> 目前播放模块已经重构完成，首先可能会将 Xbox 版本独立出来，尽量减少内存开支来挂住后台。 PS. PC 新版已经发布最后一个旧版本 （2.1.7），之后将会于1月份发布 3.0.0 重构版本。

想问下 3.0.0 版本是否已经开发完毕，xbox 上的音乐软件求更新

**Comment by kengwang** [comment]
3.0.0 版本暂时搁置着的, 最近在赶作业. 等到开学后有时间再写

**Comment by kengwang** [comment]
旧版本的最后一个版本 (Beta) 应该挂得住了, 不过要按照下面的方式:
Xbox 后台播放 / 低内存占用
请注意, 由于微软限制, Xbox 上后台应用内存占用至多为 128 MB 否则将会被杀掉, 目前可以通过一些操作尽量减少内存占用来缓解

1. 安装完软件并登录后, 进入 设置 - 实验室 - 无图模式 并勾选
2. 重启软件
3. 在当前页面 (用户页面) 下找到要播放的歌单, 点击右侧的播放按键
4. 待播放后进入 设置 - 实验室, 点击 Xbox 进后台模式
5. 待页面清空后即可切后台

上述方法会显著降低内存占用, 以此来不达到内存限制.
重构版将会从根本上减少内存占用

正式版通道按理说也可以, 之后把 Beta 的推到正式

**Comment by joebnb** [comment]
> 旧版本的最后一个版本 (Beta) 应该挂得住了, 不过要按照下面的方式: Xbox 后台播放 / 低内存占用 请注意, 由于微软限制, Xbox 上后台应用内存占用至多为 128 MB 否则将会被杀掉, 目前可以通过一些操作尽量减少内存占用来缓解
> 
> 1. 安装完软件并登录后, 进入 设置 - 实验室 - 无图模式 并勾选
> 2. 重启软件
> 3. 在当前页面 (用户页面) 下找到要播放的歌单, 点击右侧的播放按键
> 4. 待播放后进入 设置 - 实验室, 点击 Xbox 进后台模式
> 5. 待页面清空后即可切后台
> 
> 上述方法会显著降低内存占用, 以此来不达到内存限制. 重构版将会从根本上减少内存占用
> 
> 正式版通道按理说也可以, 之后把 Beta 的推到正式

👍  ，可以在store上发布一下这个版本的hyplayer吗？

**Comment by kengwang** [comment]
Re:
https://github.com/HyPlayer/HyPlayer/issues/13#issuecomment-1035919549

已经发布
