### ISSUE TITLE
[BUG] 播放缓存功能修复

### ISSUE THREAD

**Issue by EMT-Knight** [HyPlayer/HyPlayer#132]
疑问？
HyPlayer的在线播放缓存在哪啊？也没有清理选项啊？建议提供清理选项或者可以自定义缓存目录！！

**Comment by kengwang** [comment]
如果没有在实验室开启缓存的话是不会有缓存的，如果实验室开启了缓存则在存储设置里有缓存目录


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月5日 14:13:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HyPlayer/HyPlayer] HyPlayer的在线播放缓存在哪啊？也没有清理选项啊？建议提供清理选项或者可以自定义缓存目录！！ (Issue #132)




 
疑问？
 HyPlayer的在线播放缓存在哪啊？也没有清理选项啊？建议提供清理选项或者可以自定义缓存目录！！

**Comment by EMT-Knight** [comment]
实验室开启缓存了，为什么缓存目录没有文件？是隐藏了吗？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HyPlayer/HyPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月5日(星期六) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HyPlayer/HyPlayer] HyPlayer的在线播放缓存在哪啊？也没有清理选项啊？建议提供清理选项或者可以自定义缓存目录！！ (Issue #132)





 如果没有在实验室开启缓存的话是不会有缓存的，如果实验室开启了缓存则在存储设置里有缓存目录 
 
 
   
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年2月5日 14:13:16 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [HyPlayer/HyPlayer] HyPlayer的在线播放缓存在哪啊？也没有清理选项啊？建议提供清理选项或者可以自定义缓存目录！！ (Issue #132) 
 
 
 
 
   
 疑问？ 
  HyPlayer的在线播放缓存在哪啊？也没有清理选项啊？建议提供清理选项或者可以自定义缓存目录！！ 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kengwang** [comment]
我调试一下看下情况, 是不是不小心把缓存那个地方的逻辑删了

**Comment by kengwang** [comment]
嘶, 缓存模块炸了. 开了之后都不会走缓存, 我改改

**Comment by kengwang** [comment]
OK 了
