### ISSUE TITLE
希望降低一下歌词背景的亮度

### ISSUE THREAD

**Issue by chwt163** [HyPlayer/HyPlayer#134]
歌词界面的背景是自动匹配专辑封面的，如果封面的整体色彩比较明亮，歌词背景就显得太明亮，导致很难看清歌词和操作按钮。
另外，能不能自定义歌词字体？

Tasks:

- [ ] 背景深度调整
- [ ] 自定义歌词字体

**Comment by kengwang** [comment]
* 这个其实是一个很难做出调整的东西, 目前歌词已经是响应颜色式的了. 不过专辑封面很多, 亚克力本身就是降低了背景的, 如果可以的话要不这个参数之后课自定义化?
* 自定义歌词字体的话可以考虑考虑 但不作为必须项

**Comment by chwt163** [comment]
感谢回复~
加个设置自定义当然是最好了。
可以参考一下 yesplaymusic 和 lyricease ，这两个的背景也是响应封面的，颜色比较深，看起来就比较舒服。

**Comment by kengwang** [comment]
具体进度见 #135 
Task 2: 歌词页面背景配色更改
