### ISSUE TITLE
亚克力配色更改

### ISSUE THREAD

**Issue by chwt163** [HyPlayer/HyPlayer#135]
如图：
![屏幕截图 2022-02-13 160556](https://user-images.githubusercontent.com/70951194/153744789-80adc614-e295-43df-9f93-6fd4ae578386.png)

Tasks:

- [ ] PlayBar 的配色更改
- [ ] 歌词页面背景的配色更改
- [ ] 

附加:
- [x] #136

**Comment by ApigeonAPE** [comment]
播放区域最下面的一条确实难受

**Comment by ApigeonAPE** [comment]
或者把playbar的颜色和软件本体的灰度调出些差别，比如一个深一个浅，或者加个阴影会舒服很多。

**Comment by kengwang** [comment]
> 或者把playbar的颜色和软件本体的灰度调出些差别，比如一个深一个浅，加个阴影，会舒服很多。

下个版本将会采用

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/164886245-aa3c1663-7239-4c7f-9a29-2e20b2338e4f.png)
 新 UI 下的显示效果
