### ISSUE TITLE
VIP 歌曲的显示及相关逻辑

### ISSUE THREAD

**Issue by kengwang** [HyPlayer/HyPlayer#139]
### Discussed in https://github.com/HyPlayer/HyPlayer/discussions/138

<div type='discussions-op-text'>

<sup>Originally posted by **ApigeonAPE** February 17, 2022</sup>
*系统：Windows 10 家庭版 21H2 内部版本19044.1526*

~~系统正常自动锁屏后~~ 现在发现正常播放时也会，**时不时出现一首歌放了个开头就自动切换下一首的问题。**
*软件版本：2.1.14.0*
*设备识别码：aab93f34-ec42-ebde-a035-7ed869c1d819*

实验室中开启了亚克力背景，播放缓存，高级音乐历史，听歌打卡</div>

>VIP歌曲试听，所以没法放完。居然不能显示哪些歌是VIP，有点遗憾，下载时VIP歌曲不能下载也不会提醒。希望重构版能加入VIP显示，也免得踩坑了。

**Comment by ApigeonAPE** [comment]
实现了？已经会显示VIP：
![image](https://user-images.githubusercontent.com/61077394/158362571-2aa97eff-4947-4a94-8fd4-0f7a7310d0e8.png)
但是版本号依然是2.1.14.0：
![image](https://user-images.githubusercontent.com/61077394/158362689-ae6ed595-ec45-4257-b522-8c62f050b294.png)

**Comment by kengwang** [comment]
一直都有这个功能的, 但是在当前播放项的时候不会显示.
