### ISSUE TITLE
关于评论展开的bug

### ISSUE THREAD

**Issue by ApigeonAPE** [HyPlayer/HyPlayer#140]
> 感谢您对 HyPlayer 提出建议和反馈,有了您的支持 HyPlayer 将会更好
>
> 在提交Issue时,为了保证您的Issue方便排查,减少沟通成本
>
> 请完善下方的内容, 这段引用起来的文字可以将其删除

## BUG 反馈

**何处触发：**

评论中展开评论的评论
![image](https://user-images.githubusercontent.com/61077394/155330725-dbc2f0b5-5ef6-4fe8-b69d-297507352a9d.png)

**实际行为描述：**

只要展开-收起评论的评论，再一次展开，就会复制一条一样的评论，可以一直复制。
![image](https://user-images.githubusercontent.com/61077394/155331067-cff74c66-6e95-4f3a-88be-1add51632b37.png)
如图，我可以一直通过重复**展开-收起**来复制评论

**复现步骤：**

同上

**配置与环境：**

- 音乐链接：任何音乐
- HyPlayer 版本：2.1.14.0（版本号不能复制，很麻烦，建议改进）
- 系统版本：win10 home 21h2

**截图（若有）**

同上

**报错信息**

无

**补充信息：**

github昨天晚上又抽风连不上，还好手快保存了。

**修复思路：**
收起评论后清除缓存，避免再次重复

**Comment by Raspberry-Monster** [comment]
Fixed in https://github.com/HyPlayer/HyPlayer/commit/6f9021cba5f475a5a0b0f41776a31868846f1529
