### ISSUE TITLE
PlayBar UI 修改

### ISSUE THREAD

**Issue by kengwang** [HyPlayer/HyPlayer#141]
**这是什么方面的想法？**

新增功能 / UI 界面

**这个想法具体是要实现什么？**

PlayBar 允许与页面底部贴合
并且非贴合情况下加上阴影与背景改色

**Comment by ApigeonAPE** [comment]
微软商店没更新？是要和下一版同时发布吗？

**Comment by kengwang** [comment]
微软商店会月更，在当月 15 日的最近周末发布更新From KengwangOn Outlook Android
