### ISSUE TITLE
网络有关功能异常

### ISSUE THREAD

**Issue by CJYKK** [HyPlayer/HyPlayer#142]
## BUG 反馈

**何处触发：**

点击寻觅音乐，发现音乐，播放历史，我的收藏和我的云盘时。

**实际行为描述：**

软件无法正常使用，显示出现问题，几乎所有关于“互联网歌曲”的模块都会报错。离线音乐播放，功能设置等正常。

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**

每次在主页点击都这样……真的没什么复现步骤……

**配置与环境：**

- HyPlayer 版本：Release 2.1.15.0
- 系统版本：Microsoft Windows 10 21H1（19043.1526） 专业工作站版

**截图（若有）**

![image](https://user-images.githubusercontent.com/59359590/156365995-b15bbb14-3356-4192-a519-0b281a63bd54.png)

![image](https://user-images.githubusercontent.com/59359590/156365687-502d1edf-fe15-4016-b2cb-c434390a3891.png)

**报错信息**

```
Object reference not set to an instance of an object.
Exception of type 'System.Exception' was thrown.

和

Value cannot be null.
Parameter name: source
Exception of type 'System.Exception' was thrown.
```

**补充信息：**

https://user-images.githubusercontent.com/59359590/156367185-e660400c-64b8-4041-9268-d05ff1e4f4ac.mp4

**Comment by Raspberry-Monster** [comment]
我留意到您打开了Telegram 所以您似乎正在使用网络代理？
由于UWP的网络环回限制，必须解除网络环回限制才能正确连接至网络
请参考[https://github.com/HyPlayer/HyPlayer#%E5%85%B3%E4%BA%8E%E6%97%A0%E7%89%88%E6%9D%83](url)中的解除网络环回限制以解决问题
如果此问题仍然出现，请再次与我们联系 HyPlayer开发团队很乐意协助您解决此问题

**Comment by CJYKK** [comment]
问题已解决，感谢您的热心帮助！
