### ISSUE TITLE
专辑展开导致软件卡死

### ISSUE THREAD

**Issue by Keanu-42** [HyPlayer/HyPlayer#143]
- 问题：
点击左下角专辑封面，或右下角箭头进行展开，整个软件就会严重卡死。
- 版本：
微软商店 最新版
- 系统：
win10 21H2（64位）
- 措施：
已尝试过清除UWP缓存（

**Comment by Raspberry-Monster** [comment]
麻烦更新一下软件版本至 2.1.15（最新版本） 并且再次尝试复现此Bug；
如果仍然出现此问题，HyPlayer团队非常愿意协助您解决问题

**Comment by Raspberry-Monster** [comment]
麻烦更新一下软件版本至 2.1.15（最新版本） 并且再次尝试复现此Bug；
如果仍然出现此问题，HyPlayer团队非常愿意协助您解决问题

**Comment by Raspberry-Monster** [comment]
非常抱歉对您造成不便，由于证书原因，GitHub版本的Release必须使用右键使用PowerShell执行压缩包中的Install.ps1文件才能正确安装
同时，我们建议您在切换商店版本到GitHub版本的时候，先卸载商店版本
对此造成的不便 HyPlayer开发组对您表达诚挚的歉意

**Comment by Keanu-42** [comment]
2.1.15版本已安装成功，但是问题依旧，不过我更加确定卡顿是针对某一首歌曲（[AIAIAI](https://music.163.com/#/song?id=1353381404)——Kizuna AI / 中田ヤスタカ），这挺奇怪的。
> 题外话，居然不能用最新版pwsh安装（

**Comment by Raspberry-Monster** [comment]
（Kizuner震怒） 非常抱歉对您造成不便，由于我现在还在学校，无法对程序进行调试
我在回家之后会尝试对其进行定位
对此造成的不便 HyPlayer开发组对您表达诚挚的歉意

**Comment by kengwang** [comment]
这是由于新版 Powershell （7.x）想要做到全平台通用，所以移除了 Windows 的独有的部分功能。所以只能在旧版中使用 Add-AppxPackageFrom KengwangOn Outlook Android发件人: Keanu-42 ***@***.***>发送时间: 2022年3月4日星期五 下午12:47收件人: HyPlayer抄送: subscribed主题: Re: [HyPlayer/HyPlayer] 专辑展开导致软件卡死 (Issue #143)

2.1.15版本已安装成功，但是问题依旧，不过我更加确定卡顿是针对某一首歌曲（AIAIAI——Kizuna AI / 中田ヤスタカ），这挺奇怪的。



题外话，居然不能用最新版pwsh安装（

**Comment by Raspberry-Monster** [comment]
Fixed in https://github.com/HyPlayer/HyPlayer/commit/c54e6e25194afcf8e99c4d4a6ece9a350db3aa47
