### ISSUE TITLE
无法播放云盘中“无损”音质的音乐

### ISSUE THREAD

**Issue by liuyi-thu** [HyPlayer/HyPlayer#144]
## BUG 反馈

**何处触发：**

在云盘中播放“无损”音质的音乐时

**实际行为描述：**

会自动跳过该音乐，无法播放

**预期的行为：**

应该可以播放

**复现步骤：**

在网易云客户端中上传APE、FLAC（MP3格式之外）的音频，再用HyPlayer就无法播放

**配置与环境：**

- 音乐链接：
- HyPlayer 版本：2.14.0
- 系统版本：Windows 10 20H2（19042）

**截图（若有）**

**报错信息**

无报错信息

**补充信息：**

其实影响不大，我可以上传MP3格式的文件，这样就能播放了。

**修复思路：**

似乎是UWP的某些API的问题？我用LyricEase也出现了这个问题，它用的好像是UWP的一个API进行播放，然后我搜了一下文档发现这个API似乎不支持APE、FLAC这类无损格式，主要支持的还是MP3格式。不过Windows自带的WMP应该也不支持这些无损格式。
我没有接触过UWP开发，不清楚UWP的应用能不能调用外部的解码器，如果能调用的话或许就能解决这个问题了。

**Comment by kengwang** [comment]
emm, 不过我云盘歌曲也是传的 FLAC 但是可以播放

**Comment by liuyi-thu** [comment]
> emm, 不过我云盘歌曲也是传的 FLAC 但是可以播放

感谢您的回复。我刚才试了一下，新传的 FLAC 可以播放，显示的是“818K”而非“无损”。我猜测可能是现在网易云的客户端改版了，服务器保存的不是原始的 FLAC 文件。
