### ISSUE TITLE
关于使用 UnblockNeteaseMusic 的方法

### ISSUE THREAD

**Issue by kengwang** [HyPlayer/HyPlayer#148]
HyPlayer 不内置 UnblockNeteaseMusic ，但是你可以通过手动运行并让 HyPlayer 的代理达到目的。

1. 请前往 https://github.com/nondanee/UnblockNeteaseMusic 下载程序并运行, 你会看到
![看到此提示表示成功运行](https://user-images.githubusercontent.com/30862240/158030619-832604da-72f5-449a-b749-03c7e4246053.png)
2. (以 Windows 11 为例) 进入 `系统设置` - `网络和 Internet` - `代理`
3. 编辑 `使用设置脚本`, 将其启用并在地址填入 `http://127.0.0.1:8080/proxy.pac` (请将 `8080` 换成你所指定的端口)
4. 打开 Powershell / CMD, 运行以下代码来解除网络环回 (Loopback)
```powershell
CheckNetIsolation LoopbackExempt -a -n="48848aaaaaaccd.hyplayer_fkcggvf9kbkw0"
```
5. 打开 HyPlayer, 在 `设置` - `实验室` 中填入任意字符
6. 重启 HyPlayer
7. 在 UnblockNeteaseMusic 的控制台将会输出请求同时您的歌曲也将解除灰色

**Comment by Raspberry-Monster** [comment]
此issue移动至wiki

**Comment by fordes123** [comment]
补充一下，如果使用Clash系统代理，为避免代理冲突，步骤2、3可以替换为：
- 打开Clash设置->系统代理->PAC内容，将内容修改为 ：
```
function FindProxyForURL(url, host) {
  if (host == 'music.163.com' || host == 'interface.music.163.com' || host == 'interface3.music.163.com' || host == 'apm.music.163.com' || host == 'apm3.music.163.com' || host == 'musicupload.netease.com') {
		return 'PROXY 127.0.0.1:8080'
	}
  return "PROXY 127.0.0.1:%mixed-port%; SOCKS5 127.0.0.1:%mixed-port%; DIRECT;"
}
```
其中`127.0.0.1:8080`为UnblockNeteaseMusic服务地址，修改后保存，Clash托盘右键勾选系统代理即可

**Comment by kengwang** [comment]
> 补充一下，如果使用Clash系统代理，为避免代理冲突，步骤2、3可以替换为：
> - 打开Clash设置->系统代理->PAC内容，将内容修改为 ：
> ```
> function FindProxyForURL(url, host) {
>   if (host == 'music.163.com' || host == 'interface.music.163.com' || host == 'interface3.music.163.com' || host == 'apm.music.163.com' || host == 'apm3.music.163.com' || host == 'musicupload.netease.com') {
> 		return 'PROXY 127.0.0.1:8080'
> 	}
>   return "PROXY 127.0.0.1:%mixed-port%; SOCKS5 127.0.0.1:%mixed-port%; DIRECT;"
> }
> ```
> 其中`127.0.0.1:8080`为UnblockNeteaseMusic服务地址，修改后保存，Clash托盘右键勾选系统代理即可

感谢，将在之后加入 Wiki

**Comment by FEI352** [comment]
> 补充一下，如果使用Clash系统代理，为避免代理冲突，步骤2、3可以替换为：
> 
> * 打开Clash设置->系统代理->PAC内容，将内容修改为 ：
> 
> ```
> function FindProxyForURL(url, host) {
>   if (host == 'music.163.com' || host == 'interface.music.163.com' || host == 'interface3.music.163.com' || host == 'apm.music.163.com' || host == 'apm3.music.163.com' || host == 'musicupload.netease.com') {
> 		return 'PROXY 127.0.0.1:8080'
> 	}
>   return "PROXY 127.0.0.1:%mixed-port%; SOCKS5 127.0.0.1:%mixed-port%; DIRECT;"
> }
> ```
> 
> 其中`127.0.0.1:8080`为UnblockNeteaseMusic服务地址，修改后保存，Clash托盘右键勾选系统代理即可

dalao,v2rayN需要怎么做才不冲突

**Comment by havfu** [comment]
使用proxifier可以代替clash，
1.设置代理服务器为127.0.0.1:8080,https协议，就是8080端口，8081不通
![image](https://github.com/HyPlayer/HyPlayer/assets/147126552/1353315b-b000-42e5-930e-9c5ddbd421e2)
2.设置代理规则为
![image](https://github.com/HyPlayer/HyPlayer/assets/147126552/db448ab8-c83b-49c2-95e4-292b970e3558)
目标地址music.163.com;interface.music.163.com;interface3.music.163.com;apm.music.163.com;apm3.music.163.com;musicupload.netease.com
行为选上面添加的服务器
3.如果出现提示说解锁程序无限循环就选择【按照建议的处理方法】

**Comment by kengwang** [comment]
之后我会重写一遍这篇文章

**Comment by kengwang** [comment]
文章以重写完成, 请前往 [此处](https://github.com/HyPlayer/HyPlayer/wiki/%E5%85%B3%E4%BA%8E%E4%BD%BF%E7%94%A8-UnblockNeteaseMusic-%E7%9A%84%E6%96%B9%E6%B3%95) 查看

**Comment by LINKlang** [comment]
解黑后歌曲图片之类的加载不出来了，然后黑的歌播放的时候还会报错，歌曲也放不出来
![image](https://github.com/HyPlayer/HyPlayer/assets/116951234/0ca7cb95-e713-4941-8a5d-21a99df6cd3e)
![image](https://github.com/HyPlayer/HyPlayer/assets/116951234/55330a43-133e-4974-bc22-15155b484632)
用的是系统代理的办法
求个解决办法

**Comment by kengwang** [comment]
> Reply https://github.com/HyPlayer/HyPlayer/issues/148#issuecomment-1937453050

请加入用户交流群获取反馈

**Comment by havfu** [comment]
> 使用proxifier可以代替clash， 1.设置代理服务器为127.0.0.1:8080,https协议，就是8080端口，8081不通 ![image](https://private-user-images.githubusercontent.com/147126552/302558178-1353315b-b000-42e5-930e-9c5ddbd421e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzY1MDQsIm5iZiI6MTcwNzYzNjIwNCwicGF0aCI6Ii8xNDcxMjY1NTIvMzAyNTU4MTc4LTEzNTMzMTViLWIwMDAtNDJlNS05MzBlLTljNWRkYmQ0MjFlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwNzIzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzM5ODUyNWFlMWZmMGFiYmNlYWEzODY3MzRkZjVmMjk4YTFlOGZiYmIwZDZmMmE0NWE0Yzc2MDlkMGRlZTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uw4Rn9imxqdtHcYP8vHObeFqXaF8FVRt2rTTsA4LjZg) 2.设置代理规则为 ![image](https://private-user-images.githubusercontent.com/147126552/302558549-db448ab8-c83b-49c2-95e4-292b970e3558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzY1MDQsIm5iZiI6MTcwNzYzNjIwNCwicGF0aCI6Ii8xNDcxMjY1NTIvMzAyNTU4NTQ5LWRiNDQ4YWI4LWM4M2ItNDljMi05NWU0LTI5MmI5NzBlMzU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwNzIzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzNmNGJlMzQzMTgwMmQ0MmYwN2ZlZTgwMGY0YzY2Y2NlMTcyMDEwYjU3NjRmOWFlOGFlNWM5ZjQyMDY1MWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ka6fPyj5JE-IGhqLWv_mHsS3jNvA7tIki9MbQvn9tSc) 目标地址music.163.com;interface.music.163.com;interface3.music.163.com;apm.music.163.com;apm3.music.163.com;musicupload.netease.com 行为选上面添加的服务器 3.如果出现提示说解锁程序无限循环就选择【按照建议的处理方法】

注意applications是any，不然开了代理解不了灰，因为不开代理是hyplayer在访问，开了代理是xray在访问

**Comment by kengwang** [comment]
> Reply: https://github.com/HyPlayer/HyPlayer/issues/148#issuecomment-1937458090

好的, 谢谢指教
