### ISSUE TITLE
Clash for Windows 系统代理开启时，HyPlayer文字正常加载，但封面与音乐无法加载

### ISSUE THREAD

**Issue by AnrayAnn** [HyPlayer/HyPlayer#149]
## BUG 反馈

**何处触发：**

Clash未对音乐播放器启用UWP应用网络回环，开启系统代理，音乐无法播放，封面无法获取。

**实际行为描述：**

音乐无法播放，封面无法获取。

**预期的行为：**

音乐正常播放，封面正常获取

**复现步骤：**

Clash开启系统代理。

**配置与环境：**

- 音乐链接：所有
- HyPlayer 版本：2.1.14.0
- 系统版本：Win11 21H2 22000.556

**报错信息**

```
无报错
```

**Comment by Raspberry-Monster** [comment]
我留意到您打开了Clash 所以您似乎正在使用网络代理？
由于UWP的网络环回限制，必须解除网络环回限制才能正确连接至网络
请参考Readme中的“关于无版权”中的解除网络环回限制以解决问题
如果此问题仍然出现，请再次与我们联系 HyPlayer开发团队很乐意协助您解决此问题

**Comment by AnrayAnn** [comment]
非常感谢，在解除网络环回限制后问题就解决了。
我以为不用走代理的uwp应用不需要解除呢，打扰你们了非常抱歉。

**Comment by observerkei** [comment]
是因为 UWP应用的代理设置导致的， Clash 的 General - UWP Loopback 可以进行设置，勾上 HyPlayer 就行
