### ISSUE TITLE
发现评论新问题

### ISSUE THREAD

**Issue by ApigeonAPE** [HyPlayer/HyPlayer#150]
> 感谢您对 HyPlayer 提出建议和反馈,有了您的支持 HyPlayer 将会更好
>
> 在提交Issue时,为了保证您的Issue方便排查,减少沟通成本
>
> 请完善下方的内容, 这段引用起来的文字可以将其删除

## BUG 反馈

**何处触发：**

![搜狗截图20220315184918](https://user-images.githubusercontent.com/61077394/158363279-6440d2c8-3b21-452e-9607-20224981ab03.png)

**实际行为描述：**

![搜狗截图20220315184902](https://user-images.githubusercontent.com/61077394/158366509-b784cc46-f2f4-4482-be39-b215aa7ed9eb.png)

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**

找个歌曲，打开评论区，翻到最下方所有评论，排序方式选成热度，翻页，就会报错

**配置与环境：**

- 音乐链接：Touch-3LAU/Carly Paige
- HyPlayer 版本：2.14.1.0
- 系统版本：21H2

**截图（若有）**

见上

**报错信息**

![搜狗截图20220315184902](https://user-images.githubusercontent.com/61077394/158366805-9d05c3bf-b11c-4e12-9592-a51e1620db2a.png)

**补充信息：**

无
**修复思路：**

无

**Comment by kengwang** [comment]
Fixed in 54f64aa49cd2634258742a8a72857865458ae4e6

**Comment by kengwang** [comment]
Not Fixed
Wait a minute

**Comment by kengwang** [comment]
Due to https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1377
将会修复
