### ISSUE TITLE
日语转罗马音的问题

### ISSUE THREAD

**Issue by Krisky0922** [HyPlayer/HyPlayer#151]
## BUG 反馈

**何处触发：**

在一些特殊日文歌词中

这个问题出在程序的哪一个具体功能？

**实际行为描述：**

日语转罗马音

触发问题后造成了什么效果及影响？

**预期的行为：**

不会输出任何罗马音

这个功能应该有怎样的效果和影响？

**复现步骤：**

找到一首日文歌全是汉字的一句

怎样才能再次触发这个问题？若无法复现可直接写 无法复现

**配置与环境：**

- 音乐链接：https://music.163.com/#/song?id=26096272 （如果有，请提供一个触发此问题的 音乐）
- HyPlayer 版本：2.1.15（Release 标注的版本号，Commit 版则写 Commit 编号）
- 系统版本：Win11 22000.588（正在使用的操作系统, cmd中输入`winver` 即可查看详细信息）

**截图（若有）**

![image](https://user-images.githubusercontent.com/41366404/159121881-859a3713-79fd-4e78-83a4-36e610290867.png)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

提供尽可能多的相关信息。

**修复思路：**

如果全歌词平假/片假名达到一定程度则翻译出罗马音

直接使用网易的罗马音歌词

**Comment by kengwang** [comment]
这是正常情况, 因为有的中文歌曲的歌词不应当转换为罗马音
网易云音乐 APP 应该也是相同的处理
