### ISSUE TITLE
小窗模式没有退出按钮，需要关闭APP才能用

### ISSUE THREAD

**Issue by Suzia-lab** [HyPlayer/HyPlayer#154]
> 感谢您对 HyPlayer 提出建议和反馈,有了您的支持 HyPlayer 将会更好
>
> 在提交Issue时,为了保证您的Issue方便排查,减少沟通成本
>
> 请完善下方的内容, 这段引用起来的文字可以将其删除

## BUG 反馈

**何处触发：**

这个问题出在程序的哪一个具体功能？

**实际行为描述：**

触发问题后造成了什么效果及影响？

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**

怎样才能再次触发这个问题？若无法复现可直接写 无法复现

**配置与环境：**

- 音乐链接：（如果有，请提供一个触发此问题的 音乐）
- HyPlayer 版本：（Release 标注的版本号，Commit 版则写 Commit 编号）
- 系统版本：（正在使用的操作系统, cmd中输入`winver` 即可查看详细信息）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

提供尽可能多的相关信息。

**修复思路：**

**Comment by kengwang** [comment]
双击小窗歌词即可退出

**Comment by kengwang** [comment]
双击小窗歌词即可退出Close #154From KengwangOn Outlook Android
