### ISSUE TITLE
关于图标的误解

### ISSUE THREAD

**Issue by ShiroAsrm** [HyPlayer/HyPlayer#156]
**这是什么方面的想法？**
UI 界面
**这个想法具体是要实现什么？**
修改按键图标或添加注释

**这个想法实现后有什么帮助？**
让用户可以清楚理解按键功能

**是否有具体的实现思路？**
修改图标显示逻辑或者在鼠标悬停在上面的时候显示注释

**补充信息：**
![图片](https://user-images.githubusercontent.com/25266663/162606173-fb366ca2-2c1c-4c5c-b19d-e80e0976b62d.png)
如图，我多次将该图标误理解为单曲循环，但实际上是列表循环，而我认为的列表循环图标是实际是单曲循环。
![图片](https://user-images.githubusercontent.com/25266663/162606223-5f27d99b-5cd9-491d-b255-a4bc15b9390e.png)

**Comment by kengwang** [comment]
将在之后版本修复
