### ISSUE TITLE
动态磁贴

### ISSUE THREAD

**Issue by tjddbc** [HyPlayer/HyPlayer#161]
老哥有兴趣加个动态磁贴吗？

**Comment by kengwang** [comment]
在 Windows 11 下微软移除了动态磁贴, 暂时无法测试.
在之后版本有望在 HyPlayer 中加入但是不保证稳定性

**Comment by tjddbc** [comment]
期待那一天，磁贴才是灵魂




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月17日(星期天) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HyPlayer/HyPlayer] 动态磁贴 (Issue #161)





 
在 Windows 11 下微软移除了动态磁贴, 暂时无法测试.
 在之后版本有望在 HyPlayer 中加入但是不保证稳定性

**Comment by gghh2007** [comment]
希望加个磁贴

**Comment by huhuime** [comment]
> 在 Windows 11 下微软移除了动态磁贴, 暂时无法测试. 在之后版本有望在 HyPlayer 中加入但是不保证稳定性

可以用第3方软件（已上架微软商店）强行糊桌面上，并没有彻底移除

**Comment by tjddbc** [comment]
> > 在 Windows 11 下微软移除了动态磁贴, 暂时无法测试. 在之后版本有望在 HyPlayer 中加入但是不保证稳定性
> 
> 可以用第3方软件（已上架微软商店）强行糊桌面上，并没有彻底移除

是什么软件啊老哥

**Comment by kengwang** [comment]
> > 在 Windows 11 下微软移除了动态磁贴, 暂时无法测试. 在之后版本有望在 HyPlayer 中加入但是不保证稳定性
> 
> 可以用第3方软件（已上架微软商店）强行糊桌面上，并没有彻底移除

如果可以的话，发一下链接看下能否适配

**Comment by huhuime** [comment]
> > > 在 Windows 11 下微软移除了动态磁贴, 暂时无法测试. 在之后版本有望在 HyPlayer 中加入但是不保证稳定性
> > 
> > 
> > 可以用第3方软件（已上架微软商店）强行糊桌面上，并没有彻底移除
> 
> 是什么软件啊老哥

[Live Tiles Anywhere](https://www.microsoft.com/zh-cn/p/live-tiles-anywhere/9nr7qqk712pl?rtc=1&activetab=pivot:overviewtab)

**Comment by huhuime** [comment]
> > > 在 Windows 11 下微软移除了动态磁贴, 暂时无法测试. 在之后版本有望在 HyPlayer 中加入但是不保证稳定性
> > 
> > 
> > 可以用第3方软件（已上架微软商店）强行糊桌面上，并没有彻底移除
> 
> 如果可以的话，发一下链接看下能否适配

[Live Tiles Anywhere](https://www.microsoft.com/zh-cn/p/live-tiles-anywhere/9nr7qqk712pl?rtc=1&activetab=pivot:overviewtab)
理论上不用适配，按原来磁贴方式就行

**Comment by Raspberry-Monster** [comment]
已在
https://github.com/HyPlayer/HyPlayer/commit/f16c83e8b177451f847ec0266b6b6e89e9ca9cdb
https://github.com/HyPlayer/HyPlayer/commit/68cc27f23953c8092d9efb4f592d136d5100828b
https://github.com/HyPlayer/HyPlayer/commit/b529ff41c10e870e75f79839c122719adff972f1
https://github.com/HyPlayer/HyPlayer/commit/d58ad13be45c3f8c4c031874c7d1deab26578d6a
中实现
