### ISSUE TITLE
登录失败：System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by wiidede** [HyPlayer/HyPlayer#162]
## BUG 反馈

**何处触发：**

登录的时候

**实际行为描述：**

- 扫码登录，扫出来的二维码感觉不对，直接是网易云的登录页

- 三方登录，三方账号登录后一直加载

- 密码登陆报错

> 登录失败
登录失败 Type：
System.Net.Http.HttpRequestException Message:
An error occurred while sending the request. Source:
<unknown> StackTrace:
at System.Net.Http.HttpClientHandler.<SendAsync>d_113.MoveNex ---End of stack trace from previous location where exception was thro at System.Runtime.ExceptionServices.ExceptionDispatchlnfo.Throw( at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSucce at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAnd[ +0x38
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task)+ at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d_62.Mov 

**配置与环境：**

- HyPlayer 版本：2.1.18.0(商店里下载的)
- 系统版本：win10

**Comment by YanYan233** [comment]
刚下,也是这个提示，我猜测是不是因为网易云的证书过期了，我登陆官网提示证书不正确了，以前他们也发生过长时间证书过期

**Comment by kengwang** [comment]
是否现在还能复现? 是否查阅 `登录帮助`?
https://blog.kengwang.com.cn/hyplayer-login-help

**Comment by YanYan233** [comment]
> 是否现在还能复现？是否查阅 `登录帮助` ? https://blog.kengwang.com.cn/hyplayer-login-help

确实是小飞机的问题，要么在wiki里写一下您发的这个登陆帮助？好像找不到帮助

**Comment by wiidede** [comment]
> 是否现在还能复现? 是否查阅 `登录帮助`? https://blog.kengwang.com.cn/hyplayer-login-help

@kengwang 我看了，我也用clash 的 UWP Lookback勾中HyPlayer了，我其他uwp应用都没有问题，我必须走代理，因为公司禁了网易云的访问🤣而且我点三方登陆，页面是可以打开的呀，但是登陆之后，HyPlayer就没反应了

**Comment by wiidede** [comment]
有点离谱的是，我用手机开个热点就好了，我甚至没有关clash，我感觉可能是某个接口直接被公司内网屏蔽了吧（虽然我全局代理也登录不上），抱歉😂

**Comment by kengwang** [comment]
在 设置 - 实验室 中填入任意内容以便降级 HTTPS

**Comment by wiidede** [comment]
> 在 设置 - 实验室 中填入任意内容以便降级 HTTPS

牛啊，原来是软件自己有代理，我大意了，怪不得clash log里没看到请求。设置成clash的代理就行了。我以为简单的uwp应用不会有自己的代理，牛啊牛啊🥰
