### ISSUE TITLE
建议功能：下载按 专辑/乐手/播放列表 分子文件夹

### ISSUE THREAD

**Issue by ibin7777** [HyPlayer/HyPlayer#163]
**这是什么方面的想法？**

现有内容的优化

**这个想法具体是要实现什么？**

想要批量下载歌单，发现缺少按歌单分独立文件夹的选项。
当然可以临时更改文件夹来弥补缺陷，但是这样会让原播放器识别不到之前已下载内容。
希望添加这个功能。

**Comment by kengwang** [comment]
可以在设置 - 存储设置 中看到下载文件命名
捏可以在文件命名中添加预定义变量结合上 `/`
例如: `{$ALBUM}/{$SONGNAME}` 即按照专辑分文件夹

**Comment by kengwang** [comment]
自由度很高的, 因为我觉得只提供选项让选自由度很低
