### ISSUE TITLE
下载时{$SINGER}字段不读取歌曲的"Contributing artists"信息，而是读取"Album artist"，播放列表中无法正常显示个人上传歌曲的信息

### ISSUE THREAD

**Issue by RJiazhen** [HyPlayer/HyPlayer#165]
## BUG 反馈

**何处触发：**

浏览播放列表和进行歌曲下载时。

**实际行为描述：**

* 下载歌曲时，{$SINGER}字段也是读取的"Album artist"信息，导致个人上传的歌曲如果未填写"Album artist"信息（Mp3tag软件不方便填写Album artist信息），则下载的歌曲的文件名中{$SINGER}部分会留空，不利于歌曲管理和避免重复下载本地歌曲。
而且个人比对后发现，所有下载的flac后缀文件的"Album artist"均与"Contributing artists"相同（哪怕两者信息实际不一样）。
* 播放列表中不显示云盘歌曲除了标题以外的任何信息（包括"Contributing artists"，"Album artist"，专辑封面等）。

**预期的行为：**

理想情况应该正常读取"Contributing artists"信息，以保证显示正常和下载后文件名和文件信息正常。

**复现步骤：**

- 下载文件问题推荐下载《キメラ》这张专辑的歌曲，因为其中几乎每首歌的作者都不同，下载后可发现每首歌曲的"Album artist"都不同（理论上同首专辑的歌曲该信息应相同），且都和"Contributing artists"一样。
- 显示问题可以下载任意歌曲后，只修改"Title"信息再直接上传，然后添加到相应列表以测试。

**配置与环境：**

- 音乐链接：[《キメラ》](http://music.163.com/album?id=134545901&userid=283076062)。
- HyPlayer 版本：win10商店版，version 2.1.18.0
- 系统版本：windows10专业版 21H2(OS Build 19044.1645)

**截图（若有）**

![image](https://user-images.githubusercontent.com/103310338/164978701-c6090a0c-19ae-4089-9850-baf4c9a29660.png)
下方为网易云原歌曲，上方为只修改"Title"后重新上传的歌曲，无法正常显示其他信息

**报错信息**
无

**补充信息：**
无

**修复思路：**

> 所有下载的flac后缀文件的"Album artist"均与"Contributing artists"相同（哪怕两者信息实际不一样）

个人使用ncmdump软件转ncm格式文件也遇到完全一样的问题，可以考虑是转格式软件的问题

**Comment by kengwang** [comment]
这个是由于网易云音乐返回数据的问题, 网易云音乐只返回这个, 我也没法

**Comment by RJiazhen** [comment]
> 这个是由于网易云音乐返回数据的问题, 网易云音乐只返回这个, 我也没法

那是否方便增加修改文件信息功能，对下载后的文件进行再处理？
例如 将下载的flac文件的"Album artist"信息清空，以及如果{$SINGER}信息为空就再读取"Contributing artists"信息，修改文件名对应的部分

**Comment by Raspberry-Monster** [comment]
现在就是将下载文件的信息同步为网易云返回的数据，网易给什么我们就写什么，这个我们无法控制QAQ
