### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Afire-625** [HyPlayer/HyPlayer#167]
## BUG 反馈

**何处触发：2.1.19点击设置立即闪退

这个问题出在程序的哪一个具体功能？

**实际行为描述：**

触发问题后造成了什么效果及影响？

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**

怎样才能再次触发这个问题？若无法复现可直接写 无法复现

**配置与环境：**

- 音乐链接：（如果有，请提供一个触发此问题的 音乐）
- HyPlayer 版本：2.1.19
- 系统版本：19044.1618
**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

提供尽可能多的相关信息。

**修复思路：**

**Comment by FeelLiao** [comment]
I have the same problem.

**Comment by kengwang** [comment]
问题已知，下个版本将在今晚发布

**Comment by Afire-625** [comment]
> 问题已知，下个版本将在今晚发布

辛苦辛苦……问问是发布在Micsoft store，还是发在这呢
