### ISSUE TITLE
界面按钮边缘锯齿

### ISSUE THREAD

**Issue by ibin7777** [HyPlayer/HyPlayer#168]
![image](https://user-images.githubusercontent.com/64576479/165819857-b854ffe9-a7aa-4443-96fa-c7b281f858a9.png)
不是很明显，无伤大雅，忽然注意到了就写在这

fyi：2560x1440显示器

**Comment by Whaleser** [comment]
同

**Comment by Raspberry-Monster** [comment]
这个无法修复 不过在新版本中可以将这个强调色给取消，这样就看不到了（）
