### ISSUE TITLE
用返回键回退页面时navigationview没有做出相应响应

### ISSUE THREAD

**Issue by EP012014** [HyPlayer/HyPlayer#17]
> 感谢您对 HyPlayer 提出建议和反馈,有了您的支持 HyPlayer 将会更好
>
> 在提交Issue时,为了保证您的Issue方便排查,减少沟通成本
>
> 请完善下方的内容, 这段引用起来的文字可以将其删除

## BUG 反馈

**何处触发：**

这个问题出在程序的哪一个具体功能？
左侧navigationview

**实际行为描述：**

触发问题后造成了什么效果及影响？
使用返回按键发挥上一个页面时，左侧的当前选中页面不改变

**预期的行为：**

这个功能应该有怎样的效果和影响？
左侧那个小条条滑到主页上

**复现步骤：**

怎样才能再次触发这个问题？若无法复现可直接写 无法复现

导航到设置页面，用返回键返回主页
**配置与环境：**

- 音乐链接：（如果有，请提供一个触发此问题的 音乐）
- HyPlayer 版本：（Release 标注的版本号，Commit 版则写 Commit 编号）
- 系统版本：（正在使用的操作系统, cmd中输入`winver` 即可查看详细信息）
19042
**截图（若有）**
![image](https://user-images.githubusercontent.com/67152455/116809397-6d196600-ab70-11eb-82fe-80771788cdc2.png)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

提供尽可能多的相关信息。

**修复思路：**

**Comment by EP012014** [comment]
已经在PR中修复 #20

**Comment by kengwang** [comment]
Merged
