### ISSUE TITLE
贴靠窗口后不显示收藏及循环模式按钮

### ISSUE THREAD

**Issue by littlef0x** [HyPlayer/HyPlayer#172]
## BUG 反馈

**何处触发：**

收藏及循环模式按钮

**实际行为描述：**

当窗口贴靠一侧（即占用屏幕一半横向空间）时，不显示收藏及循环模式两个按钮，手动拉宽2像素后显示。
自动贴靠（窗口宽度1277px）：
![图片](https://user-images.githubusercontent.com/32670075/166666291-182a6356-9b62-4f76-9fe5-cf73ca196794.png)

手动调整后（窗口宽度1279px）：
![图片](https://user-images.githubusercontent.com/32670075/166666207-87b706d4-eeea-4b23-a4af-cfa2292d2aaa.png)

我理解在窗口过窄时需要隐藏部分按钮，但贴靠之后的宽度足够显示这两个按钮，而每次都需要手动调整，则失去了贴靠窗口的便利性。

**预期的行为：**

应在自动贴靠后依然显示这两个按钮。

**复现步骤：**

拖动HyPlayer窗口到屏幕一侧或一角触发自动贴靠。

**配置与环境：**

- HyPlayer 版本：2.1.20.0
- 系统版本：Windows 11 22000.613

**截图（若有）**

见上。

**报错信息**

无。

**补充信息：**

显示器分辨率2560*1440

**修复思路：**

调整触发按钮隐藏的宽度阈值。

**Comment by kengwang** [comment]
何不再小点, 再小点的话就会有个更多按钮
(之后会商榷下中等宽度下的按钮表现)

**Comment by littlef0x** [comment]
> 何不再小点, 再小点的话就会有个更多按钮 (之后会商榷下中等宽度下的按钮表现)

是的，不过无论是调大还是调小，都违背了贴靠的初衷，毕竟就是因为不用找窗口边缘手动调才使用的呀。
个人觉得随着窗口缩小，直接由5个按钮的布局变为带有“更多”的布局即可，没有必要经过三个按钮的布局，至于阈值可以比屏幕一半小一点。

**Comment by kengwang** [comment]
三个按钮布局已经被移除
