### ISSUE TITLE
windows11安装在Windows11是不是有很多的问题？

### ISSUE THREAD

**Issue by lineshare** [HyPlayer/HyPlayer#175]
> 感谢您对 HyPlayer 提出建议和反馈,有了您的支持 HyPlayer 将会更好
>
> 在提交Issue时,为了保证您的Issue方便排查,减少沟通成本
>
> 请完善下方的内容, 这段引用起来的文字可以将其删除

## BUG 反馈

**何处触发：点击歌曲不播放，点击主页和每日推荐都显示：object reference not set to an instance of an object
exception of type 'system.exception' was thrown

触发问题后造成了什么效果及影响？

**预期的行为：基本上完全无法使用，基本上都会显示object reference not set to an instance of an object
exception of type 'system.exception' was thrown

**配置与环境：
- HyPlayer 版本：（Release 2.1.2.0）
- 系统版本：WINDOWS 11 21H2版本

**截图（若有）**
![image](https://user-images.githubusercontent.com/62013006/168989042-91332532-4f49-4815-9bef-b85771ec24a3.png)

![image](https://user-images.githubusercontent.com/62013006/168989134-eb7dddd0-0ee9-4cd2-baca-6ad81a048a2a.png)
![image](https://user-images.githubusercontent.com/62013006/168989209-6cd5bdae-3ff5-4190-bc07-1c1954e6fe0a.png)

![image](https://user-images.githubusercontent.com/62013006/168989267-99214c6c-3276-464e-aef7-6b14b6633233.png)

**Comment by lineshare** [comment]
我没有开启缓存，同样还是不能播放。
![image](https://user-images.githubusercontent.com/62013006/169253597-dea770cc-5700-46c3-a6fb-f80d47c00195.png)
![image](https://user-images.githubusercontent.com/62013006/169253788-9d36c5d3-7849-48fc-8692-d3ffbcb4619d.png)

**Comment by kengwang** [comment]
此问题我这边无法复现，可能是系统的配置问题导致的。请检查系统的相关配置，例如音频输出设备等是否正常。
Won't fix.
---
如果仍然有问题可以在此 Issue 下继续回复

**Comment by shikkoku** [comment]
![Screenshot 2022-06-22 124309](https://user-images.githubusercontent.com/4697177/174945198-e76296f8-0bba-4444-b052-fe85f0c62a47.jpg)
2.1.24.0 商店版在Windows 11 22621 则是遇到无法下载的问题。同样未开启缓存。

**Comment by kengwang** [comment]
已知问题，下个版本修复。下载功能相关体验将进行修复
