### ISSUE TITLE
专辑增加 添加全部 按钮

### ISSUE THREAD

**Issue by ShiroAsrm** [HyPlayer/HyPlayer#177]
**何处触发：**

专辑页播放

**实际行为描述：**

点击专辑页"播放全部"按钮后该专辑乐曲添加至整个播放列表末尾，并重新开始播放当前乐曲；右键"播放全部"按钮，菜单中选择"下一首播放"后仅添加专辑第一首乐曲进入播放列表下一首，剩余乐曲不加入。

**预期的行为：**

点击专辑页"播放全部"按钮后将该专辑乐曲覆盖播放列表，菜单中选择"下一首播放"后将整个专辑塞入播放列表下一位。

**复现步骤：**

专辑页操作即可。

**配置与环境：**
- HyPlayer 版本：2.1.20.0
- 系统版本：Win11 21H2 22000.708

**修复思路：**

如预期行为，并在右键菜单添加将专辑整个添加到列表末尾的选项（等同目前播放全部按钮逻辑）。

**Comment by kengwang** [comment]
这个问题将在下个版本修复

**Comment by kengwang** [comment]
Release 和 Beta 版已经修复
Fixed in `837cfe128e9aa22782d96020be1eb4ff590e8555`

**Comment by ShiroAsrm** [comment]
右键-下一首播放还是只塞了一首歌，看上去整个逻辑可能要改一下？

**Comment by kengwang** [comment]
右键菜单是根据单首歌曲的, 将会在后续版本假如 添加全部 按钮
我 reopen 一下改下标题

**Comment by ShiroAsrm** [comment]
然后实际上专辑页的按钮是添加选中的那一首歌曲，此处逻辑应该分开。下一首就放在选歌的菜单，专辑页就放添加整个的。
另外，下一首播放可以无限塞同一首歌，是不是有点反直觉（

**Comment by kengwang** [comment]
已经添加，新版已经推送到 Beta 和 Release？
