### ISSUE TITLE
音质选项无效

### ISSUE THREAD

**Issue by ShiroAsrm** [HyPlayer/HyPlayer#179]
## BUG 反馈

**何处触发：**

设置在线播放音质选项无效

**实际行为描述：**

修改设置为无损后仍然播放HiRes

**预期的行为：**

无损就播无损

**复现步骤：**

手动把在线播放音质选项拉到无损

**配置与环境：**

- 音乐链接：https://music.163.com/#/song?id=1309901466
- HyPlayer 版本：2.1.21.0
- 系统版本：Win11 21H2 22000.708

**补充信息：**

未测试下载

**修复思路：**
无

**Comment by kengwang** [comment]
这是由于 Hi-Res 目前 HyPlayer 中的判断是根据返回的 br (Bitrate) 来的, br 超过了无损上限 `999000` 就判断为 Hi-Res

**Comment by kengwang** [comment]
https://en.wikipedia.org/wiki/High-resolution_audio
根据 Wikipedia 的介绍, 高解析度音频 ( High Resolution Audio, aka Hi-res) 的定义为 **采样率** 超过 `44.1 kHz` 或 **位深** 高于 16-bit 的音频
现行的使用 **比特率** 判定确实不妥, 之后会进行修正

**Comment by kengwang** [comment]
网易云音乐新增的上游 API , 可以更加精确的指定音质
https://github.com/Binaryify/NeteaseCloudMusicApi/commit/647396f38ce4cc33acf303d37ce06f91500f63cf
将会在下个版本实现
