### ISSUE TITLE
可以给歌词添加一种模糊效果吗

### ISSUE THREAD

**Issue by hinatamiyabi** [HyPlayer/HyPlayer#182]
如图：
![Snipaste_2022-06-13_10-46-51](https://user-images.githubusercontent.com/104922774/173270946-42e9bd2d-04ff-4b5b-a394-23ca11dbc287.png)

**Comment by kengwang** [comment]
隔壁做了这个独创功能，就让他成为隔壁的特色吧。
不想刻意去模仿，引来流言蜚语。

**Comment by hinatamiyabi** [comment]
不过这个特色好像也是从apple music那借过来的吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月13日(星期一) 上午10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HyPlayer/HyPlayer] 可以给歌词添加一种模糊效果吗 (Issue #182)





 
隔壁做了这个独创功能，就让他成为隔壁的特色吧。
 不想刻意去模仿，引来流言蜚语。
