### ISSUE TITLE
一处UI Button 颜色建议

### ISSUE THREAD

**Issue by srcenchen** [HyPlayer/HyPlayer#184]
关于 UI 界面 的建议
![image](https://user-images.githubusercontent.com/48435089/174319031-85d53092-d471-4a97-a981-63cd380ea8b7.png)
希望把这个地方的Button文本颜色改为白色，还有一处就是喜欢歌单那里的心动模式的颜色也改为红底白字，这样看上去比较舒服一些
希望能够把这两个小细节改一下

**Comment by kengwang** [comment]
考虑考虑

**Comment by kengwang** [comment]
新版 UI 已经修复
