### ISSUE TITLE
关于这个版本的一些问题

### ISSUE THREAD

**Issue by Gaoyifei1011** [HyPlayer/HyPlayer#19]
1.关于登录窗口的关闭窗口按钮的位置，希望能够放到右上角，这个位置有点不符合平常关闭按钮的窗口位置。
![image](https://user-images.githubusercontent.com/49179966/118391815-cef5c780-b668-11eb-8067-8c202232ec16.png)
2.希望能够优化一下左侧导航栏按钮的设定，比如点击登录，然后取消登录后，这个选中的条目会停留在登录，而不会返回原来的位置。
![image](https://user-images.githubusercontent.com/49179966/118391832-df0da700-b668-11eb-9b63-dcaf50065e61.png)
3.希望能够优化一下面板的背景颜色与文字的设定，比如在设置面板中，背景使用的是暗色，而且文字也是使用的是暗色，容易发生文字看不清的情况，希望能够优化一下
![image](https://user-images.githubusercontent.com/49179966/118391870-12503600-b669-11eb-8164-7fdb8c382556.png)
4.下载目录设定后希望在旁边添加一个打开文件夹的按钮，方便人们直接查看下载的音乐文件
![image](https://user-images.githubusercontent.com/49179966/118391913-44619800-b669-11eb-9819-7369c98d013d.png)
5.关于磁贴的显示问题，希望能够在应用清单文件中添加以下应用的名称显示
![image](https://user-images.githubusercontent.com/49179966/118391961-7a9f1780-b669-11eb-86e0-b3e055190f7c.png)
也就是有关这一部分的设定
![image](https://user-images.githubusercontent.com/49179966/118391972-8f7bab00-b669-11eb-9215-c6b4409178cc.png)
6.希望楼主可以注意一下音乐的下载问题，这个可能涉及到版权了吧，比如在网易云音乐上面下载付费音乐的时候会要求收费后在听，但是在这个应用中下载付费音乐会直接下载，希望开发者能够注意一下这个问题。比如说下载艾辰的错位时空，网易云音乐下载需要付费，这个应用会直接下载。

**Comment by kengwang** [comment]
感谢反馈，下载的话我下个版本就会移除掉功能入口。 磁贴的话确实，我一直都没管…… 
背景的话是因为我的Light.xaml中的参数写错了，所以导致显示出错（本来应当显示左下角的亮色区，现在显示右上角的暗色区了）

**Comment by kengwang** [comment]
侧边栏的条条我是有点无奈的，也在想解决方法，怎么设计这个UX QAQ

**Comment by kengwang** [comment]
登录按钮的关闭位置确实反人类 （笑），当时脑袋抽了的时候写的

**Comment by kengwang** [comment]
侧边栏问题在 #17 讨论

**Comment by Gaoyifei1011** [comment]
建议你的侧边栏在下一次构建的时候可以设计成IT之家左侧栏那样，又简洁，大方，而且又不像汉堡菜单完全打开会留下那么多的空白，目前这个汉堡菜单缩回去图标显得有点小，放开了又占地方

**Comment by kengwang** [comment]
Fixed since ac7b036

**Comment by kengwang** [comment]
那个打开路径弄不了

**Comment by kengwang** [comment]
下载功能已经关闭,假如有兴趣的话可以了解下是如何关闭的
