### ISSUE TITLE
无法播放音乐

### ISSUE THREAD

**Issue by Minecrafter-Pythoner** [HyPlayer/HyPlayer#224]
## BUG 反馈

**何处触发：

程序无法播放任何音乐

**实际行为描述：**

任何使得程序开始试图播放音乐的行为都无法使程序输出音频，并伴有报错弹窗

**预期的行为：**

程序应当开始播放音乐

**复现步骤：**

报错弹窗每次启动程序后首次试图播放音乐都会弹出

**配置与环境：**

- 音乐链接：https://music.163.com/#/song?id=1891389807
-            注：经过测试，所有音乐均无法播放
- HyPlayer 版本：Release 2.1.30
- 系统版本：Win10 21H2  Build 19044.1826

**截图（若有）**

![image](https://user-images.githubusercontent.com/58333458/182536799-21d62df0-84f6-4aed-87ec-c51e27e5e8ee.png)

**报错信息**

播放失败 切换到下一首
播放核心：SourceNotSupported

**补充信息：**

此问题在今日上午11：30于当时MS Store最新版本首次发现，任何音乐均无法播放，从github下载安装2.1.30后依旧如此
注：我的账号是黑胶会员，播放与下载音质均为Hi-Res，最近一个月没有修改过软件设置

**修复思路：**
无（可能网易改接口了？）

**Comment by kengwang** [comment]
* 请关闭 设置 - 实验室 - 使用播放缓存
* 请检查其他软件是否可以正常播放声音

**Comment by Minecrafter-Pythoner** [comment]
“使用播放缓存”并未开启
其他软件都可以正常播放声音

**Comment by kengwang** [comment]
可以尝试在 设置 - 播放设置 - 输出设置 中选择 恢复默认

**Comment by kengwang** [comment]
可以试试隔壁 LyricEase 是否可以正常播放

**Comment by Minecrafter-Pythoner** [comment]
> 可以尝试在 设置 - 播放设置 - 输出设置 中选择 恢复默认

恢复默认后好了，感谢！

**Comment by Minecrafter-Pythoner** [comment]
（小声问一句这是什么原因
   毕竟报错是播放核心相关的
   为什么恢复默认音频输出设备可以解决？

**Comment by kengwang** [comment]
> （小声问一句这是什么原因 毕竟报错是播放核心相关的 为什么恢复默认音频输出设备可以解决？

可能是输出设备有问题导致播放核心无法输出音频从而崩溃

**Comment by Minecrafter-Pythoner** [comment]
emm....我用笔记本连电视，把电视当显示器用，前面一直好好的，今天突然就出问题了
（好玄学
