### ISSUE TITLE
[BUG] 播放失败后切到下一曲的行为异常

### ISSUE THREAD

**Issue by kengwang** [HyPlayer/HyPlayer#229]
## BUG 反馈

**何处触发：**

HyPlayerList

**实际行为描述：**

播放失败后音源仍是当前文件, 但信息为下一首

**预期的行为：**

音源和信息一致

**Comment by Raspberry-Monster** [comment]
Fixed in [ #762373](https://github.com/HyPlayer/HyPlayer/commit/7623733ae805776c3be47895b596f4b4be656a8c)
