### ISSUE TITLE
封面点击后下面的按钮应该改为切换而不是`添加到歌单`

### ISSUE THREAD

**Issue by heartacker** [HyPlayer/HyPlayer#244]
**这是什么方面的想法？**

UI 界面 / 用户体验

**这个想法具体是要实现什么？**
点击 底部的封面之后，封面下面的按钮改为切换。
![image](https://user-images.githubusercontent.com/1876302/183895873-1553ce26-4638-4760-af55-2bb5f53c98c8.png)
![image](https://user-images.githubusercontent.com/1876302/183895933-a3a0dc75-59e6-42a4-ad13-9ebec357b2b9.png)

1. 防止误触
2. 符合操作逻辑。
3. 优化用户习惯
4. 符合大脑思维

**这个想法实现后有什么帮助？**

鼠标点击顺手了
不怕双击了

**是否有具体的实现思路？**
1. 将封面对应下面的`添加到歌单`的按钮改为切换全屏按钮。这边的按钮全部右移

**补充信息：**
1. 用户习惯点击封面，进去全屏模式。（封面有图像，更加吸引关注）
2. 按照习惯，应该再点击一次同样的位置，推出全屏
3. 如果有人双击。（确实有很多人喜欢点击变成双击），那么相当于触发了添加到歌单

**Comment by kengwang** [comment]
这个好诶, UX 逻辑挺流畅的
