### ISSUE TITLE
关于登录界面的一些问题

### ISSUE THREAD

**Issue by Gaoyifei1011** [HyPlayer/HyPlayer#25]
当登录界面出现空字符登录时会出现异常，希望能够处理一下
![屏幕截图 2021-05-25 020341](https://user-images.githubusercontent.com/49179966/119510017-bf325d80-bda3-11eb-9896-1435ff9b7e35.png)
当登录成功后登录界面不会自动退出
![屏幕截图 2021-05-25 020517](https://user-images.githubusercontent.com/49179966/119510061-ce191000-bda3-11eb-9f9c-22a39a99be2a.png)
默认没有歌词播放时希望可以显示一个默认值：暂未播放歌曲
![Inked屏幕截图 2021-05-25 020651_LI](https://user-images.githubusercontent.com/49179966/119510214-edb03880-bda3-11eb-897a-f6510793150a.jpg)

**Comment by EP012014** [comment]
好的，尽快解决

**Comment by EP012014** [comment]
已经解决
94b136b260b377445d5d6db229e9ae9d1065edb6
