### ISSUE TITLE
打开后自动全屏问题

### ISSUE THREAD

**Issue by Suzia-lab** [HyPlayer/HyPlayer#250]
为什么应用打开后会自动全屏，还没有开关的按钮，体验很奇怪，目前主流音乐应用也没有这样的ux体验，能不能把这个设定取消或者加一个开关

**Comment by kengwang** [comment]
已收到, 在之前是否开启过全屏, 且在未退出全屏的情况下关闭了应用
由于 UWP 的策略, 此种情况会导致之后开启都是全屏.
将会在之后版本尝试修复

**Comment by kengwang** [comment]
Update in 17f8b302006ab8a0bb37512aa6ae5d75eb59be54
尝试进行了修复, 在每次开启时会退出全屏模式
