### ISSUE TITLE
标题栏按钮颜色显示问题，以及播放栏内容显示问题

### ISSUE THREAD

**Issue by ccyykkcyk** [HyPlayer/HyPlayer#251]
> 感谢您对 HyPlayer 提出建议和反馈,有了您的支持 HyPlayer 将会更好
>
> 在提交Issue时,为了保证您的Issue方便排查,减少沟通成本
>
> 请完善下方的内容, 这段引用起来的文字可以将其删除

## BUG 反馈

**何处触发：**
任何页面
这个问题出在程序的哪一个具体功能？
ui显示
**实际行为描述：**
标题栏按钮和背景色相同，几乎不可见
触发问题后造成了什么效果及影响？
![image](https://user-images.githubusercontent.com/91893497/187031981-43cb8d9b-6fdf-4fd6-bd30-abfe4a6559f4.png)
上图可见，标题栏上三个按钮和背景一个颜色，播放栏上歌曲名称显示不完整，上部被截掉了一点
**预期的行为：**
浅色标题栏，应该用颜色深一点的按钮颜色，播放栏内容应该完整显示
这个功能应该有怎样的效果和影响？

**复现步骤：**
打开程序必定复现

**配置与环境：**

- 音乐链接：（如果有，请提供一个触发此问题的 音乐）
- HyPlayer 版本：（Release 标注的版本号，Commit 版则写 Commit 编号）
  Version 2.1.32.5161  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：（正在使用的操作系统, cmd中输入`winver` 即可查看详细信息）
  win10 21h2 19044.1949
**截图（若有）**
![image](https://user-images.githubusercontent.com/91893497/187032116-5aae8024-cc40-4343-bb0f-3cfeba14b9fe.png)
![image](https://user-images.githubusercontent.com/91893497/187032126-68a369b9-1286-42af-97f3-75a774c275e5.png)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

提供尽可能多的相关信息。

**修复思路：**

**Comment by kengwang** [comment]
> 标题栏按钮和背景色相同，几乎不可见

这个是有意的, 为了沉浸感

我这边第二个问题无法复现
![image](https://user-images.githubusercontent.com/30862240/187035853-260f4e02-0539-4d6d-a1b6-04e42cb69aa2.png)

**Comment by ccyykkcyk** [comment]
> > 标题栏按钮和背景色相同，几乎不可见
> 
> 这个是有意的, 为了沉浸感
> 
> 我这边第二个问题无法复现 ![image](https://user-images.githubusercontent.com/30862240/187035853-260f4e02-0539-4d6d-a1b6-04e42cb69aa2.png)

沉浸吗，好吧。
看起来你这个也是上面被截了几个像素的高度吧
![image](https://user-images.githubusercontent.com/91893497/187035996-d5ecf23b-9a63-4b96-9d29-d13d233403a2.png)

**Comment by kengwang** [comment]
好细节, Mark 一下, 等有空修

**Comment by ccyykkcyk** [comment]
> 好细节, Mark 一下, 等有空修

要关掉这个issue吗

**Comment by kengwang** [comment]
不需要, Issue 存在的意义就是方便追踪, 免得忘

**Comment by ccyykkcyk** [comment]
好的

**Comment by kengwang** [comment]
> 标题栏按钮和背景色相同，几乎不可见

新增了这个设置项
![image](https://user-images.githubusercontent.com/30862240/198869859-9b57de16-7779-4f3d-be01-db0936235238.png)

**Comment by kengwang** [comment]
中间态也已经被取消
