### ISSUE TITLE
播放本地音乐时出现的一些错误

### ISSUE THREAD

**Issue by ccyykkcyk** [HyPlayer/HyPlayer#266]
## BUG 反馈

**何处触发：**

本地音乐播放时的一些错误

**实际行为描述：**

1. 播放点击播放全部本地音乐，上一首播完，自动切换下一首时，右上角弹窗提示错误
![image](https://user-images.githubusercontent.com/91893497/191026791-f579df34-f541-4859-8300-332380b7b80f.png)

2. 本地音乐播放时，点击播放栏上的封面进入歌词页面，弹窗报错，然后自动切换下一首
![image](https://user-images.githubusercontent.com/91893497/191026914-ac039ecf-9088-418b-a1a5-c3228bcc5f10.png)

**预期的行为：**

对于行为1，播完自动切换不应该报错，而是正常切换
对于行为2，播放时，进入歌词页，应该继续播放当前音乐

**复现步骤：**

在hyplayer中，播放本地音乐

**配置与环境：**

- 音乐链接：（如果有，请提供一个触发此问题的 音乐）
- HyPlayer 版本：Version 2.1.33.5196
- 系统版本：Windows 10 21H2(19044.2006)

**截图（若有）**

实际行为描述中附截图

**Comment by ndbcd** [comment]
同有

**Comment by Raspberry-Monster** [comment]
Fixed in https://github.com/HyPlayer/HyPlayer/commit/940b9013f4c76ae98211ea4db3534ff18a96baea
