### ISSUE TITLE
[Bug Report] 提示更新旧版本

### ISSUE THREAD

**Issue by FrzMtrsprt** [HyPlayer/HyPlayer#275]
## BUG 反馈

**何处触发：**

软件启动时，以及关于页点击检查更新

**实际行为描述：**

检查到的更新比已部署版本更旧

**预期的行为：**

最新版本号小于应用版本号时，什么都不做，而不是提示更新

**复现步骤：**

前往关于页，将更新渠道设为 App Center，点击检查更新

**配置与环境：**

- 音乐链接：N/A
- HyPlayer 版本：5225
- 系统版本：N/A

**截图（若有）**

N/A

**报错信息**

```
N/A
```

**补充信息：**

无

**修复思路：**

最新版本号小于应用版本号时，什么都不做，而不是提示更新
```
// ./HyPlayer/Classes/UpdateManager.cs

if (remoteResult.Version == null || remoteResult.Version <= localVersion)
        {
            if (isStartup) return;
            title = "你已是最新版";
        }
```

**Comment by kengwang** [comment]
Mark 一下, 之后更新模块也会大改一下
