### ISSUE TITLE
[FR] 脱离系统代理的“代理服务器设置”

### ISSUE THREAD

**Issue by GrassBlock1** [HyPlayer/HyPlayer#287]
**这是什么方面的想法？**
独立于系统的代理服务器设定

在翻阅了官方文档等资料以及一些测试后，发现“实验室”中“代理服务器”这一选项似乎是个空壳，并不能使用诸如HTTP代理（http://domain:port）的选项，只能调用系统代理。

**这个想法具体是要实现什么？**
使hyplayer拥有和原版相似的代理设置，而不仅仅调用系统代理

**这个想法实现后有什么帮助？**
防止本地音源解锁与其它代理软件的冲突

**是否有具体的实现思路？**
~~后端代码生疏，只能写写~~
代理部分增加 HTTP 代理和系统代理、不使用代理等选项
~~可参考 Unigram~~

**补充信息：**
*如果有疏漏或错误可以说明原因/方法后关issue*

**Comment by Raspberry-Monster** [comment]
首先，感谢您的Issue
由于UWP应用的限制，软件只能使用系统代理，我们在实验室中留下此功能是为了方便UNM用户使用时降级Https
Unigram的话我去看了下，应该是通过外挂Win32应用实现的。
后面有机会的话应该会在WinUI3.0版本中实现

Best Regards,
Raspberry Kan

**Comment by GrassBlock1** [comment]
> 

好，谢谢您，期待更新。
