### ISSUE TITLE
[FR] 重构分发方式

### ISSUE THREAD

**Issue by kengwang** [HyPlayer/HyPlayer#293]
**在此 Issue 完成前请勿再次进行分发**
**在此 Issue 完成前请勿再次进行分发**
**在此 Issue 完成前请勿再次进行分发**

## 问题基本概述

**这是什么方面的想法？**

对于现行的分发方式的优化

**这个想法具体是要实现什么？**

修改现行分发方式, 由于需要多平台分发, 多通道分发
现行的分发方式无法满足需求
需要对其进行修改

## 目前遇到的情况

我们需要将每次提交到 DevOps 的编译进行自动分发到对应通道(s)
并且同时订阅者将会收到通知并通过内测页面进行下载自己所需架构版本

当前分发方式存在以下问题:

* 发布的包体积过大 (理想每次更新 50MB 以下)
* 双通道推送会使 Telegram 通知两次
* 错误将符号文件分发到了用户
* 初次安装的用户并不知道如何进行安装

## 可能会进行的修改

* 理想应当对每个版本进行增量分发
* 应减少包体积大小
* 多播分发应当更加合理

**Comment by Raspberry-Monster** [comment]
由于生成了msixbundle文件，实际上ARM64和x64是在同一个包分发，所以架构是可以不太需要去选择的

**Comment by Raspberry-Monster** [comment]
现在CI那边主要的问题是Dependencies文件夹占用过大和错误分发appxsym文件

**Comment by Raspberry-Monster** [comment]
appxsym的bug晚点会修复，Dependencies文件夹的体积可能比较难缩小

**Comment by RERASER** [comment]
能不能尽可能地把每部分拆成单独的包，然后用一个下载器去下载安装缺失部分
