### ISSUE TITLE
[FR] 希望打开时能继续从上次关闭（结束）的位置播放

### ISSUE THREAD

**Issue by limbia** [HyPlayer/HyPlayer#300]
我记得之前是这样的啊，现在怎么又不行了。。打开时自动显示为结束时播放的那首歌，免得又得翻一遍，还有每次打开时在earthumpet里都是满音量。。这两点都是和网易云本体操作个人感觉不太融洽适应的地方，从网易过渡过来就有点不丝滑，望修正^-^

**Comment by kengwang** [comment]
目前是有这个功能的, 请检查是否在实验室关闭了下图所示的选项
![image](https://user-images.githubusercontent.com/30862240/204086648-de1a3651-b2f9-4900-9c39-85343bd3ca27.png)

目前由于技术原因, 暂时无法留存电台(播客)音乐及本地音乐播放记录, 请知悉

**Comment by kengwang** [comment]
我这边开始复现, 目前正在排查

**Comment by kengwang** [comment]
目前可以通过直接点击播放按钮来进行继续播放
