### ISSUE TITLE
考虑加个全局快捷键嘛？

### ISSUE THREAD

**Issue by Misaka2298** [HyPlayer/HyPlayer#304]
如题，觉得有个全局快捷键功能会好用很多

比如按（快捷键）暂停/播放
按（另一个快捷键）上一曲
之类的

**Comment by Clrs17** [comment]
这个是开发平台的限制
不过应用处于前台的时候是可行的
后台的话可以考虑一下键盘映射

**Comment by Raspberry-Monster** [comment]
Dup https://github.com/HyPlayer/HyPlayer/issues/96#issuecomment-1076469421

**Comment by Raspberry-Monster** [comment]
另 可以使用PowerToys映射媒体键以达到相同效果
