### ISSUE TITLE
安装提示证书不受信任

### ISSUE THREAD

**Issue by Norsk-SkogKatt** [HyPlayer/HyPlayer#305]
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x800B0109, 已处理证书链，但是在不受信任提供程序信任的根证书中终止。
错误 0x800B0109: 应用包或捆绑包中的签名的根证书必须是受信任的证书。
注意: 有关其他信息，请在事件日志中查找 [ActivityId] a5617f33-03a8-0000-ba74-62a5a803d901，或使用命令行 Get-AppPackageLo
g -ActivityID a5617f33-03a8-0000-ba74-62a5a803d901
所在位置 行:1 字符: 1
+ Add-AppxPackage .\HyPlayer_2.1.35.5340_x64_ARM64.msixbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\Admini...RM64.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Time                      ID           Message
----                      --           -------
2022/11/29 12:31:01       603          已使用主参数 HyPlayer_2.1.35.5340_x64_ARM64.msixbundle 以及选项 0 和 0 开始对程
                                       序包执行部署 Add 操作。要获取有关诊断应用部署问题的帮助，请参阅 http://go.micros
                                       oft.com/fwlink/?LinkId=235160。
2022/11/29 12:31:01       154          错误 0x800B0109: 应用包或捆绑包中的签名的根证书必须是受信任的证书。
2022/11/29 12:31:01       465          错误 0x800B0109: 从位置 HyPlayer_2.1.35.5340_x64_ARM64.msixbundle 中打开程序包失
                                       败。
2022/11/29 12:31:01       497          错误 0x80070002: 从位置 HyPlayer_2.1.35.5340_x64_ARM64.msixbundle 打开 Msixvc 程
                                       序包失败。请检查是否安装了 Msixvc 支持服务。
2022/11/29 12:31:01       403          错误 0x800B0109: 无法为以下对象获取暂存会话: file:///C:/Users/Administrator/Down
                                       loads/HyPlayer_2.1.35.5340_x64_ARM64.msixbundle。
2022/11/29 12:31:01       404          程序包  的 AppX 部署操作失败，错误为 0x800B0109。此失败的具体错误文本是: 错误 0x
                                       800B0109: 应用包或捆绑包中的签名的根证书必须是受信任的证书。

**Comment by frg2089** [comment]
你应该用这条命令安装
```powershell
Add-AppPackage -Path "PathTo\HyPlayer_2.1.35.5340_x64_ARM64.msixbundle" -AllowUnsigned
```

[Add-AppPackage -AllowUnsigned | Microsoft Learn](https://learn.microsoft.com/powershell/module/appx/add-appxpackage?view=windowsserver2022-ps#-allowunsigned)

**Comment by Norsk-SkogKatt** [comment]
PS C:\Users\Administrator\Downloads> Add-AppPackage -Path ".\HyPlayer_2.1.35.5340_x64_ARM64.msixbundle" -AllowUnsigned
Add-AppPackage : 部署失败，原因是 HRESULT: 0x80073CF3, 包无法进行更新、相关性或冲突验证。
Windows 无法安装程序包 48848aaaaaaccd.HyPlayer_2.1.35.5340_x64__fkcggvf9kbkw0，因为此程序包依赖于一个找不到的框架。请随
要安装的此程序包一起提供由“CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US”发布的框
架“Microsoft.Services.Store.Engagement”(具有中性或 x64 处理器体系结构，最低版本为 10.0.19011.0)。当前已安装的名称为“
Microsoft.Services.Store.Engagement”的框架为: {}
注意: 有关其他信息，请在事件日志中查找 [ActivityId] d78c0dd6-063e-0002-df50-8dd73e06d901，或使用命令行 Get-AppPackageLo
g -ActivityID d78c0dd6-063e-0002-df50-8dd73e06d901
所在位置 行:1 字符: 1
+ Add-AppPackage -Path ".\HyPlayer_2.1.35.5340_x64_ARM64.msixbundle" -A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Admini...RM64.msixbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by frg2089** [comment]
你的系统版本是什么...?
可以发一下winver的截图吗？

**Comment by Raspberry-Monster** [comment]
删除文件夹下全部的Microsoft.Services.Store.Engagement 包 然后执行Install.ps1即可

**Comment by Raspberry-Monster** [comment]
团队内部也有在讨论说后面是否需要上Azure Code Signing以从根本性上解决此问题

**Comment by frg2089** [comment]
这里的包好像没有提供Install.ps1

https://github.com/HyPlayer/HyPlayer/releases/tag/2.1.35.5340

**Comment by Raspberry-Monster** [comment]
https://hyplayer.kengwang.com.cn/#/index

**Comment by frg2089** [comment]
> https://hyplayer.kengwang.com.cn/#/index

提个小建议 这里可以用a标签
不然想右键在新标签页打开都不行的
![image](https://user-images.githubusercontent.com/42184238/205427225-b2f418e4-028a-45d7-a900-7574e9c2af2c.png)

**Comment by kengwang** [comment]
> Reply: https://github.com/HyPlayer/HyPlayer/issues/305#issuecomment-1336090886

用的 Element UI Vue, 他们是这么实现的, 也不好改

**Comment by frg2089** [comment]
> > Reply: [#305 (comment)](https://github.com/HyPlayer/HyPlayer/issues/305#issuecomment-1336090886)
> 
> 用的 Element UI Vue, 他们是这么实现的, 也不好改

那没办法了

**Comment by Norsk-SkogKatt** [comment]
> 你的系统版本是什么...? 可以发一下winver的截图吗？

![winver_7OsdPcaG5L](https://user-images.githubusercontent.com/53899925/206857472-eb7bb489-9bf7-4209-b839-3a9dd3d2d1b2.png)

**Comment by frg2089** [comment]
> > 你的系统版本是什么...? 可以发一下winver的截图吗？
> 
> ![winver_7OsdPcaG5L](https://user-images.githubusercontent.com/53899925/206857472-eb7bb489-9bf7-4209-b839-3a9dd3d2d1b2.png)
> 

服务器系统？装在自己电脑上的嘛？
一般来说不建议这样做 我想开发者也没想到过这软件会在服务器系统上被安装吧...

**Comment by kengwang** [comment]
删除掉 `Dependencies` 文件夹下的所有包含 `Microsoft.Services.Store.Engagement` 的文件

**Comment by Norsk-SkogKatt** [comment]
> 删除掉 文件夹下的所有包含 的文件`Dependencies``Microsoft.Services.Store.Engagement`

没有应用商店

**Comment by Norsk-SkogKatt** [comment]
> > > 你的系统版本是什么...? 可以发一下winver的截图吗？
> > 
> > 
> > ![winver_7OsdPcaG5L](https://user-images.githubusercontent.com/53899925/206857472-eb7bb489-9bf7-4209-b839-3a9dd3d2d1b2.png)
> 
> 服务器系统？装在自己电脑上的嘛？ 一般来说不建议这样做 我想开发者也没想到过这软件会在服务器系统上被安装吧...

电脑性能太差跑10经常爆内存

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/206858570-1633fcf1-8e93-4096-86fe-fe5968d49668.png)

像这样, 在基础包里面

**Comment by Norsk-SkogKatt** [comment]
> Dependencies

我没有这个文件夹:(

**Comment by frg2089** [comment]
> > Dependencies
> 
> 我没有这个文件夹:(

在上面有一个下载链接 去那里下载

**Comment by kengwang** [comment]
```
基本包
|___Dependencies
|___|___arm64
|___|___Win32
|___|___x64
|___|___|___Microsoft.Services.Store.Engagement.x64.10.0.appx   <=== 删掉他
|___TelemetryDependencies
|___Add-AppDevPackage.ps1
|___Install.ps1
|___安装说明.txt
|___HyPlayer********.msixbundle
|___代码证书.cer
```

如果没有基本包, 可以在内测申请后的下载页面下载

**Comment by Norsk-SkogKatt** [comment]
> ![image](https://user-images.githubusercontent.com/30862240/206858570-1633fcf1-8e93-4096-86fe-fe5968d49668.png)
> 
> 像这样, 在基础包里面

![powershell_515QmhPYJn](https://user-images.githubusercontent.com/53899925/206859459-c63249f3-082c-44a4-805e-2f97eea727c5.png)

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/206859508-4e31dec9-5a76-4ded-90b0-cf154a383552.png)
![image](https://user-images.githubusercontent.com/30862240/206859514-1d6c63fe-ab47-435c-af48-3279b8792187.png)
![image](https://user-images.githubusercontent.com/30862240/206859525-2163413b-0cea-4198-926e-ecb6090f3f87.png)

请注意回看我发出的 Comment 并按照步骤进行操作
之后再次按照安装说明进行安装

**Comment by xiaogun123** [comment]
那个Store的删掉了

**Comment by Norsk-SkogKatt** [comment]
> ![image](https://user-images.githubusercontent.com/30862240/206859508-4e31dec9-5a76-4ded-90b0-cf154a383552.png) ![image](https://user-images.githubusercontent.com/30862240/206859514-1d6c63fe-ab47-435c-af48-3279b8792187.png) ![image](https://user-images.githubusercontent.com/30862240/206859525-2163413b-0cea-4198-926e-ecb6090f3f87.png)
> 
> 请注意回看我发出的 Comment 并按照步骤进行操作 之后再次按照安装说明进行安装

安装好了,谢谢

**Comment by kengwang** [comment]
请贴出目前所遇到的报错信息, 在一次 Comment 中提供尽量多的信息以便减少交流成本和负担.

PS. 如何提问建议参考: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by cangSDARM** [comment]
额，没有exe么？
为什么要用弱智的misx，
![image](https://github.com/HyPlayer/HyPlayer/assets/20441896/2e361ab2-4ce0-4094-86f6-78bdd3747263)
![image](https://github.com/HyPlayer/HyPlayer/assets/20441896/9c34bf2f-0700-4d49-93a1-fd2512868c5c)

https://stackoverflow.com/questions/38056317/make-exe-file-out-of-visual-studio-uwp-appx-file

**Comment by WXRIW** [comment]
我想，msix没您弱智

> 额，没有exe么？ 为什么要用弱智的misx， ![image](https://user-images.githubusercontent.com/20441896/240837260-2e361ab2-4ce0-4094-86f6-78bdd3747263.png) ![image](https://user-images.githubusercontent.com/20441896/240837428-9c34bf2f-0700-4d49-93a1-fd2512868c5c.png)
> 
> https://stackoverflow.com/questions/38056317/make-exe-file-out-of-visual-studio-uwp-appx-file

**Comment by Raspberry-Monster** [comment]
1. UWP不支持
2. 你装不上是因为你自己没跟着安装说明走
3. 请跟随“基本包”（README中有链接）中的安装说明进行安装

**Comment by cnbluefire** [comment]
> 额，没有exe么？ 为什么要用弱智的misx， ![image](https://user-images.githubusercontent.com/20441896/240837260-2e361ab2-4ce0-4094-86f6-78bdd3747263.png) ![image](https://user-images.githubusercontent.com/20441896/240837428-9c34bf2f-0700-4d49-93a1-fd2512868c5c.png)
> 
> https://stackoverflow.com/questions/38056317/make-exe-file-out-of-visual-studio-uwp-appx-file

有msix容器不用为什么要用弱智的exe打包？

**Comment by Raspberry-Monster** [comment]
另：此StackOverflow所提供的方案实质上就是让AdvancedInstaller调用PowerShell安装msix，这和现在的方案完全没有区别，只会增加分发时的难度。请问您是否认真阅读过此Post？
