### ISSUE TITLE
[FR] 建议关闭HyPlayer的同时关闭热词

### ISSUE THREAD

**Issue by G-POPLO** [HyPlayer/HyPlayer#314]
**这是什么方面的想法？**
建议关闭HyPlayer的同时关闭热词

**这个想法具体是要实现什么？**
如标题所述

**这个想法实现后有什么帮助？**
更方便，不用手动去关闭热词

**是否有具体的实现思路？**
N/A
**补充信息：**
N/A

**Comment by kengwang** [comment]
这个需要热词方面进行适配，但是之前问过热词开发者不想弄
________________________________
发件人: c-poplo ***@***.***>
发送时间: 2022年12月4日 15:45
收件人: HyPlayer/HyPlayer ***@***.***>
抄送: Subscribed ***@***.***>
主题: [HyPlayer/HyPlayer] [FR] 建议关闭HyPlayer的同时关闭热词 (Issue #314)


这是什么方面的想法？
建议关闭HyPlayer的同时关闭热词

这个想法具体是要实现什么？
如标题所述

这个想法实现后有什么帮助？
更方便，不用手动去关闭热词

是否有具体的实现思路？
N/A
补充信息：
N/A

―
