### ISSUE TITLE
[FR] 建议提升一下高分辨率屏幕的显示情况

### ISSUE THREAD

**Issue by niconihe** [HyPlayer/HyPlayer#315]
**这是什么方面的想法？**
屏幕显示

**这个想法具体是要实现什么？**
就是我是4K，屏幕缩放300%的笔记本，总感觉显示的信息量太少了，一大片的地方的地方只显示很少的内容显得很窄，然后就是音乐的控制栏，也是原版网易云的1.5倍高，显得很粗，顺便一提窗口化模式控制栏也只有几个基础的按钮，中间的空隙也很大感觉完全可以把其他的加上

**这个想法实现后有什么帮助？**
界面更美观，更食用一些？大概。

**是否有具体的实现思路？**
none

**补充信息：**
![QQ截图20221207164208](https://user-images.githubusercontent.com/29039907/206133809-50e80dcc-ca7c-4d4a-9feb-54f287663cd2.png)
![QQ截图20221207165902](https://user-images.githubusercontent.com/29039907/206134450-74994720-53dd-4a53-9b21-f5e37209c55d.png)
![QQ截图20221207170202](https://user-images.githubusercontent.com/29039907/206135414-035c8748-2635-4a89-aba3-ad0ec84e8c7f.png)

**Comment by Raspberry-Monster** [comment]
这应该是高DPI导致的 如果可以的话调低DPI会好很多
