### ISSUE TITLE
[BUG] 搜索不显示结果

### ISSUE THREAD

**Issue by flypigJ** [HyPlayer/HyPlayer#317]
## BUG 反馈

**何处触发：**

搜索（全局搜索，不是歌单内）

**实际行为描述：**应用程序打开后，前几次搜索正常，但后续搜索不显示结果。

搜索不显示结果（结果为空）

**预期的行为：**显示搜索结果

**复现步骤：**

升级到V2.1.35.5362版本后，先搜索几首歌曲，再切换到其它页面（如歌词页），过一会切回搜索页，发现不显示结果

**配置与环境：**

- 音乐链接：
- HyPlayer 版本：V2.1.35.5362
- 系统版本：Windows 11 Pro Insider Preview 25267.1000

**截图（若有）**

![image](https://user-images.githubusercontent.com/68471692/208219262-dc6b98f5-9a74-4479-88e7-bc57b86be6f8.png)
此时未连接代理，音乐均能正常播放

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
收到, 正在排查

**Comment by Raspberry-Monster** [comment]
Fixed in https://github.com/HyPlayer/HyPlayer/commit/bc285503ce1a3c7ffd2a6f0a3d4e921e53226292
