### ISSUE TITLE
动态磁贴小优化

### ISSUE THREAD

**Issue by tjddbc** [HyPlayer/HyPlayer#319]
非常感谢大佬，把磁贴加入，我当时也只是随口一说。非常谢谢大佬。
磁贴希望能让他自己动，换图片这样。
我发现，现在的逻辑是我播放的音乐的封面
可不可以是播放过的封面，隔段时间自己更换这样。
😋😋😋

**Comment by Raspberry-Monster** [comment]
应该不会实现此功能，因为磁贴的目的就是为了指示当前播放的歌曲

**Comment by tjddbc** [comment]
我当成壁纸用的i😋



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月11日(星期三) 晚上8:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HyPlayer/HyPlayer] 动态磁贴小优化 (Issue #319)





 
应该不会实现此功能，因为磁贴的目的就是为了指示当前播放的歌曲
