### ISSUE TITLE
[BUG] 播放失败，切换到下一首 Exception from HRESULT: 0xC00D0035

### ISSUE THREAD

**Issue by sf467** [HyPlayer/HyPlayer#322]
随机出现并且频率较高，有几次一连好几首歌都给我跳过去了
而且歌曲因播放失败跳到下一首之后，点击播放上一首回到这首歌，可以正常播放
已经解决了网络环回

**Comment by kengwang** [comment]
尝试关闭播放缓存功能 (实验室 - 播放缓存)

**Comment by sf467** [comment]
遗憾的是出现这个问题时播放缓存功能就是在关闭状态的😢
只是在打开播放缓存功能后更加严重（几乎听不了歌了）
感谢

**Comment by zhinailuoli** [comment]
我这边也偶尔会出现这个问题,出现没什么规律,而且也没提示错误代码
![image](https://user-images.githubusercontent.com/107562312/222918202-16cbc469-76bf-4cca-ad95-5b200e4e29de.png)

**Comment by kengwang** [comment]
关代理, 关缓存, 降音质, 开环回, 关音量平衡, 关掉使用旧版 SMTC, 实验室功能不要动, 关闭渐入渐出, 实在不行重装试试

**Comment by kengwang** [comment]
实验室的默认配置:
![image](https://user-images.githubusercontent.com/30862240/222918956-5502923a-b23b-4d04-a16a-0ace24699aa7.png)

**Comment by wling-art** [comment]
我也遇到这个问题,但降音质就解决了,但想问问,能不能在不降音质的情况下也能正常啊😥
无损和无损以上的就会出现这种情况了
![image](https://github.com/HyPlayer/HyPlayer/assets/90316914/4b8aeef2-eebd-4a72-a09c-97a704bb995e)
然后接着又有一些弹窗
![image](https://github.com/HyPlayer/HyPlayer/assets/90316914/0dbae8b7-a094-45b4-9ac8-84b7991ee784)
本来下一首播放的他也没放,貌似报错了一两首就才正常

**Comment by Raspberry-Monster** [comment]
比较难，因为是微软的播放核心扛不住了
