### ISSUE TITLE
language

### ISSUE THREAD

**Issue by senolfndk** [HyPlayer/HyPlayer#324]
can you add turkish language in app

**Comment by kengwang** [comment]
Hello bro,
We will add multilingual support in the 3.0 version, the translation will be on Crowdin which is a public translate platform.
We can put your language on it and hope you can help for the correction of the translation.


________________________________

**Comment by senolfndk** [comment]
hello friend thank you

Windows için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: ***@***.***>
Gönderilme: 7 Ocak 2023 Cumartesi 11:48
Kime: ***@***.***>
Bilgi: şenol ***@***.***>; State ***@***.***>
Konu: Re: [HyPlayer/HyPlayer] language (Issue #324)

Hello bro,
We will add multilingual support in the 3.0 version, the translation will be on crowdy.
We can put your language on it and hope you can help for the correction of the translation.


________________________________

**Comment by senolfndk** [comment]
hello friend thank you
