### ISSUE TITLE
[BUG] Win11 UWP任务栏标题在窗口最小化时不会更新当前播放的歌曲信息

### ISSUE THREAD

**Issue by 135ty** [HyPlayer/HyPlayer#328]
## BUG 反馈

**何处触发：**
UWP版App任务栏标题中显示的歌曲信息。

**实际行为描述：**
切换上/下一首歌后，任务栏标题中正在播放歌曲的信息仍然保持不变。

**预期的行为：**
任务栏标题中显示的歌曲信息应随歌曲的切换而变化。

**复现步骤：**
将窗口最小化然后切歌（通过任务栏上的按钮或播放完成后自动切换下一首的方式均能复现）。

**配置与环境：**
* Win10/Win11 最新发行版
- 音乐链接：
- HyPlayer 版本：
- 系统版本：

**截图（若有）**

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
由于 UWP 的问题, 这个暂时无法实现
~~我也不知道为啥 UWP 有这种神奇的问题! 最小化就相当于没有窗口(View)了, 没有窗口就改不了窗口标题, 真6~~

**Comment by kengwang** [comment]
3.0 如果采用了 WinUI 应该就不会有这个问题了.
不过现在 WinUI 还是有些没达到预期, 再等等
