### ISSUE TITLE
无法播放音乐

### ISSUE THREAD

**Issue by 11515-2** [HyPlayer/HyPlayer#330]
**何处触发：**
程序突然无法播放音乐

**实际行为描述：**
程序突然无法播放音乐，smtc和其他方式都无法播放，已解除环回，关闭缓存，

**预期的行为：**
播放音乐

**复现步骤：**
打开应用就无法播放

**配置与环境：**

- 音乐链接：https://music.163.com/#/song?id=1377261977
- HyPlayer 版本：Version 2.1.35.5396
- 系统版本：win11 21H2

**截图（若有）**

**报错信息**

```
没有报错
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
是否调整音质? 其他歌曲是否可以播放? 是否尝试重启 HyPlayer? 是否关闭全局代理? 是否开启了 Unblock 但未降级 HTTPS?

**Comment by 11515-2** [comment]
音质为最低，都无法播放，重启好几次了已降级。它是用着用着突然无法播放的

**Comment by kengwang** [comment]
重新解除环回, 在 cmd 中运行:
```
CheckNetIsolation LoopbackExempt -a -n="48848aaaaaaccd.hyplayer_fkcggvf9kbkw0"
```
并截图执行的命令和返回内容

**Comment by 11515-2** [comment]
！我重新cmd运行了下然后重启系统就OK了，谢谢大佬！
