### ISSUE TITLE
[FR] 建议增加音量均衡功能

### ISSUE THREAD

**Issue by 66622a** [HyPlayer/HyPlayer#332]
**这是什么方面的想法？**
新增功能

**这个想法具体是要实现什么？**
每首歌播放时自动平衡该首歌曲的音量
**这个想法实现后有什么帮助？**
避免不同歌曲之间音量太大被吵到或太小听不见歌曲的情况发生
**是否有具体的实现思路？**
设置一个统一的音量，如果音量太小则增大该首歌曲的音量，反之则减小音量
**补充信息：**
无

**Comment by Raspberry-Monster** [comment]
好想法，请问如何实现此功能？我们应如何定义所有人都能接受的，统一的音量？

**Comment by 66622a** [comment]
由用户定义用户能接受的音量，然后以这个音量作为标准进行音量均衡

> 好想法，请问如何实现此功能？我们应如何定义所有人都能接受的，统一的音量？

**Comment by qiuzilu** [comment]
好想法，但是您可以将风格相同，响度相近的曲子放在同一个歌单内
您的这种情况我也遇到过，大晚上的，歌曲突然从平缓切换到奔放；突然从静谧变为喧阗的感觉真的很难受，有时候耳朵都要炸掉。
但是您所要求的这种功能，效果也许并不那么卓有成效，也许会占用大量性能，更重要的是，这个标准真的很难找，即使用户自定义。
许多歌曲并不是一马平川的，也许前奏缓和而安静，高潮狂放而热烈，高潮过后又是一段平静的轻音乐。
请看一首歌曲的波形图：
![image](https://user-images.githubusercontent.com/64822124/216621574-dae590dc-0fff-4609-9361-fc3e91009cb9.png)
如果，将这首歌降低音量以避免高潮时的太过于吵闹，会变成：
![image](https://user-images.githubusercontent.com/64822124/216624323-57fb66a4-ca5e-4725-84c2-3909acb2669b.png)
实际上听起来呢，前奏的声音更小了，高潮部分像那种便秘拉不出来的感觉，高潮过后那段轻音像被删掉一样
![0FGI_20DGL)Q`BTE7D2YNET](https://user-images.githubusercontent.com/64822124/216624957-e8636048-2992-4db3-aa2d-439175a3b9a0.jpg)

**Comment by kengwang** [comment]
网易云音乐给了返回值的，但是暂时没适配


________________________________

**Comment by Raspberry-Monster** [comment]
Implemented in https://github.com/HyPlayer/HyPlayer/commit/389cd23da1570241f11830b57e05c8ab3b399c4b

**Comment by kengwang** [comment]
@Raspberry-Monster 666, 好快
