### ISSUE TITLE
怎么去掉启动时的弹窗提醒[FR] 

### ISSUE THREAD

**Issue by wblmxxxx** [HyPlayer/HyPlayer#334]
**这是什么方面的想法？**

**这个想法具体是要实现什么？**
去掉弹窗

**这个想法实现后有什么帮助？**
减少点击，舒心

**是否有具体的实现思路？**
可以加个选项

**补充信息：**

**Comment by Raspberry-Monster** [comment]
您是否阅读过用户群的群公告？

**Comment by wblmxxxx** [comment]
不好意思，我没进群

**Comment by zhoumao1** [comment]
有没有办法通过启动参数来自动关闭【重要通知】弹框呢？不好意思没有进群，也没找到群

**Comment by Raspberry-Monster** [comment]
关于界面 谢谢 非启动参数 UWP不支持
