### ISSUE TITLE
[FR] 小窗播放建议

### ISSUE THREAD

**Issue by Akira-TL** [HyPlayer/HyPlayer#341]
### **这是什么方面的想法？**
现有内容的优化

### **这个想法具体是要实现什么？**

- 记住小窗最后打开的**位置**
- 记住小窗的**模糊和清晰状态**
- 记住小窗的**大小**
- 小窗歌词显示可选**展示和隐藏**

### **这个想法实现后有什么帮助？**
小窗优化

### **是否有具体的实现思路？**
None

### **补充信息：**
None

**Comment by weihour** [comment]
要是在小窗里直接有小红心的按钮就好了，直接添加到我喜欢的音乐里面

**Comment by Akira-TL** [comment]
### 平时使用时另外的建议
+ 快捷键切歌(全局和软件内):ctrl + →;ctrl + alt + →;......
+ 在竖直播放页面时设置我喜欢的按钮,右下角的"..."用起来有点麻烦
![GT92YGH}XSRLF9VJ4`AHO3N](https://user-images.githubusercontent.com/34976229/224226929-9dc7c86b-320b-4a90-b8fd-1668766fe101.png)

**Comment by Raspberry-Monster** [comment]
1. 感谢FR 由于UWP限制，我们无法实现全局快捷键
2. 竖直模式右下角的...是平衡了大部分用户的需求后才做出的取舍，否则按钮过多容易导致按钮叠在按钮上的情况。暂无计划对其进行修改

**Comment by Raspberry-Monster** [comment]
3. 其他功能我们会考虑可行性酌情添加

**Comment by Raspberry-Monster** [comment]
> 要是在小窗里直接有小红心的按钮就好了，直接添加到我喜欢的音乐里面

已在最新Canary中实现
