### ISSUE TITLE
[BUG] 日推报错

### ISSUE THREAD

**Issue by ApigeonAPE** [HyPlayer/HyPlayer#348]
![image](https://user-images.githubusercontent.com/61077394/229291770-6a476ddd-25f7-4e6f-a7eb-e9a1a5d88eb1.png)

**何处触发：**

日推

**实际行为描述：**

报错，日推无法打开

![image](https://user-images.githubusercontent.com/61077394/229291797-085b27fa-0cb1-4a85-ad77-c27422ff55b9.png)

**复现步骤：**

切换到日推

**配置与环境：**

- HyPlayer 版本：Version 2.1.35.5429  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：Windows 10 专业版 22H2

**截图（若有）**

![image](https://user-images.githubusercontent.com/61077394/229291881-642eb85d-679f-4c12-9c90-bae9ab858a20.png)

![image](https://user-images.githubusercontent.com/61077394/229291933-a0372b9c-a669-4820-857a-5fda7c338dac.png)

**报错信息**

![image](https://user-images.githubusercontent.com/61077394/229291770-6a476ddd-25f7-4e6f-a7eb-e9a1a5d88eb1.png)

**Comment by kengwang** [comment]
请前往 https://music.163.com/#/user/setting 开启个性化服务

**Comment by ApigeonAPE** [comment]
感谢！

Ps:是否能针对常见的报错整理一份清单方便自行排错？
