### ISSUE TITLE
播放过特定歌曲之后，CPU占用猛增。

### ISSUE THREAD

**Issue by Leo-Aug** [HyPlayer/HyPlayer#35]
## BUG 反馈

**何处触发：** 播放特定歌曲之后

**实际行为描述：** 软件的Hyplayer进程所占用的CPU资源猛增，从百分之几猛增到百分之十几甚至百分之三十多，甚至会造成界面卡死。

**预期的行为：** 在播放歌曲的过程中，进程所占用的CPU资源应大致恒定。

**复现步骤：** 开启应用后，播放特定歌曲。

**配置与环境：** 

- 音乐链接：https://music.163.com/#/song?id=1427775641
- HyPlayer 版本：Microsoft Store 2021年6月6日的最新版本，具体版本号未知
- 系统版本：Windows10 20H2（内部版本19042.985）

**截图（若有）**

未播放任何歌曲时：
![Hyplayer_bug_havingnotplay](https://user-images.githubusercontent.com/57796691/120924998-035d2080-c709-11eb-92bc-d52b281ebd46.png)

未播放指定歌曲时：
![Hyplayer_bug1](https://user-images.githubusercontent.com/57796691/120925043-399aa000-c709-11eb-8348-c359eb1f80f7.png)

播放指定歌曲时：
![Hyplayer_bug_playing](https://user-images.githubusercontent.com/57796691/120925053-46b78f00-c709-11eb-893e-0bc8a56f9ae4.png)

暂停播放指定歌曲后：
![Hyplayer_bug_pause](https://user-images.githubusercontent.com/57796691/120925071-5a62f580-c709-11eb-8bad-a0e333dc622b.png)

从指定歌曲切换到其他歌曲后（此时下方播放条显示的播放中歌曲还是指定歌曲，但实际播放的却不是指定歌曲）：
![Hyplayer_bug_after](https://user-images.githubusercontent.com/57796691/120925086-6949a800-c709-11eb-96c5-f3bac33366da.png)

**补充信息：** 第二次播放指定歌曲时CPU占有量疑似翻倍（从30%涨到近60%）。

**Comment by kengwang** [comment]
感谢反馈,将会在近期排查

**Comment by kengwang** [comment]
据排查,是在歌词转换出出现了问题

**Comment by kengwang** [comment]
问题找到: 误用while语句,更换为if即可

**Comment by Leo-Aug** [comment]
> 问题找到: 误用while语句,更换为if即可

这样啊，那我把issue关掉了，谢谢你的关注。

**Comment by kengwang** [comment]
为了方便问题追踪,将会在 Commit 的时候自动Close
