### ISSUE TITLE
[FR] 搜索联想词切换时保留原有的联想词

### ISSUE THREAD

**Issue by 745404527** [HyPlayer/HyPlayer#350]
一个现有内容的优化

搜索时按动上下键切换联想词后其余的联想词不应该被新的联想所替换
它们应该被保留到下一次新输入字符之后
就像在常用浏览器搜索框内搜索一样

这可以帮助改进使用体验，因为这符合大部分人的使用习惯

如上

**Comment by Raspberry-Monster** [comment]
下个版本加入 感谢FR

**Comment by Raspberry-Monster** [comment]
Implemented in https://github.com/HyPlayer/HyPlayer/commit/b809ca4317bbe3a2791b7fe3e3ae46cf38f70cd9
