### ISSUE TITLE
[FR] 使歌词页歌曲封面大小可调

### ISSUE THREAD

**Issue by flypigJ** [HyPlayer/HyPlayer#351]
**这是什么方面的想法？**

**这个想法具体是要实现什么？**
使歌词页歌曲封面大小可调
原界面歌曲封面过大，影响使用体验
![image](https://user-images.githubusercontent.com/68471692/230715612-1cc2c283-0b4e-4b2d-82bf-54ef155b08fe.png)

**补充信息：**

**Comment by Raspberry-Monster** [comment]
无法实现
