### ISSUE TITLE
[BUG] 下载时的序号错误

### ISSUE THREAD

**Issue by wling-art** [HyPlayer/HyPlayer#357]
## BUG 反馈

**何处触发：**
点击下载后
**实际行为描述：**

我将储存的下载文件命名设置为`{$INDEX}­_{$SONGNAME}`，然后在我喜欢的音乐直接点击了 下载 全部

**预期的行为：**

本来应该会是按着歌单进行的序号排列，但是 如图 出现了序号 **重复和错乱** 的问题

**复现步骤：**

将文件命名设置为`{$INDEX}­_{$SONGNAME}`，在我喜欢的音乐直接点击 下载 全部

**配置与环境：**

- 音乐链接：无
- HyPlayer 版本：Version 2.1.35.5438
- 系统版本：
版本	Windows 11 专业版 Insider Preview
版本	22H2
操作系统版本	25346.1001
体验	Windows Feature Experience Pack 1000.25346.1001.0

**截图（若有）**
![uTools_1682396218892](https://user-images.githubusercontent.com/90316914/234274352-4f3f823d-1dbe-47ba-a142-6ee69d9b8f83.png) 

**报错信息**
```
无
```

**补充信息：**

**修复思路：**

**Comment by Raspberry-Monster** [comment]
Fixed
