### ISSUE TITLE
无法跳转到歌曲对应的专辑

### ISSUE THREAD

**Issue by duoduoffff** [HyPlayer/HyPlayer#36]
## BUG 反馈

**何处触发：**

无法通过任何交互方式进入歌曲对应的专辑，也无法以任何交互方式进入歌手的全部专辑或歌单列表。

**实际行为描述：**

右击歌曲项，软件毫无反应；点击歌曲的专辑封面，毫无反应；右击或点击歌手的位置，会弹出歌手选择菜单；尝试各种点击专辑名字的位置，毫无反应。歌手页只能显示歌手的前十首歌，没法显示专辑或者歌单。

**预期的行为：**

应该有一个方法显示歌曲所在的专辑的，这个基本功能还是应该有的……

**复现步骤：**

按“实际行为描述”操作即可复现

**配置与环境：**

- 音乐链接：（如果有，请提供一个触发此问题的 音乐）
- HyPlayer 版本：（Release 标注的版本号，Commit 版则写 Commit 编号）
- 系统版本：（正在使用的操作系统, cmd中输入`winver` 即可查看详细信息）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

这个应该算 enhancement，而不是 bug，你们可能还没来得及做……

**修复思路：**

**Comment by kengwang** [comment]
4941dc4270c1e66cf9c563082b9918a441d3e05a
此 Commit 中已经写了该功能,并且在现行Commit中已经支持搜索专辑

**Comment by kengwang** [comment]
Microsoft Store 因为内部协调原因导致没有更新,今天早上才发布了一个提交, 也只是到了 2da1eba457573bc0630d543e8a6ea74ed688733a
专辑搜索要等下次提交,但是专辑的入口可以通过点击歌曲的专辑名进入

**Comment by kengwang** [comment]
因为此为已经制作的功能, Closed
若需要进一步交流,可以Reopen Issue或者加入README中的用户交流群
