### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 09277632** [HyPlayer/HyPlayer#361]
## BUG 反馈

**何处触发：歌单播放

**实际行为描述：播放缓存

**预期的行为：等待约半秒后开始跳歌

**复现步骤：打开播放缓存后随机点歌

**配置与环境：CPU ：intel(R) Core(TM) i5-10210U CPU @ 1.60GHz, 2112 MHz
                      操作系统名称	Microsoft Windows 11 专业版
                      版本	10.0.22621 版本 22621
                      基于虚拟化的安全性	正在运行

- 音乐链接：https://music.163.com/#/song?id=1321015332
- HyPlayer 版本：Version 2.1.36.5463  
- 系统版本：Microsoft Windows 11 专业版 版本 22621

**报错信息**

请在此处填写报错框中的相关信息
```
播放失败切到下一曲
歌曲Pont des souvenirs
Exception from HRESULT: 0×8020001B
**补充信息：**
歌曲以极高音质播放

**修复思路：**

**Comment by kengwang** [comment]
请关闭播放缓存, 播放缓存有很多问题, 目前在实验室选项里面, 建议不要开启
