### ISSUE TITLE
[FR] 紧凑的界面

### ISSUE THREAD

**Issue by kurisucat** [HyPlayer/HyPlayer#363]
**这是什么方面的想法？**
UI 界面

**这个想法具体是要实现什么？**
紧凑的界面，例如更矮的歌单列表。

**这个想法实现后有什么帮助？**
来允许使用鼠标的用户快速选择选项。

**是否有具体的实现思路？**
否。

**补充信息：**
现在的列表仅能显示四个半的歌曲，很多空间也被 Play bar 占据了。
![Too large!](https://user-images.githubusercontent.com/64016189/235392621-7aa1ee48-93ac-4d86-8c3d-7157ffbed0ab.png)
我认为**歌单部分**紧凑的界面可以允许隐藏歌单歌曲的序号以及封面。

Play bar 可以缩小一半。如图所示。
![image](https://user-images.githubusercontent.com/64016189/235393147-9c883a53-56b0-4910-863e-70542924318a.png)

**Comment by kurisucat** [comment]
顺带一提，Play bar 专辑上的展开播放视图和 Play bar 的展开按钮功能似乎是一样的，这是特性吗？

**Comment by kengwang** [comment]
> Re: https://github.com/HyPlayer/HyPlayer/issues/363#issuecomment-1529272442

本来是只有右边的按钮的, 后来有人说不习惯, 然后就把专辑封面也加上了

**Comment by Raspberry-Monster** [comment]
视图已经在新版本中优化
