### ISSUE TITLE
[FR] 增加滚轮调节音量

### ISSUE THREAD

**Issue by wling-art** [HyPlayer/HyPlayer#370]
**这是什么方面的想法？**

 用户体验

**这个想法具体是要实现什么？**
通过鼠标滚轮对着音量图标可以进行音量上下调节
![uTools_1684035195350](https://github.com/HyPlayer/HyPlayer/assets/90316914/2989b531-0906-431f-9e9c-1457ca0f7d60)
**这个想法实现后有什么帮助？**
增加鼠标用户的体验

**是否有具体的实现思路？**
无

**补充信息：**
无

**Comment by kengwang** [comment]
估计做成设置项, 不然可能误触发

**Comment by Raspberry-Monster** [comment]
不会实现此功能，因为可能会导致不必要的触发以及在此情况下没有可用的当前音量指示方案
