### ISSUE TITLE
[BUG] 听歌打卡功能似乎失效了

### ISSUE THREAD

**Issue by 66622a** [HyPlayer/HyPlayer#373]
## BUG 反馈

**何处触发：**
播放音乐时触发

**实际行为描述：**
官方版本的网易云音乐没有看到听歌记录，且听歌排行的听歌次数也没有增加

**预期的行为：**

听歌次数有增加，也有听歌记录

**复现步骤：**
播放音乐

**配置与环境：**
- 音乐链接：任意音乐
- HyPlayer 版本：Version 2.1.36.5502
- 系统版本：Windows 11 22624.1755

**截图（若有）**

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**
可能是网易云的api失效了，或是不支持第三方播放器打卡

**Comment by Raspberry-Monster** [comment]
![Screenshot_2023-05-21-08-48-57-967_com netease cloudmusic](https://github.com/HyPlayer/HyPlayer/assets/59819050/57a7a500-c350-4fd6-b26b-6e9b5260a7a1)
正常 网易云官方客户端的记录是本地的记录，这个问题早就修复了
