### ISSUE TITLE
[BUG] 在亚克力背景模式下应用失去焦点时界面会变为不透明的黑色

### ISSUE THREAD

**Issue by BLACKCHARGE** [HyPlayer/HyPlayer#382]
## BUG 反馈

应用失去焦点时

UI界面

无

**复现步骤：**

应用背景设置为亚克力，点击系统桌面使得应用窗口失去焦点

**配置与环境：**
win10 22H2 19045
- 音乐链接：
- HyPlayer 版本：latest
- 系统版本：
win10 22H2 19045
**截图（若有）**

https://github.com/HyPlayer/HyPlayer/assets/57131319/d8fd0436-1d71-4b76-a31f-7466c527ff41

不知道这个行为是不是正常的，能不能修复，我注意到一些别的基于winui3的应用亚克力界面是没有这个问题的

**Comment by Raspberry-Monster** [comment]
这是亚克力笔刷的特性：为了节省性能，系统会在软件未聚焦时显示为背景色
这是系统笔刷的特性，我们这边是无法改变的
