### ISSUE TITLE
[BUG] 无法播放完毕且不自动切歌

### ISSUE THREAD

**Issue by Akira-TL** [HyPlayer/HyPlayer#383]
## BUG 反馈

**何处触发：**正常播放

**实际行为描述：** 无法播放完毕且不自动切歌

**预期的行为：**完整播放后切歌

**复现步骤：**播放这首歌到结尾，会出现一卡一顿的效果，此时有播放时间大于时间轴时间，听起来就像不断按播放暂停

**配置与环境：**

- 音乐链接：https://music.163.com/#/song?id=31209777
- HyPlayer 版本：Version 2.1.36.5557  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：
Windows 11 专业版
版本	22H2
安装日期	‎2022/‎12/‎28
操作系统版本	22621.1778
体验	Windows Feature Experience Pack 1000.22642.1000.0

**截图（若有）**

这里注意播放轴两边时间差异
![image](https://github.com/HyPlayer/HyPlayer/assets/34976229/647777ea-e92e-45b8-b572-e29b46762b4d)

**报错信息**

```
请在此处填写报错框中的相关信息：无报错
```

**补充信息：**
几个版本都有这个问题

**修复思路：**

**Comment by Raspberry-Monster** [comment]
![image](https://github.com/HyPlayer/HyPlayer/assets/59819050/f8d1c388-bf76-47e0-8727-713732a22f69)
播放文件问题（Miku粉震怒）
我看看有没有办法修复

**Comment by Raspberry-Monster** [comment]
![image](https://github.com/HyPlayer/HyPlayer/assets/59819050/2308da77-5cbe-4bb4-99e7-414bfdf7df73)
Fixed
