### ISSUE TITLE
[FR] 有没有办法让云盘音乐界面的歌曲全部显示出来，而不是拉到200项以后，还需要点击加载更多

### ISSUE THREAD

**Issue by FeiLZX3Km** [HyPlayer/HyPlayer#385]
**这是什么方面的想法？**
让页面歌曲加载更多。

**这个想法具体是要实现什么？**
让云盘音乐界面的歌曲默认全部显示出来。如，云盘歌曲有4000项，那就让4000项全部显示出来。

**这个想法实现后有什么帮助？**
可以定位云盘正在播放的、未在当面页面显示的200项以外的歌曲。

**是否有具体的实现思路？**
不知。

**补充信息：**
把云盘页面几千首歌曲全部点击显示出来，点击正在播放的歌曲评论区再返回以后，云盘歌曲页面歌曲项又只显示200项。可以说得上是“辛辛苦苦一整年，一夜回到解放前”。希望能够把这个小瑕疵修改一下。

**Comment by Raspberry-Monster** [comment]
无法实现
![KF FS`555D1R_)M%6SXXR6U](https://github.com/HyPlayer/HyPlayer/assets/59819050/f818a3c6-8019-48cd-b65f-1a64b0eb7c6a)
网易云在云盘项目中增加了限制，限制返回的歌曲数目
![UI5~T62$DBP{MT}UE3M4O5H](https://github.com/HyPlayer/HyPlayer/assets/59819050/4e0f3045-5881-4b7b-98a0-fcfd07d817c2)
歌单无此限制所以可以一次性加载

**Comment by kengwang** [comment]
Please refer to #393
