### ISSUE TITLE
[BUG] Version 2.1.36.5567  (Package ID: 48848aaaaaaccd.HyPlayer) 更新后使用私人FM出现如图播放器核心错误

### ISSUE THREAD

**Issue by SagitPixel** [HyPlayer/HyPlayer#388]
## BUG 反馈

**何处触发：使用私人FM进行手动下一曲**

**实际行为描述：下一曲失败播放器核心错误0xC00D36BB**

**预期的行为：正常下一曲**

**复现步骤：使用私人FM进行手动下一曲**

**配置与环境：**

- 音乐链接：（私人FM随机推送，在我的电脑上稳定触发）
- HyPlayer 版本：Version 2.1.36.5567  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：Windows11专业工作站版 22H2 22621.1702

**截图（若有）**

![屏幕截图 2023-06-04 122357](https://github.com/HyPlayer/HyPlayer/assets/59535808/2bf6fbb9-3c08-40a0-846c-072442372a8d)

**报错信息**
播放核心：System.Exception:请求的操作中出现错误。（Exception from HRESULT;0XC00D36BB)
```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by Raspberry-Monster** [comment]
Fixed in https://github.com/HyPlayer/HyPlayer/commit/26b7f48829b0c461cbe552b7c9126db3670e6b37
