### ISSUE TITLE
闪退[BUG] 

### ISSUE THREAD

**Issue by flypigJ** [HyPlayer/HyPlayer#392]
## BUG 反馈

**何处触发：**
当播放任意在线音乐

播放音乐

**实际行为描述：**
**当播放任意在线音乐，hyplayer会在5秒内闪退**（具体请看视频）

**复现步骤：**

登录账号后播放任意在线音乐

**配置与环境：**
![image](https://github.com/HyPlayer/HyPlayer/assets/68471692/0818b9b0-d51b-4817-85be-e512ebab190c)
![image](https://github.com/HyPlayer/HyPlayer/assets/68471692/d1594fd2-23f0-4ba2-8901-f581c40ce9c6)

- 音乐链接：所有
- HyPlayer 版本：
- 系统版本：

**截图（若有）**

https://github.com/HyPlayer/HyPlayer/assets/68471692/1956076b-425e-4928-bc0d-313509697285

**报错信息**

请在此处填写报错框中的相关信息
无报错，直接闪退

**补充信息：**
no

**修复思路：**

**Comment by kengwang** [comment]
已经收到, 正在排查

**Comment by kengwang** [comment]
此问题仅在 Windows 预览频道 Canary 上出现, 造成原因未知, 估计是微软的锅

**Comment by Big-Cake-jpg** [comment]
Canary 版本 25381.1 (zn_release)，问题复现。
事件查看器中记录的对应事件如下：
```
错误应用程序名称: HyPlayer.exe，版本: 1.0.0.0，时间戳: 0x6489e8d6
错误模块名称: shcore.dll，版本: 10.0.25381.1，时间戳: 0xce805dd9
异常代码: 0xc0000005
错误偏移量: 0x00000000000379b6
错误进程 ID: 0x0x3DE4
错误应用程序启动时间: 0x0x1D9A016B613971A
错误应用程序路径: C:\Program Files\WindowsApps\48848aaaaaaccd.HyPlayer_2.1.36.5613_x64__fkcggvf9kbkw0\HyPlayer.exe
错误模块路径: C:\WINDOWS\System32\shcore.dll
报告 ID: 427024d9-d57a-474a-a70f-9b36cfdf26fc
错误程序包全名: 48848aaaaaaccd.HyPlayer_2.1.36.5613_x64__fkcggvf9kbkw0
错误程序包相对应用程序 ID: App
```
```
错误应用程序名称: HyPlayer.exe，版本: 1.0.0.0，时间戳: 0x6489e8d6
错误模块名称: twinapi.appcore.dll，版本: 10.0.25381.1，时间戳: 0x9e4f39dd
异常代码: 0xc0000409
错误偏移量: 0x000000000007adcf
错误进程 ID: 0x0x4C50
错误应用程序启动时间: 0x0x1D9A016AD1B1C5C
错误应用程序路径: C:\Program Files\WindowsApps\48848aaaaaaccd.HyPlayer_2.1.36.5613_x64__fkcggvf9kbkw0\HyPlayer.exe
错误模块路径: C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
报告 ID: c6b5177e-e847-4e9a-ad2c-4e7915a86ca7
错误程序包全名: 48848aaaaaaccd.HyPlayer_2.1.36.5613_x64__fkcggvf9kbkw0
错误程序包相对应用程序 ID: App
```
```
错误应用程序名称: HyPlayer.exe，版本: 1.0.0.0，时间戳: 0x648078f1
错误模块名称: twinapi.appcore.dll，版本: 10.0.25381.1，时间戳: 0x9e4f39dd
异常代码: 0xc0000409
错误偏移量: 0x000000000007adcf
错误进程 ID: 0x0x4C94
错误应用程序启动时间: 0x0x1D9A016208ACA2F
错误应用程序路径: C:\Program Files\WindowsApps\48848aaaaaaccd.HyPlayer_2.1.36.5584_x64__fkcggvf9kbkw0\HyPlayer.exe
错误模块路径: C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
报告 ID: 2d2bbd01-1332-4fbc-adca-1b5d1ab8d0ea
错误程序包全名: 48848aaaaaaccd.HyPlayer_2.1.36.5584_x64__fkcggvf9kbkw0
错误程序包相对应用程序 ID: App
```
搜索后，可以找到相关的一个 Issue：https://github.com/microsoft/microsoft-ui-xaml/issues/2106 ，但似乎没有什么有效信息。
![image](https://github.com/HyPlayer/HyPlayer/assets/76810494/3da49cc0-5de1-40e1-a9cf-fecf8847bb0a)

**Comment by Raspberry-Monster** [comment]
目前正在重新生成应用，请在等会发布的新版本中测试是否会崩溃

**Comment by flypigJ** [comment]
> Canary 版本 25381.1 (zn_release)，问题复现。 事件查看器中记录的对应事件如下：
> 
> ```
> 错误应用程序名称: HyPlayer.exe，版本: 1.0.0.0，时间戳: 0x6489e8d6
> 错误模块名称: shcore.dll，版本: 10.0.25381.1，时间戳: 0xce805dd9
> 异常代码: 0xc0000005
> 错误偏移量: 0x00000000000379b6
> 错误进程 ID: 0x0x3DE4
> 错误应用程序启动时间: 0x0x1D9A016B613971A
> 错误应用程序路径: C:\Program Files\WindowsApps\48848aaaaaaccd.HyPlayer_2.1.36.5613_x64__fkcggvf9kbkw0\HyPlayer.exe
> 错误模块路径: C:\WINDOWS\System32\shcore.dll
> 报告 ID: 427024d9-d57a-474a-a70f-9b36cfdf26fc
> 错误程序包全名: 48848aaaaaaccd.HyPlayer_2.1.36.5613_x64__fkcggvf9kbkw0
> 错误程序包相对应用程序 ID: App
> ```
> 
> ```
> 错误应用程序名称: HyPlayer.exe，版本: 1.0.0.0，时间戳: 0x6489e8d6
> 错误模块名称: twinapi.appcore.dll，版本: 10.0.25381.1，时间戳: 0x9e4f39dd
> 异常代码: 0xc0000409
> 错误偏移量: 0x000000000007adcf
> 错误进程 ID: 0x0x4C50
> 错误应用程序启动时间: 0x0x1D9A016AD1B1C5C
> 错误应用程序路径: C:\Program Files\WindowsApps\48848aaaaaaccd.HyPlayer_2.1.36.5613_x64__fkcggvf9kbkw0\HyPlayer.exe
> 错误模块路径: C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
> 报告 ID: c6b5177e-e847-4e9a-ad2c-4e7915a86ca7
> 错误程序包全名: 48848aaaaaaccd.HyPlayer_2.1.36.5613_x64__fkcggvf9kbkw0
> 错误程序包相对应用程序 ID: App
> ```
> 
> ```
> 错误应用程序名称: HyPlayer.exe，版本: 1.0.0.0，时间戳: 0x648078f1
> 错误模块名称: twinapi.appcore.dll，版本: 10.0.25381.1，时间戳: 0x9e4f39dd
> 异常代码: 0xc0000409
> 错误偏移量: 0x000000000007adcf
> 错误进程 ID: 0x0x4C94
> 错误应用程序启动时间: 0x0x1D9A016208ACA2F
> 错误应用程序路径: C:\Program Files\WindowsApps\48848aaaaaaccd.HyPlayer_2.1.36.5584_x64__fkcggvf9kbkw0\HyPlayer.exe
> 错误模块路径: C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
> 报告 ID: 2d2bbd01-1332-4fbc-adca-1b5d1ab8d0ea
> 错误程序包全名: 48848aaaaaaccd.HyPlayer_2.1.36.5584_x64__fkcggvf9kbkw0
> 错误程序包相对应用程序 ID: App
> ```
> 
> 搜索后，可以找到相关的一个 Issue：[microsoft/microsoft-ui-xaml#2106](https://github.com/microsoft/microsoft-ui-xaml/issues/2106) ，但似乎没有什么有效信息。 ![image](https://user-images.githubusercontent.com/76810494/246330000-3da49cc0-5de1-40e1-a9cf-fecf8847bb0a.png)

我也在这个canary版本，目前最新版hyplayer正常工作

**Comment by frg2089** [comment]
遇到了同样的问题 音乐播着播着就崩了 不清楚有没有别人遇到这个问题

版本号：Version 2.1.38.6000  (Package ID: 48848aaaaaaccd.HyPlayer)
Windows 事件：
```plaintext
出错应用程序名称： HyPlayer.exe，版本： 1.0.0.0，时间戳： 0x67edb907
出错模块名称： shcore.dll， 版本： 10.0.26100.3775，时间戳： 0xdb97f74d
异常代码： 0xc0000005
错误偏移： 0x000000000002c2c6
出错进程 ID： 0xACC4
出错应用程序开始时间： 0x1DBAC5AC3E5F794
Faulting 应用程序路径： C:\Program Files\WindowsApps\48848aaaaaaccd.HyPlayer_2.1.38.6000_x64__jdagbttk64fq4\HyPlayer.exe
Faulting 模块路径： C:\WINDOWS\System32\shcore.dll
Report ID： e27eec45-6282-4ba3-9508-60e2eb8ac6f9
Faulting 包全名： 48848aaaaaaccd.HyPlayer_2.1.38.6000_x64__jdagbttk64fq4
Faulting 程序包相对应用程序 ID： App 个
```
