### ISSUE TITLE
[FR] 音乐云盘一次性加载完全部列表&支持搜索

### ISSUE THREAD

**Issue by HHaoWang** [HyPlayer/HyPlayer#393]
**这是什么方面的想法？**

现有内容的优化

**这个想法具体是要实现什么？**

现在打开音乐云盘时，默认只加载第一页，像我这样云盘存了几百首歌的，一页根本加载不完，播放的时候只会播放第一页的列表，这个实际上跟直观的感受是不一样的，直观的感受应该是我播放云盘里的所有歌，但事实并非如此。因此希望加载云盘歌曲列表时能够一次性加载完全部的歌曲。

另外，歌太多以后非常依赖搜索功能搜歌，音乐云盘没有搜歌功能确实不太方便，希望能加一个。

**这个想法实现后有什么帮助？**

优化音乐云盘播放体验。

**是否有具体的实现思路？**

加载音乐云盘歌曲列表时，一直请求分页直到最后一页，搜索时直接在列表进行本地搜索

**Comment by kengwang** [comment]
将会在下个版本尝试实现.

Linked Issue: #385
Reopen: #385

**Comment by HHaoWang** [comment]
怎么才能参与贡献啊 <del>虽然我下了代码以后设计器都不工作</del>

**Comment by kengwang** [comment]
可以不用设计器, 直接手撸 XAML

**Comment by HHaoWang** [comment]
> 可以不用设计器, 直接手撸 XAML

我比较菜。。。还得学一学呢

**Comment by kengwang** [comment]
![image](https://github.com/HyPlayer/HyPlayer/assets/30862240/ea88c48b-406a-4851-9921-5e2ffaafe6f0)

目前准备实现, 但是会遇到风控

**Comment by HHaoWang** [comment]
加一点延时也会出现风控吗，我觉得全部加载过程持续三五秒应该也是可以接受的

**Comment by kengwang** [comment]
目前是每 2 秒一次下一页请求, 可能需要改到 4 秒
