### ISSUE TITLE
[BUG] 出大事了，疑似网易云封锁了第三方接口！

### ISSUE THREAD

**Issue by SteveWorkshop** [HyPlayer/HyPlayer#401]
两个第三方软件全寄了，扫码登录后无反应，疑似网易云那边风控了

**Comment by SteveWorkshop** [comment]
更新：现在扫描刷出来的二维码会被提示账号风控！

**Comment by kengwang** [comment]
你的账号的问题, 我的账号目前暂未出现这种情况
可以尝试使用第三方登录, 第三方登录走的不是 API, 而是模拟的网易云音乐客户端行为

**Comment by SteveWorkshop** [comment]
我也发现了,可能是代理软件问题导致风控

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SteveWorkshop** [comment]
账号被风控是不是无解了只能换号了？我有点不舍得

**Comment by SteveWorkshop** [comment]
> 你的账号的问题, 我的账号目前暂未出现这种情况
> 可以尝试使用第三方登录, 第三方登录走的不是 API, 而是模拟的网易云音乐客户端行为

好几个接口都这样而且好像不止我一个人，是不是像TX那样，老账号风险系数小一些？

**Comment by kengwang** [comment]
请下载最新版使用第三方登录, 第三方登录的逻辑和网易云音乐官方客户端一致,不会出现任何问题!

**Comment by SteveWorkshop** [comment]
第三方登录那我原来号还是不能用啊，我舍不得这个号（不然我早注册新号了）。
现在网易云搞了个类似于Q盾的网易盾

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年7月2日 19:01
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [HyPlayer/HyPlayer] [BUG] 出大事了，疑似网易云封锁了第三方接口！ (Issue #401)


请下载最新版使用第三方登录, 第三方登录的逻辑和网易云音乐官方客户端一致,不会出现任何问题!

―
