### ISSUE TITLE
[BUG] 进入任意歌手页报错

### ISSUE THREAD

**Issue by gongfuture** [HyPlayer/HyPlayer#402]
## BUG 反馈

**何处触发：**

点击任意一个歌手名字，进入其主页时报错

**实际行为描述：**

![image](https://github.com/HyPlayer/HyPlayer/assets/60888755/0f970c9e-6735-44ca-a2b3-4724b968755a)

**预期的行为：**

**复现步骤：**

稳定复现

**配置与环境：**

- 音乐链接：任意
- HyPlayer 版本：Version 2.1.36.5629  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：Windows 10 专业版 22H2 19045.3086 Windows Feature Experience Pack 1000.19041.1000.0

**截图（若有）**

![image](https://github.com/HyPlayer/HyPlayer/assets/60888755/3067515a-de68-410a-ae1b-ac72cf9a2015)

**报错信息**

```
Object reference not set to an instance of an object.
Exception of type 'System.Exception' was thrown.
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
![image](https://github.com/HyPlayer/HyPlayer/assets/30862240/455e2f8e-b727-445f-b58a-736e1fe7fa22)

我这边正常

**Comment by gongfuture** [comment]
那看来是我这里的问题，我明天重装一下再试试发自我的荣耀手机

**Comment by gongfuture** [comment]
重新安装解决

**Comment by hhhanabi** [comment]
。。我也遇到了同样的问题，但是重装并没有解决，即便是如今的最新版本

**Comment by gongfuture** [comment]
> 。。我也遇到了同样的问题，但是重装并没有解决，即便是如今的最新版本

不覆盖安装，完全卸载安装也有这个问题吗

**Comment by hhhanabi** [comment]
我之前还是Microsoft store下载的，卸载了然后从github下载的&nbsp;


gx
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月9日(星期四) 中午1:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HyPlayer/HyPlayer] [BUG] 进入任意歌手页报错 (Issue #402)





  
。。我也遇到了同样的问题，但是重装并没有解决，即便是如今的最新版本
  
不覆盖安装，完全卸载安装也有这个问题吗

**Comment by kengwang** [comment]
此问题仍然需要追踪, 因为我这边也遇到了

**Comment by gongfuture** [comment]
同样再次出现，再次重装后不再复现

**Comment by caycy01** [comment]
有些歌曲的歌手在网易云音乐没有账号就会触发
![image](https://github.com/HyPlayer/HyPlayer/assets/98204496/8d603a9e-2e66-44b3-8ca9-50133f827771)
![image](https://github.com/HyPlayer/HyPlayer/assets/98204496/ae309231-725e-4e6e-a53a-b79266f841dd)
![image](https://github.com/HyPlayer/HyPlayer/assets/98204496/9bcaf88f-9e0d-4a7d-86be-2fada00413b5)

**Comment by kengwang** [comment]
![image](https://github.com/HyPlayer/HyPlayer/assets/30862240/bbdca544-6db2-404d-baea-449d50320c3d)
现在会给提示了
