### ISSUE TITLE
[FR] 32位x86的release

### ISSUE THREAD

**Issue by mcLYX** [HyPlayer/HyPlayer#426]
**这是什么方面的想法？**
程序兼容性

**这个想法具体是要实现什么？**
使HyPlayer运行在老旧的32位Win10设备上。

**这个想法实现后有什么帮助？**
可以让二十年前的老电脑装上最新版Win10后继续发光发热（物理
好吧我的平板是纯32位EFI的Win10寨板，想在平板上听歌（）

**是否有具体的实现思路？**
编译一份32位x86的msix安装包，并添加到release中。

**补充信息：**
不是吧不是吧，3202年了，居然还有人在用32位的电脑
——好吧还真有（）

本来在巨硬商店是可以下载使用的，然后wy不做人给下了。。
所以加个32位没问题吧（恳求

**Comment by kengwang** [comment]
可以发一个 32 的版

**Comment by kengwang** [comment]
请前往 Telegram 频道查看 x86 的安装包
