### ISSUE TITLE
[BUG] 证书过期

### ISSUE THREAD

**Issue by ChenPeeer** [HyPlayer/HyPlayer#433]
## BUG 反馈

**何处触发：**安装

**实际行为描述：**
powershell内容如下：
找到证书: E:\基本包\代码证书.cer
错误: 开发人员证书“E:\基本包\代码证书.cer”已到期。一个可能的原因是系统时钟未设置为正确的日期和时间。如果系统设置正确，请与应用程序所有者联系以使用有效的证书重新创建包或捆绑。
按 Enter 键继续...:

**预期的行为：**

**复现步骤：**

**配置与环境：**

- 音乐链接：
- HyPlayer 版本：
- 系统版本：win10

[**截图（若有）**]

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
问题已知, 正在处理

**Comment by kengwang** [comment]
Fixed in 652f80bf04f964295a812723dd68bafd309f63e9

请等待今晚发布更新
