### ISSUE TITLE
[BUG] 列表抖动

### ISSUE THREAD

**Issue by ChenPeeer** [HyPlayer/HyPlayer#435]
## BUG 反馈

**何处触发：**
在设置->显示设置中，滚轮向下滚动，当滚到最下面时，过度滚动，即使松开滚轮，整个列表也会有若干秒的抖动

**实际行为描述：**

**预期的行为：**

**复现步骤：**

**配置与环境：**

- 音乐链接：
- HyPlayer 版本：2.1.36.5732
- 系统版本：win10

**截图（若有）**
视频：

https://github.com/HyPlayer/HyPlayer/assets/30888522/066ddeba-d224-471b-891f-5941651bec03

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
此问题正在追踪中


________________________________
From: kksskkoopp ***@***.***>
Sent: Saturday, July 22, 2023 8:10:04 AM
To: HyPlayer/HyPlayer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HyPlayer/HyPlayer] [BUG] 列表抖动 (Issue #435)


BUG 反馈

何处触发：
在设置->显示设置中，滚轮向下滚动，当滚到最下面时，过度滚动，即使松开滚轮，整个列表也会有若干秒的抖动

实际行为描述：

预期的行为：

复现步骤：

配置与环境：

  *   音乐链接：
  *   HyPlayer 版本：2.1.36.5732
  *   系统版本：win10

截图（若有）
视频：

https://github.com/HyPlayer/HyPlayer/assets/30888522/066ddeba-d224-471b-891f-5941651bec03

报错信息

请在此处填写报错框中的相关信息


补充信息：

修复思路：

―

**Comment by kengwang** [comment]
Fixed in 9284662daa7880feb9cc1b8f159913a2e29771f8
