### ISSUE TITLE
[BUG] 部分图标丢失，显示错误

### ISSUE THREAD

**Issue by s-yh-china** [HyPlayer/HyPlayer#436]
## BUG 反馈

**何处触发：** 任意界面

**实际行为描述：** 部分图标丢失，显示错误

**预期的行为：** 影响了视觉效果

**复现步骤：** 正常安装后出现此问题

**配置与环境：**

- 音乐链接：None
- HyPlayer 版本：Version 2.1.36.5732  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：Windows10 1909 (OS 内部版本 18363.778)

**截图（若有）**

![image](https://github.com/HyPlayer/HyPlayer/assets/58360096/49d0f0ec-1d9d-42bc-a725-d589718c6bb7)

**报错信息**

```
None
```

**补充信息：**

**修复思路：** 系统版本过低导致的图标库丢失?

**Comment by kengwang** [comment]
https://aka.ms/SegoeFonts

下载并安装这个字体

**Comment by s-yh-china** [comment]
> https://aka.ms/SegoeFonts
> 
> 下载并安装这个字体

安装之后出错的图标更多了(?
![image](https://github.com/HyPlayer/HyPlayer/assets/58360096/3d716242-836b-4684-98f0-e139b2192341)

**Comment by s-yh-china** [comment]
已确认需要高版本的Segoe MDL2 Assets
微软提供的下载字体包里是1.60i版本
从高版本windows中提取出的1.79版本可正常显示所有图标
[segmdl2.zip](https://github.com/HyPlayer/HyPlayer/files/12136547/segmdl2.zip)
打了个包发出来给以后可能有此问题的人使用

**Comment by kengwang** [comment]
感谢!
