### ISSUE TITLE
[BUG] 信息加载缺失

### ISSUE THREAD

**Issue by ChenPeeer** [HyPlayer/HyPlayer#437]
## BUG 反馈

**何处触发：**
每次启动软件（冷启动）

**实际行为描述：**
每次启动软件时，第一个音乐的歌曲名、歌手名、专辑名可以正常加载；但专辑图片加载失败，音质显示为“无歌曲”

**预期的行为：**

**复现步骤：**

**配置与环境：**

- 音乐链接：
- HyPlayer 版本：Version 2.1.36.5732  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：win10

**截图（若有）**

https://github.com/HyPlayer/HyPlayer/assets/30888522/6e85e695-fab9-41ed-91e0-c9c656ae850c

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
已知问题, 设计问题, 旧版不修, 重构随缘修.
