### ISSUE TITLE
[BUG] 下载安装更新 V2.1.36.5732 后，出现了两个版本的Hplayer

### ISSUE THREAD

**Issue by heartacker** [HyPlayer/HyPlayer#438]
rt
![image](https://github.com/HyPlayer/HyPlayer/assets/1876302/727360a9-9605-483a-aaa2-d796b1aea861)

**Comment by kengwang** [comment]
已知问题，更新日志已经说了可以卸载旧版


________________________________
From: heartacker ***@***.***>
Sent: Sunday, July 23, 2023 9:28:05 AM
To: HyPlayer/HyPlayer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HyPlayer/HyPlayer] [BUG] 下载安装更新 V2.1.36.5732 后，出现了两个版本的Hplayer (Issue #438)


rt
[image]<https://user-images.githubusercontent.com/1876302/255357310-727360a9-9605-483a-aaa2-d796b1aea861.png>

―

**Comment by Raspberry-Monster** [comment]
因为证书更新导致旧版本包名和新版本不同，可以放心卸载
