### ISSUE TITLE
[BUG] 在2.1.36.5732版本中解除回环的命令过时

### ISSUE THREAD

**Issue by aw59** [HyPlayer/HyPlayer#439]
![图片](https://github.com/HyPlayer/HyPlayer/assets/70953327/662cc0c3-87a5-438c-964f-147cb31342db)
此处提供的命令是上一版本的解除回环命令，最新版本因为证书更换，导致命令失效

当前有效命令是：CheckNetIsolation LoopbackExempt -a -n="48848aaaaaaccd.HyPlayer_jdagbttk64fq4"

**Comment by kengwang** [comment]
问题已知, 将会尽快修复

**Comment by Raspberry-Monster** [comment]
Fixed
