### ISSUE TITLE
[FR] 设置页面增加搜索功能

### ISSUE THREAD

**Issue by 66622a** [HyPlayer/HyPlayer#440]
**这是什么方面的想法？**
用户体验

**这个想法具体是要实现什么？**
设置页面增加搜索功能

**这个想法实现后有什么帮助？**
本人眼瞎，经常找不到设置内容，有时候为了找一个设置要翻大半天

**是否有具体的实现思路？**

**补充信息：**

**Comment by kengwang** [comment]
wontfix
