### ISSUE TITLE
[BUG] 小窗模式，中文歌词闪烁

### ISSUE THREAD

**Issue by flypigJ** [HyPlayer/HyPlayer#442]
## BUG 反馈

**何处触发：**
小窗模式，中文歌词

**实际行为描述：**

小窗模式逐字歌词开启后中文歌词已高亮的歌词部分亮度会闪烁（不明显），且英文显示正常

**复现步骤：**

使用小窗模式播放有中文歌词的歌，注意小窗中的中文歌词

**配置与环境：**

- 音乐链接：all
- HyPlayer 版本：2.1.36.5733 Canary
- 系统版本：win11 Bata Latest

**截图（若有）**

https://github.com/HyPlayer/HyPlayer/assets/68471692/89b50398-5619-4c52-9f7f-ad870bee021f

**修复思路：**
nope

**Comment by kengwang** [comment]
此问题可能无法修复
