### ISSUE TITLE
[FR] 小窗歌词希望换回之前的句与句切换时的动效

### ISSUE THREAD

**Issue by flypigJ** [HyPlayer/HyPlayer#443]
**这是什么方面的想法？**

UI 界面 

**这个想法具体是要实现什么？**

小窗歌词希望换回之前的句与句切换时的动效

**补充信息：**
重构之后会比较难做吗？如果麻烦就算了，但真的很喜欢之前的进入动画

**Comment by kengwang** [comment]
这个动画写了又被删了, 因为部分情况会导致歌词先切后换
