### ISSUE TITLE
X-Real-IP无法保存[BUG] 

### ISSUE THREAD

**Issue by loll70** [HyPlayer/HyPlayer#446]
## BUG 反馈

**何处触发：**

实验室-X-Real-IP

**实际行为描述：**

填入IP，点击设置后无法应用。导致在海外无法使用国内匿名IP代理，歌曲无法播放。

**预期的行为：**

在海外可以使用国内匿名IP代理，歌曲可以播放。

**复现步骤：**

填入一个IP。例如下面网址里的一些。222.170.15.122:9091
http://free-proxy.cz/zh/proxylist/country/CN/all/ping/all

**配置与环境：**

- 音乐链接：n/a
- HyPlayer 版本：Version 2.1.36.5732  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：22621.2134

**截图（若有）**

无

**报错信息**

```
无
```

**补充信息：**

无

**修复思路：**

无

**Comment by Raspberry-Monster** [comment]
Fixed in https://github.com/HyPlayer/HyPlayer/commit/d972ec34d56b9aeb23bc6cfde90a8216014ab59c
