### ISSUE TITLE
[BUG] 显示设置乱跳

### ISSUE THREAD

**Issue by chr56** [HyPlayer/HyPlayer#450]
## BUG 反馈

**何处触发：**

显示设置还是在乱跳

**复现步骤：**

显示设置拖到底

**配置与环境：**

- HyPlayer 版本：V2.1.37.5743 (GitHub)
- 系统版本：Windows 11 22621.2134

**截图（若有）**

[
](https://github.com/HyPlayer/HyPlayer/assets/30681738/dda9c5b4-3e30-4bbd-9fe5-c0cc00e769de)

**补充信息：**
无

**Comment by kengwang** [comment]
这个是目前微软方面的问题, PowerToys 同样存在此问题

**Comment by kengwang** [comment]
Fixed in #455
