### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Seraph21345** [HyPlayer/HyPlayer#453]
## BUG 反馈

**何处触发：关闭后无法保存win10音量合成器应用程序设置**

**实际行为描述：设置过HyPlayer的应用程序音量后重启程序就会重置**

**预期的行为：每次启动要重新设置特定程序音量大小**

**复现步骤：记忆音量**

**配置与环境：win10**

- 音乐链接：
- HyPlayer 版本：Version 2.1.37.5743  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：Windows 10 专业版 21H1 19043.2251

**截图（若有）
![image](https://github.com/HyPlayer/HyPlayer/assets/49055918/7aff68a4-787e-43f9-9776-6a38d50c73ac)
**

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
你可以试试在 HyPlayer 内设置音量


________________________________
From: 哦啦啦啦 ***@***.***>
Sent: Sunday, September 3, 2023 5:30:54 PM
To: HyPlayer/HyPlayer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HyPlayer/HyPlayer] [BUG] (Issue #453)


BUG 反馈

何处触发：关闭后无法保存win10音量合成器应用程序设置

实际行为描述：设置过HyPlayer的应用程序音量后重启程序就会重置

预期的行为：每次启动要重新设置特定程序音量大小

复现步骤：记忆音量

配置与环境：win10

  *   音乐链接：
  *   HyPlayer 版本：Version 2.1.37.5743 (Package ID: 48848aaaaaaccd.HyPlayer)
  *   系统版本：Windows 10 专业版 21H1 19043.2251

**截图（若有）
[image]<https://user-images.githubusercontent.com/49055918/265255270-7aff68a4-787e-43f9-9776-6a38d50c73ac.png>
**

报错信息

请在此处填写报错框中的相关信息


补充信息：

修复思路：

―

**Comment by Raspberry-Monster** [comment]
这个是系统行为，无法修复
