### ISSUE TITLE
[FR] 专辑页封面在简介展开时显示改进

### ISSUE THREAD

**Issue by HHaoWang** [HyPlayer/HyPlayer#454]
**这是什么方面的想法？**
UI 界面

**这个想法具体是要实现什么？**
![image](https://github.com/HyPlayer/HyPlayer/assets/20449130/fb8bdfd3-81c7-4bf1-a130-2f386a740e32)
展开专辑简介后封面就会居中，不美观，建议上方对齐

**这个想法实现后有什么帮助？**
更美观

**Comment by kengwang** [comment]
将会在之后改进

---

> 目前 HyPlayer 项目组成员正忙, 可能需要等待很长时间才能获得项目代码修改, 请见谅.
