### ISSUE TITLE
希望能够最小化到托盘

### ISSUE THREAD

**Issue by NickerGrylls** [HyPlayer/HyPlayer#460]
**这是什么方面的想法？**

新增功能

**这个想法具体是要实现什么，实现后有何帮助？**

使软件能够最小到托盘，不占用任务栏空间
具体为在右上控制栏新增一“托盘化”选项；或新增设置，点击“最小化”/“关闭”时默认进入托盘后台运行

**是否有具体的实现思路？**

应该不难写
我能够用第三方工具实现该效果，但果然还是内置比较方便

**Comment by kengwang** [comment]
能力有限, 无法实现, 欢迎 Pr

**Comment by NickerGrylls** [comment]
> 能力有限, 无法实现, 欢迎 Pr

我不过是一个算法都写不快的学生……我尽力多学点吧😂
