### ISSUE TITLE
[BUG] 较长的歌单简介展开后仍会应用淡出效果

### ISSUE THREAD

**Issue by NickerGrylls** [HyPlayer/HyPlayer#461]
## BUG 反馈

**触发及复现**

找个简介比较长的歌单展开一下应该就能看到效果了
已尝试深色模式，影响上没有区别

**描述**

见图，gif压了色深，但意思是一样的
有时简介里还是有点信息需要看的，我不认为这符合设计意图
![2023-10-14 22-28-14 00_00_04-00_00_13~1 00_00_00-00_00_30](https://github.com/HyPlayer/HyPlayer/assets/120347871/b87cb18a-8382-42c8-b9d1-b28ce3a1edf4)

**配置与环境**

- HyPlayer 版本：2.1.37.5755
- 系统版本：Windows10家庭版22H2

**修复思路**

在简介展开时禁用相应的淡出效果
若要保持视觉表现统一性，可以依据简介的行数，仅在其末尾接近窗口顶端时应用效果（不过可能由于特殊格式等导致行数与实际显示长度不匹配，但那是极端情况了）

**Comment by zxbmmmmmmmmm** [comment]
Toolkit里边FadeHeaderBehavior的问题，貌似只能先删除了....

**Comment by NickerGrylls** [comment]
> Toolkit里边FadeHeaderBehavior的问题，貌似只能先删除了....

真是简单粗暴啊（赞赏）
