### ISSUE TITLE
[BUG] CPU占用过高

### ISSUE THREAD

**Issue by Vi-brance** [HyPlayer/HyPlayer#465]
## BUG 反馈

**何处触发：**

不确定触发原因，但触发后不论是将软件关闭重启，还是切歌CPU占用都居高不下（约20%占用）

**实际行为描述：**

进程持续占用CPU，只有关闭软件能解决。

**预期的行为：**

软件在后台时CPU占用应至少低于10%（甚至接近0%），前台播放歌曲时CPU占用在10%左右。

**复现步骤：**

不清楚复现步骤。

**配置与环境：**

- 音乐链接：任意
- HyPlayer 版本：Version 2.1.37.5755
- 系统版本：Win11 23H2 专业版

**截图（若有）**

![image](https://github.com/HyPlayer/HyPlayer/assets/82794754/47ad94ec-8fb2-4bc1-a1de-8e5cb03a65c5)

**报错信息**

```
无
```

**补充信息：**

* 安装以来基本只收听私人FM歌曲，由于网络原因开启了`解除网络环回`功能，其他设置基本默认。
* 本人CPU配置为笔电i7 10代，正常使用此软件应该不会有如此高的占用，所以判断为BUG。

**修复思路：**

**Comment by Raspberry-Monster** [comment]
现在问题仍存在吗，我这边无法复现

**Comment by Vi-brance** [comment]
> 现在问题仍存在吗，我这边无法复现

没有了，但是在长时间后台挂载时会出现卡顿，可能资源分配还有些问题。

具体情况是不关闭软件，且电脑超过2-3天不关机（会息屏or睡眠，此时软件不播放歌曲但是挂后台），接着再次点开（点到前台）时软件短时间内无法响应操作，且之后的响应都很慢（歌曲播放不受影响）。重启软件后问题解决。

这个问题没仔细排查资源管理器，但是目测没有对其它进程产生影响，所以cpu和内存占用应该都没爆。

**Comment by Raspberry-Monster** [comment]
这个大概率是系统问题，重启软件/系统应该可以解决，但是我这边无法复现所以就先Close了

**Comment by Raspberry-Monster** [comment]
这个大概率是系统问题，重启软件/系统应该可以解决，但是我这边无法复现所以就先Close了
