### ISSUE TITLE
[BUG] 本地音乐无法播放

### ISSUE THREAD

**Issue by sf467** [HyPlayer/HyPlayer#467]
## BUG 反馈

播放本地音乐时，应用会崩溃

播放本地音乐时，无论作为mp3文件的打开方式还是从软件内界面打开

卡死或崩溃

**预期的行为：**

音乐正常播放

**复现步骤：**

播放本地音乐时，无论作为mp3文件的打开方式还是从软件内界面打开

**配置与环境：**

- 音乐链接：本地mp3文件，320k音质
- HyPlayer 版本：2.1.37.5755、2.1.36.5732
- 系统版本：win11，build 23612

**截图（若有）**

![image](https://github.com/HyPlayer/HyPlayer/assets/121373973/48b79f38-36f8-4a7b-a74a-694f3a86f39c)

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by Raspberry-Monster** [comment]
不好意思，能麻烦提供一下mo3文件复现吗 谢谢

**Comment by sf467** [comment]
> 不好意思，能麻烦提供一下mo3文件复现吗 谢谢

当时在群里Kengwang大佬说是已知问题，现在已经修了，此issue关闭
