### ISSUE TITLE
[FR] 希望加入全局快捷键

### ISSUE THREAD

**Issue by LINKlang** [HyPlayer/HyPlayer#472]
**这是什么方面的想法？**

用户体验

**这个想法具体是要实现什么？**

在设置页面加入可自定义的（非）全局快捷键
可实现：播放、切歌等等

**这个想法实现后有什么帮助？**

提升用户体验

**是否有具体的实现思路？**

暂无

**Comment by zxbmmmmmmmmm** [comment]
UWP不支持全局快捷键，可以考虑使用PowerToys映射媒体键
相关信息:#304 #112
