### ISSUE TITLE
听歌防熄屏

### ISSUE THREAD

**Issue by qinglian** [HyPlayer/HyPlayer#478]
**这是什么方面的想法？**
听歌防止熄屏，自动休眠

**这个想法具体是要实现什么？**
听歌防止熄屏，自动休眠

**这个想法实现后有什么帮助？**
防止熄屏

**是否有具体的实现思路？**

**补充信息：**

**Comment by kengwang** [comment]
已经实现, 前往`设置` - `实验室` - `保持屏幕常亮`
