### ISSUE TITLE
[BUG] 进度条拖快点拖不动

### ISSUE THREAD

**Issue by caycy01** [HyPlayer/HyPlayer#483]
## BUG 反馈

**何处触发：进度条**

**实际行为描述：进度条拖快点就拖不动了**

**预期的行为：快速响应**

**复现步骤：进度条拖快点**

**配置与环境：**

- 音乐链接：任何音乐
- HyPlayer 版本：2.1.37.5786
- 系统版本：windows10

**截图（若有）**

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
Assign to @Raspberry-Monster 

那个节流好像有点问题, 我也经常能够复现

**Comment by Raspberry-Monster** [comment]
进行了一些优化，可以关注下后续更新
