### ISSUE TITLE
[BUG] 歌词闪烁

### ISSUE THREAD

**Issue by caycy01** [HyPlayer/HyPlayer#484]
## BUG 反馈

**何处触发：歌词**

**实际行为描述：歌词闪烁**

**预期的行为：丝滑的**

**复现步骤：将进度条点到中间，再往回点**

**配置与环境：**

- 音乐链接：https://music.163.com/#/song?id=26580049
- HyPlayer 版本：2.1.37.5786
- 系统版本：window10

**截图（若有）**
![1712192819624](https://github.com/HyPlayer/HyPlayer/assets/98204496/8da144e8-2dd1-4a21-8eae-633a1d54e21a)

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by zxbmmmmmmmmm** [comment]
Win2D的小窗也会这样
在部分设备上复现，可能是显卡驱动的问题

**Comment by kengwang** [comment]
可以尝试开启歌词控件调试模式, 看一下绘制的详细信息再截图反馈

**Comment by caycy01** [comment]
![1712378406384](https://github.com/HyPlayer/HyPlayer/assets/98204496/69862db3-defd-431a-b90d-3ab89383d7b8)



> 可以尝试开启歌词控件调试模式, 看一下绘制的详细信息再截图反馈

**Comment by caycy01** [comment]
在Version 2.1.37.5795中 问题照旧
![9629657fc94713d334de09225f898063](https://github.com/HyPlayer/HyPlayer/assets/98204496/c3bfd3f3-1e84-4e61-bc44-2a53080eea14)
