### ISSUE TITLE
[BUG] 新版歌词渲染的问题

### ISSUE THREAD

**Issue by ApigeonAPE** [HyPlayer/HyPlayer#486]
## BUG 反馈

**何处触发：**

歌词

**实际行为描述：**

1.新的歌词不如老版本清晰，好像有一层光晕，和左侧的歌曲信息对比可以明显的看出。特别是下方的翻译显得尤为模糊。
2.如图，阴影的大小有误，和放大前一致，导致了问题。
3.打开歌词时会先变成一长条，再排成歌词（较为抽象可直接看图）

**预期的行为：**

1.歌词清晰
2.阴影大小正常
3.动画正常

**复现步骤：**

打开歌词

**配置与环境：**

- 音乐链接：任何音乐
- HyPlayer 版本：Version 2.1.37.5786  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：22H2

**截图（若有）**

![image](https://github.com/HyPlayer/HyPlayer/assets/61077394/2d365be6-2a71-47e3-bcc6-f035a2ec09c7)
![image](https://github.com/HyPlayer/HyPlayer/assets/61077394/0aa04a74-9795-45ca-9a6e-fcccb4745baa)

以上两张图对比可见问题1、2

![image](https://github.com/HyPlayer/HyPlayer/assets/61077394/1f946a97-9350-42dc-b3d8-9e4514555385)

上图为问题3

**补充**

新版歌词动画挺好看的，加油

**Comment by kengwang** [comment]
1. 这个是专门的特效, 可以前往 `设置` - `歌词设置` - `歌词特效` - `高亮焦点歌词`, 将这个选项关闭

2. 这个问题已知, 已经被修复, 将会在下一个版本实装

3. 这个是我的问题, 其实不该让用户看到这个长条, 在加载完成前不应当绘制

**Comment by kengwang** [comment]
感谢支持!

**Comment by ApigeonAPE** [comment]
抱歉，刚刚发现问题1确实是功能，是我疏忽了。
感谢
