### ISSUE TITLE
[BUG] 新版歌词渲染在渲染可变字体时出错

### ISSUE THREAD

**Issue by Nevodev** [HyPlayer/HyPlayer#487]
## BUG 反馈

**何处触发：**

歌词页在渲染可变字体时

**实际行为描述：**

歌词界面字形渲染错误

**预期的行为：**

笔画应该是实心的

**复现步骤：**

设置-歌词设置-歌词显示-歌词字体-选择一款可变字体（我这里选择Unbounded与SF Pro演示）

**配置与环境：**

- 音乐链接：任意
- HyPlayer 版本：2.1.37.5794
- 系统版本：Windows 11 24H2 26100.1

**截图（若有）**

可以确认不是SF Pro字体本身的问题，别的可变字体也有这个问题
Unbounded字体
![image](https://github.com/HyPlayer/HyPlayer/assets/51047891/333bee8d-4c10-4b66-aed1-b3e010159f2c)
SF Pro字体
![image](https://github.com/HyPlayer/HyPlayer/assets/51047891/02b4636a-35db-4489-a035-ae1603243dce)

**报错信息**

**补充信息：**

大概是因为字形的路径有部分重叠，见下图
Unbounded字体
![image](https://github.com/HyPlayer/HyPlayer/assets/51047891/4339c678-7313-4d64-86ef-04020c328173)
SF Pro字体
![image](https://github.com/HyPlayer/HyPlayer/assets/51047891/8269a8db-b88c-4647-b224-3352592376fe)
![image](https://github.com/HyPlayer/HyPlayer/assets/51047891/cf6b50b0-ac4d-45d0-82ef-c3834359648e)

**修复思路：**

**Comment by kengwang** [comment]
可能由于geometey拼接导致，之后换成矩形裁切

**Comment by Raspberry-Monster** [comment]
Fixed
