### ISSUE TITLE
[FR] 能不能在评论区里添加正常显示表情的功能，优化用户体验

### ISSUE THREAD

**Issue by SiYuan-Y** [HyPlayer/HyPlayer#495]
![屏幕截图 2024-04-27 131338](https://github.com/HyPlayer/HyPlayer/assets/98321536/79498b75-1a23-4446-8304-70acc6b9918e)
我是一个喜欢看评论区的人，而这些发布在网易云的评论里并不能显示出它原来的表情。我想能不能添加相关的功能，使这些表情正常显示出来。

**Comment by Raspberry-Monster** [comment]
由于软件本身的重点并不在评论区 加上不方便解析 优先度低
