### ISSUE TITLE
[bug] 可选动效无法开启

### ISSUE THREAD

**Issue by FrzMtrsprt** [HyPlayer/HyPlayer#50]
## BUG 反馈

**何处触发：**

设置页

**实际行为描述：**

可选动效无法开启

**预期的行为：**

可选动效能够正常开启并工作

**复现步骤：**
1. 在设置页勾选可选动效
2. 切换至任意页面后
3. 切换回设置页
4. 发现可选动效仍未启用，且播放页并没有什么动效

**配置与环境：**

- 音乐链接：🈚
- HyPlayer 版本：1.0.40.0
- 系统版本：21390.2025

**截图（若有）**

🈚

**报错信息**

```
🈚
```

**补充信息：**

🈚

**修复思路：**

🈚

**Comment by kengwang** [comment]
对不起,可选动效现在只是 方形歌单的动效 和 展开关闭播放器的连接动画
之前 beauty 分支加了动效的,后来因为效率和观赏度不够就删了

如需进一步讨论,可以Reopen
