### ISSUE TITLE
[BUG] “最近播放”的歌曲列表int32溢出

### ISSUE THREAD

**Issue by HuajiKojima** [HyPlayer/HyPlayer#507]
## BUG 反馈

**何处触发：** 在最新的2.1.37.5810版本中，“最近播放”页面中触发。

**实际行为描述：** 界面右上角出现”Value was either too large or too small for an Int32.“异常提示。同时无法加载“最近播放歌曲”选项卡对应的歌曲列表。且单击“听歌排行（全部）”选项卡也会出现上述问题。但此问题并不会导致程序崩溃退出，正在播放的歌曲也并未受到影响且继续正常播放。

**预期的行为：** 正常加载歌曲列表并且可播放列表中歌曲.

**复现步骤：** 点击主界面侧边菜单中的“音乐”选项组中的“播放历史”选项，点击“最近播放歌曲”以及“听歌排行（全部）”选项卡会出现上述问题，但目前“听歌排行（本周）”选项卡暂未出现上述问题。

**配置与环境：**

- 音乐链接：
- HyPlayer 版本：2.1.37.5810
- 系统版本：Windows 11 23H2

**截图（若有）**

![image](https://github.com/HyPlayer/HyPlayer/assets/44185970/41201c9c-724f-48ab-ac63-bb45a5989767)

![image](https://github.com/HyPlayer/HyPlayer/assets/44185970/e7d2fae3-3f9d-4966-a34f-b5fea331cd2a)

**报错信息**

```

Value was either too large or too small for an Int32.
Exception of type 'System.Exception' was thrown.

```

**补充信息：**

由于个人本周播放歌曲次数较少，所以无法确定“听歌排行（本周）”选项卡对应的歌曲列表在加载时不会出现上述问题。

**修复思路：**

是否在修复之前int32溢出问题时并未考虑到“最近播放”页面的歌曲列表加载？

**Comment by kengwang** [comment]
我们正在排查最近大量出现的int32溢出问题并尝试修复

**Comment by HuajiKojima** [comment]
今早部署并开启调试看了一下：貌似是在NCSongs.cs里面的CreateFromJason方法抛出了这个异常，如下图示，解析到歌曲对应的JSON信息里面“mv”一项（红框框选处）的内容为6013229092910299.但是代码断点处这里使用的类型转换是int，同时NCSong的类成员mvid也是int类型，无法存储像是上述如此之大的mvid。为了防止之后长度比这更离谱的mvid，建议改成long或ulong

![image](https://github.com/HyPlayer/HyPlayer/assets/44185970/aab83d6b-9d53-4f9f-80c2-327a6c7cda06)

本地部署的代码修改相关问题后正常显示：

![image](https://github.com/HyPlayer/HyPlayer/assets/44185970/dbcef0c8-a4e4-4493-8a31-261ce3dd3813)

**Comment by Raspberry-Monster** [comment]
后面改为string

**Comment by Raspberry-Monster** [comment]
目前已经尽量将可以检查到的会引发错误的位置替换为string
163Key因为无法使用String所以已经替换为ulong，麻烦协助重新编译一下看看其他地方是否仍能复现
感谢您的帮助！

**Comment by HuajiKojima** [comment]
您太客气了，之后我这里会去重新编译并查看一下。
