### ISSUE TITLE
[BUG] 逐字歌词无法关闭

### ISSUE THREAD

**Issue by AtriDayo** [HyPlayer/HyPlayer#513]
## BUG 反馈

**何处触发：关闭歌词逐字歌词功能时触发。**

**实际行为描述：在关闭逐字歌词后仍然会使用逐字歌词播放。**

**预期的行为：关闭逐字歌词后整行显示歌词。**

**复现步骤：关闭逐字歌词开关，重启软件，重新查看歌词播放界面**

**配置与环境：**

- 音乐链接：
- HyPlayer 版本：2.1.37.5810
- 系统版本：Windows 11 23H2

**截图（若有）**

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
请检查设置 - 歌词设置 - 最底部有个 非逐字歌词扫词，将其关闭即可


________________________________
From: 枫原万叶 ***@***.***>
Sent: Tuesday, June 4, 2024 5:14:18 PM
To: HyPlayer/HyPlayer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HyPlayer/HyPlayer] [BUG] 逐字歌词追踪错误 (Issue #513)


BUG 反馈

何处触发：播放在网易云官方歌词源无逐字歌词时触发。

实际行为描述：程序会按照一行歌词的时间去平均滚动逐字歌词。

预期的行为：如果找不到逐字歌词，使用整行显示。

复现步骤：

配置与环境：

  *   音乐链接：
  *   HyPlayer 版本：2.1.37.5810
  *   系统版本：Windows 11 23H2

截图（若有）

报错信息

请在此处填写报错框中的相关信息


补充信息：关闭逐字歌词选项，并重启软件，仍无法关闭。

修复思路：

―
