### ISSUE TITLE
[BUG] 横向分辨率低于1050 100%缩放下歌词页背景模糊异常

### ISSUE THREAD

**Issue by gongfuture** [HyPlayer/HyPlayer#518]
## BUG 反馈

**何处触发：** 歌词页

**实际行为描述：** 背景模糊组件排列异常

**预期的行为：** 正常显示

**复现步骤：** 屏幕分辨率调节至横向分辨率低于1050 100%缩放下 , 打开显示设置-歌词页面-背景显示设置-专辑封面模糊 , 选择任意歌曲(最好是封面比较鲜艳的)播放后 , 打开歌词页面

**配置与环境：**

- 音乐链接：任意
- HyPlayer 版本：Version 2.1.37.5827 (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：
版本 Windows 10 专业版
版本号 22H2
安装日期 ‎2023/‎1/‎13
操作系统内部版本 19045.4474
体验 Windows Feature Experience Pack 1000.19058.1000.0

**截图（若有）**
![IMG_20240608_150316](https://github.com/HyPlayer/HyPlayer/assets/60888755/6c5493fb-b24f-45d1-9330-f6b0966b8aca)
抱歉拍照 , 使用截图时则显示正常

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：** 一开始以为是副屏问题 , 后来发现是分辨率导致的 #517 

**修复思路：**

**Comment by gongfuture** [comment]
这下又奇怪了 , 1050*1680正常 , 1067*1707异常 , 1024*1600异常

**Comment by Raspberry-Monster** [comment]
是否有安装美化软件，如有麻烦暂时停用一下

**Comment by gongfuture** [comment]
Version 2.1.37.5836  (Package ID: 48848aaaaaaccd.HyPlayer) 更新后恢复正常

**Comment by gongfuture** [comment]
Version 2.1.37.5854  (Package ID: 48848aaaaaaccd.HyPlayer)
仍可触发该问题，所有美化软件均已关闭

**Comment by Raspberry-Monster** [comment]
太奇怪了 我这边没法复现

**Comment by Raspberry-Monster** [comment]
![IMG_20240716_172050](https://github.com/user-attachments/assets/4fd3325d-8d03-427c-8c5f-0f61c72f9783)
![IMG_20240716_172253](https://github.com/user-attachments/assets/ff588257-7e2a-4e3f-b869-e62a8364c2ac)
这两个我都测试过 一个是N卡 2060 一个是 I卡 DG1 都正常

**Comment by gongfuture** [comment]
> ![IMG_20240716_172050](https://github.com/user-attachments/assets/4fd3325d-8d03-427c-8c5f-0f61c72f9783)
> ![IMG_20240716_172253](https://github.com/user-attachments/assets/ff588257-7e2a-4e3f-b869-e62a8364c2ac)
> 这两个我都测试过 一个是N卡 2060 一个是 I卡 DG1 都正常

竖屏情况下调低分辨率呢？我怀疑可能是元素布局挤压导致的（大概是这个意思）
我明天白天也多测试一下看看

**Comment by gongfuture** [comment]
我这里使用的是1050×1680,125%，稳定复现

**Comment by Raspberry-Monster** [comment]
你更新下显卡驱动看看？我这边还是没法复现

**Comment by gongfuture** [comment]
更新显卡驱动并且所有美化开机自启关了重启之后，还是有
顺带一提今天推的Version 2.1.37.5857  (Package ID: 48848aaaaaaccd.HyPlayer)装上之后直接打不开歌词界面了，这下都测试不了了（
我去再开一个issue去（

**Comment by Raspberry-Monster** [comment]
给一下系统版本那些？

**Comment by Raspberry-Monster** [comment]
还有硬件配置 我这里是真没办法复现了 要不你试试看重装吧

**Comment by Raspberry-Monster** [comment]
分辨率 横竖屏都试过了 DPI也试过了

**Comment by gongfuture** [comment]
草，那我回头自己研究研究吧

**Comment by gongfuture** [comment]
从57回退到54之后又好了，和上次一样，也是版本变动重新安装之后就好，过了好一阵子就有问题，好奇怪啊
