### ISSUE TITLE
期望加入新建歌单、第三方平台登陆功能

### ISSUE THREAD

**Issue by orzgithub** [HyPlayer/HyPlayer#52]
**这是什么方面的想法？**

软件方面功能

**这个想法具体是要实现什么？**

> 增加新建歌单功能
> 增加第三方账号登陆

**这个想法实现后有什么帮助？**

> 使用户可以直接在程序内添加新的歌单
> 使用户可以使用绑定了网易云账号的第三方账号登陆

**Comment by EP012014** [comment]
新建歌单已经有了
还没发布到商店

**Comment by EP012014** [comment]
> **这是什么方面的想法？**
> 
> 软件方面功能
> 
> **这个想法具体是要实现什么？**
> 
> > 增加新建歌单功能
> > 增加第三方账号登陆
> 
> **这个想法实现后有什么帮助？**
> 
> > 使用户可以直接在程序内添加新的歌单
> > 使用户可以使用绑定了网易云账号的第三方账号登陆

直接在程序内添加新的歌单建议您下载最新的
[自动构建包](https://dev.azure.com/kengwang/c353f3d8-cb71-45a4-921d-ad8e6f898505/_apis/build/builds/1577/artifacts?artifactName=drop&api-version=6.0&%24format=zip)
然后手动部署（右键点击Install.ps1，选择用powershell执行
至于第三方账号登陆，理论上是可以用webview调用网页版进行然后导入cookie
不过这个不在开发计划内
可能要等到以后了

**Comment by EP012014** [comment]
8bc5e4f
