### ISSUE TITLE
[BUG] system.io.filenotfoundexception:找不到指定的模块。（Exception form HRESULT:0x8007007E)

### ISSUE THREAD

**Issue by orianna773345115** [HyPlayer/HyPlayer#521]
## BUG 反馈

**何处触发：播放时

**实际行为描述：报错提示 system.io.filenotfoundexception:找不到指定的模块。（Exception form HRESULT:0x8007007E)

**预期的行为：正常播放

**复现步骤：播放任意在线歌曲

**配置与环境：**

- 音乐链接：
- HyPlayer 版本：2.1.37.5836
- 系统版本：Microsoft Windows 11 专业工作站版 Insider Preview  10.0.26217 版本 26217

**截图（若有）
![屏幕截图 2024-06-18 113147](https://github.com/HyPlayer/HyPlayer/assets/34902408/a9208979-da1a-499d-83f9-8b3dfaa46cff)

**报错信息 system.io.filenotfoundexception:找不到指定的模块。（Exception form HRESULT:0x8007007E)

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by Raspberry-Monster** [comment]
请问是否开启了播放前缓存，如有麻烦关闭 谢谢

**Comment by orianna773345115** [comment]
> 请问是否开启了播放前缓存，如有麻烦关闭 谢谢
![屏幕截图 2024-06-20 105632](https://github.com/HyPlayer/HyPlayer/assets/34902408/1608ec59-429a-40b2-b973-0395d5adb253)
没有开启

**Comment by Raspberry-Monster** [comment]
能重新安装后在尝试吗？

**Comment by orianna773345115** [comment]
> 能重新安装后在尝试吗？

用geek卸载后分别重新安装了release和canary版本，问题仍然存在

**Comment by orianna773345115** [comment]
> 能重新安装后在尝试吗？

用geek卸载后分别重新安装了release和canary版本，问腿仍然存在

**Comment by Raspberry-Monster** [comment]
请问一下是精简版系统还是原版系统，我这边无法复现这个问题

**Comment by orianna773345115** [comment]
> 请问一下是精简版系统还是原版系统，我这边无法复现这个问题

UUP下载的原版系统

**Comment by orianna773345115** [comment]
> 请问一下是精简版系统还是原版系统，我这边无法复现这个问题

系统更新昨天推送的26241版本问题消失了，也许是上个版本的bug

**Comment by Raspberry-Monster** [comment]
OK
