### ISSUE TITLE
切换歌曲时的bug

### ISSUE THREAD

**Issue by orzgithub** [HyPlayer/HyPlayer#53]
## BUG 反馈

**何处触发：**

出现在切换音乐时

**实际行为描述：**

出现在手动在不同歌单中用双击进行音乐切换时。现象为音乐暂停但并不会切换到所选歌曲，同时播放列表不发生变化。

**预期的行为：**

总之就是挺不方便。

**复现步骤：**

试试在不同歌单之间通过双击歌曲来切换，至少我这边会出现该bug。重启系统/软件均可以以相同方式复现。

**配置与环境：**

- HyPlayer 版本：1.0.41.0（Microsoft Store版本）
- 系统版本：Windows10专业工作站版 20H2 （19042.1052）

**报错信息**

未报错

**补充信息：**

无

**Comment by kengwang** [comment]
播放控制这边我来改吧

**Comment by kengwang** [comment]
经过测试无法复现,如果可能可以提供播放列表id.
我这边也看看App Center有没有日志

**Comment by kengwang** [comment]
此Issue在时间内没有回应，自动Close
