### ISSUE TITLE
[FR] 板载声卡/usb声卡 独占 以提升实际音质

### ISSUE THREAD

**Issue by AuroraNasa** [HyPlayer/HyPlayer#532]
**实现类似网易云原版的usb独占**

**实现类似网易云原版的usb独占**

**对一些设备大幅提升音质，以保证最接近无损的输出**

** WASAPI允许传输未经修改的比特流到音频设备，从而避开SRC（Sample Rate Conversion，取样率转换器）的干扰。 可以按照已有的做法 原版网易云 其他音乐播放器。放弃播放设置里选择音频输出设备调用的，类似网易云原版的。**

**补充信息：无**

**Comment by Raspberry-Monster** [comment]
MediaPlayer所使用的音频输出API就是WASAPI

具体可以参照这个文档

https://learn.microsoft.com/zh-cn/windows-hardware/drivers/audio/windows-audio-architecture

**Comment by Raspberry-Monster** [comment]
独占功能因为UWP限制，无法实现
