### ISSUE TITLE
[BUG] 2.1.37.5857无法打开歌词界面

### ISSUE THREAD

**Issue by gongfuture** [HyPlayer/HyPlayer#533]
## BUG 反馈

**何处触发：**打开歌词界面，即左侧曲绘图标
![image](https://github.com/user-attachments/assets/acd68701-8eaf-4e2b-8552-79bd8e296667)
和右侧
![image](https://github.com/user-attachments/assets/fc5d1e36-a1a0-464e-b35a-4cad3ce77b39)

**实际行为描述：**打开歌曲详情即歌词界面

**预期的行为：**无法打开，且右侧控件处于打开状态无法复位

**复现步骤：**

**配置与环境：**

- 音乐链接：
- HyPlayer 版本：Version 2.1.37.5857  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎1/‎13
操作系统内部版本	19045.4651
体验	Windows Feature Experience Pack 1000.19060.1000.0

**截图（若有）**

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
请提供一下设备识别码方便我们定位问题?

> 进入 HyPlayer 设置 - 关于 - 设备识别码 - 右键复制

**Comment by gongfuture** [comment]
1b26713f-ff10-72aa-48f4-f944441ba8e2

**Comment by kengwang** [comment]
已经收到, 开发组正在处理

**Comment by BLACKCHARGE** [comment]
同样的问题，无法打开歌词

**Comment by kengwang** [comment]
断定为新组件在 Windows 10 上存在兼容问题, 如果遇到这个情况的可以回滚到上一版本

https://github.com/HyPlayer/HyPlayer/releases/tag/2.1.37.5854

**Comment by zxbmmmmmmmmm** [comment]
![c77cb7e58f3035cecc984efa11617d2d](https://github.com/user-attachments/assets/aaac6327-8bf8-4815-8eeb-305ced69158c)
develop分支似乎是正常的..?

**Comment by kengwang** [comment]
dev 分支已经修复, 最新 Canary 已经修复
