### ISSUE TITLE
[FR] 关闭时最小化功能

### ISSUE THREAD

**Issue by paseofyou** [HyPlayer/HyPlayer#538]
**这是什么方面的想法？**
现有内容的优化 & 新增功能

**这个想法具体是要实现什么？**
关闭最小化

**这个想法实现后有什么帮助？**
改进用户体验，符合用户习惯关闭所有窗口导致误关闭音乐播放。减少主要的任务栏占用栏位

**是否有具体的实现思路？**
1. 点击关闭按钮后最小化到后台任务栏运行
2. 会弹出对话框提示每次关闭是否最小化，且下次点击关闭不再提示，将此处配置写入配置文件。
3. 可在设置重新更改每次关闭最小化配置。

**Comment by kengwang** [comment]
UWP 限制，无法实现
