### ISSUE TITLE
[BUG] Windows 11 控制中心媒体管理有两个Hyplayer

### ISSUE THREAD

**Issue by whwdzg** [HyPlayer/HyPlayer#541]
## BUG 反馈

**何处触发：**

打开Hyplayer播放

**实际行为描述：**

控制中心媒体管理有两个Hyplayer，一个显示正常的封面和名称，另一个不显示

**预期的行为：**

仅一个

**复现步骤：**

每次均可复现

**配置与环境：**

- 音乐链接：/
- HyPlayer 版本：Version 2.1.37.5863  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：26100.1586

**截图（若有）**

![image](https://github.com/user-attachments/assets/cec91dc5-441f-4ae6-b5d4-2419b10c9c98)
![image](https://github.com/user-attachments/assets/335004f3-a437-4a1a-9fd5-9b57647a7402)

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

**修复思路：**

**Comment by kengwang** [comment]
请关闭使用传统 SMTC


________________________________
From: Alex Yang ***@***.***>
Sent: Thursday, August 22, 2024 9:50:11 AM
To: HyPlayer/HyPlayer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HyPlayer/HyPlayer] [BUG] Windows 11 控制中心媒体管理有两个Hyplayer (Issue #541)


BUG 反馈

何处触发：

打开Hyplayer播放

实际行为描述：

控制中心媒体管理有两个Hyplayer，一个显示正常的封面和名称，另一个不显示

预期的行为：

仅一个

复现步骤：

每次均可复现

配置与环境：

  *   音乐链接：/
  *   HyPlayer 版本：Version 2.1.37.5863 (Package ID: 48848aaaaaaccd.HyPlayer)
  *   系统版本：26100.1586

截图（若有）

image.png (view on web)<https://github.com/user-attachments/assets/cec91dc5-441f-4ae6-b5d4-2419b10c9c98>
image.png (view on web)<https://github.com/user-attachments/assets/335004f3-a437-4a1a-9fd5-9b57647a7402>

报错信息

请在此处填写报错框中的相关信息


补充信息：

修复思路：

―
