### ISSUE TITLE
Add X-Real-IP options to bypass location check

### ISSUE THREAD

**Issue by Lutra-Fs** [HyPlayer/HyPlayer#55]
**这是什么方面的想法？**

新增功能

**这个想法具体是要实现什么？**

> 由于网易限制,此项目在国外服务器或部分国内云服务上使用会受到限制,如 460 cheating异常,如需解决 , 可使用大陆服务器或者使用代理 , 感谢 @hiyangguo提出的解决方法: 在 '/util/request.js' 的 'headers' 处增加 X-Real-IP':'211.161.244.70' // 任意国内 IP 即可解决 
现在 在Nodejs版中可以添加X-Real-IP参数

**这个想法实现后有什么帮助？**
Bypass Location Check

**是否有具体的实现思路？**
Add X-Real-IP parameter while calling the API.

**补充信息：**

**Comment by kengwang** [comment]
感谢反馈,正准备吧这个参数的设置公开出来,顺带公开代理服务器的设置,这样可以用UnblockNeteaseCloudMusic
