### ISSUE TITLE
[BUG] 亚克力背景不在焦点时失效

### ISSUE THREAD

**Issue by yixyming** [HyPlayer/HyPlayer#560]
## BUG 反馈

**何处触发：**

背景显示

**实际行为描述：**
窗口不在焦点时亚克力效果消失,  变成黑色背景, 或者白色

**预期的行为：**

无论是否失去焦点,  亚克力背景应当一直正常显示

**复现步骤：**

失去焦点,  随便点一下其他窗口

**配置与环境：**

- 音乐链接：
- HyPlayer 版本：Version 2.1.37.5872  (Package ID: 48848aaaaaaccd.HyPlayer)
- 系统版本：Windows 11 23H2

**截图（若有）**

![微信图片_20241215015835](https://github.com/user-attachments/assets/5b5fe734-d165-40b4-901e-16fd14834d05)
![微信图片_20241215015846](https://github.com/user-attachments/assets/756826fc-53ab-4244-aaa1-a35757df562a)

**报错信息**

```
无报错框
```

**补充信息：**

谢谢, HyPlayer的亚克力很棒,  搭配上歌词软件美观性拉满了

**修复思路：**

**Comment by yixyming** [comment]
另外希望HyPlayer能缩小到托盘, 和改进一下与Windows 11的媒体控制键的适配,  我一定爱发电支持

**Comment by kengwang** [comment]
亚克力失焦失效为 Windows 强制行为, 目的为了减少不必要的显卡占用. 无法实现
