### ISSUE TITLE
进度条无法点击/拖拽

### ISSUE THREAD

**Issue by RERASER** [HyPlayer/HyPlayer#58]
## BUG 反馈

**何处触发：**

点击或拖拽进度条时

**实际行为描述：**

点击进度条的话会回弹回去，拖拽进度条的话会导致重新播放

**预期的行为：**

正常调整播放进度

**复现步骤：**

在XSX上使用手柄

**配置与环境：**

- 音乐链接：所有音乐均如此
- HyPlayer 版本：1.0.42.70 Preview
- 系统版本：10.0.19041.8126(xb_flt_2106vb.210608-1700)

**截图（若有）**

XBOX在非游戏界面无法截图

**报错信息**

无

**Comment by RERASER** [comment]
更正:点击无法使用是全部歌曲，拖拽是仅部分无法使用

**Comment by kengwang** [comment]
由于旧版的进度判断出现问题，已在Commit be6c84c4b1419debee90cdd8d177ba87dfac4e1e 中修复，由于版本迭代原因，此Commit暂未发布到Microsoft Store，可能会在1周后才能收到更新。
如需继续跟进此问题，请在三天内留言。此Issue将在三天无回应后关闭

**Comment by EP012014** [comment]
三天无回应，关闭
