### ISSUE TITLE
本地和下载页面选中后卡住

### ISSUE THREAD

**Issue by kengwang** [HyPlayer/HyPlayer#60]
## BUG 反馈

**何处触发：**

左侧菜单栏 本地和下载

**实际行为描述：**

点击之后整个软件卡住,无法进行操作或关闭

**预期的行为：**

正常显示内容

**复现步骤：**

可以复现

**配置与环境：**

- HyPlayer 版本：（Release 标注的版本号，Commit 版则写 Commit 编号）
- 系统版本：Win 11 22000.65

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

@EP012014 这个功能可以再优化下. 比如说本地的扫描可以放到异步操作里面,可能就是这个导致的卡顿但我这边无法修复

**修复思路：**

**Comment by EP012014** [comment]
无法复现
