### ISSUE TITLE
登录密码错误产生的空指针异常

### ISSUE THREAD

**Issue by Hammerliu** [HyPlayer/HyPlayer#61]
## BUG 反馈

**何处触发：**

邮箱登录时输入错误的密码

**实际行为描述：**

登录

**预期的行为：**

产生密码错误的提示

**复现步骤：**

登入时输入错误的密码即可

**配置与环境：**

- HyPlayer 版本：daddbf7
- 系统版本：Windows 10 Pro 21H119043.1110

**截图**

![ApplicationFrameHost_5oqS8LNgts.png](https://i.loli.net/2021/07/19/5jBXuqfWkbm9ye4.png)

**修复思路：**
自己排查了下发现是云音乐API的问题，在Request.cs文件中，CreateRequest方法146行
`return (status == 200, answer);`
因为密码错误的话上文的status会赋值为502，从而返回false。
进一步的在CloudMusicApi.cs 第143行判断之后直接使JObject返回为null。

**Comment by kengwang** [comment]
哇,感谢大佬这么详细的分析
