### ISSUE TITLE
最新版本怎么安装啊？

### ISSUE THREAD

**Issue by jialiangZ** [HyPlayer/HyPlayer#65]
安装显示缺证书，安装包内的证书也没用，开发者能出个具体的安装流程吗？谢谢

**Comment by kengwang** [comment]
可以从商店下载正式通道版本，假如要用Github Commit版本可以右键运行drop.zip中的install.ps1来安装

**Comment by kengwang** [comment]
之后我在drop里面放个安装流程吧

**Comment by jialiangZ** [comment]
好嘞，谢谢你
