### ISSUE TITLE
添加快捷键支持

### ISSUE THREAD

**Issue by GDWGH** [HyPlayer/HyPlayer#66]
**这是什么方面的想法？**

新增功能

**这个想法具体是要实现什么？**
添加快捷键 更快的切换歌曲

**这个想法实现后有什么帮助？**
更方便切换歌曲

**是否有具体的实现思路？**
无

**补充信息：**
希望可以使用网易云PC版那套的快捷键 （习惯了）

**Comment by GDWGH** [comment]
评论区bug： 不会在切歌的时候自动刷新评论区

https://user-images.githubusercontent.com/57795156/127585549-39809a1d-79fb-4679-8c47-4ffd5bdc92dc.mp4

mini模式bug：错误载入完整模式的按钮
![image](https://user-images.githubusercontent.com/57795156/127585648-345d201a-0a4a-452a-8d8c-764c062df506.png)

而且 在进入上一级的时候 mini模式关闭需要按两次按钮

https://user-images.githubusercontent.com/57795156/127586038-d22d90a6-587a-47fc-8058-0fa663c86370.mp4

以上测试均在2.0.17.0进行

**Comment by kengwang** [comment]
首先感谢反馈!
1. 快捷键的话将会在之后版本加,在现在的版本可以通过MSTC来控制音乐的播放和暂停
2. 评论不刷新主要是因为评论是和当前播放歌曲独立开的 (网易云手机端就是这样)
3. Mini 模式点两次将会在下个版本修复.

**Comment by GDWGH** [comment]
感谢回复 如果下一个版本还有bug 我会把这个issue 再打开

HONOR携帯電話から送信

**Comment by kengwang** [comment]
还有什么问题吗?

**Comment by GDWGH** [comment]
当再打开的时候 我原来设置的单曲重复 变成了列表播放

**Comment by GDWGH** [comment]
载入的时候 好像有点慢或者卡(第一次用的时候 就有了） 不知道是哪里出了问题
版本：2.0.17.0
网络：广东移动

**Comment by GDWGH** [comment]
还有 原曲部分的字感觉有点淡
![image](https://user-images.githubusercontent.com/57795156/127604531-52c2f03b-aeda-489e-acf3-2b922529a88a.png)

**Comment by kengwang** [comment]
> 还有 原曲部分的字感觉有点淡
> ![image](https://user-images.githubusercontent.com/57795156/127604531-52c2f03b-aeda-489e-acf3-2b922529a88a.png)

emm,这个之后我调下画笔颜色

**Comment by kengwang** [comment]
假如修复了的问题我会直接修改提出的问题的内容并在后面加上修复的Commit标签

**Comment by kengwang** [comment]
> 还有 原曲部分的字感觉有点淡
> ![image](https://user-images.githubusercontent.com/57795156/127604531-52c2f03b-aeda-489e-acf3-2b922529a88a.png)

![image](https://user-images.githubusercontent.com/30862240/127610144-00df93ee-43da-419c-a672-2f299c9b2766.png)
这种颜色怎么样?

**Comment by GDWGH** [comment]
> ![image](https://user-images.githubusercontent.com/30862240/127610144-00df93ee-43da-419c-a672-2f299c9b2766.png)
> 这种颜色怎么样?

也许需要实装看看 毕竟我用的不是普通屏幕 是电视

**Comment by kengwang** [comment]
那晚上我发个包到Beta和Release

**Comment by GDWGH** [comment]
这是什么方面的想法？

新增功能

这个想法具体是要实现什么？
在歌单页面添加 歌单内搜索功能

这个想法实现后有什么帮助？
更方便找到歌曲

是否有具体的实现思路？
无

补充信息：
无

**Comment by GDWGH** [comment]
> > ![image](https://user-images.githubusercontent.com/30862240/127610144-00df93ee-43da-419c-a672-2f299c9b2766.png)
> > 这种颜色怎么样?
> 
> 也许需要实装看看 毕竟我用的不是普通屏幕 是电视

还可以（不过有时玩过游戏的时候 电视屏幕的gamma值 和开机的时候不一样）

**Comment by kengwang** [comment]
对了,请问是否是Xbox设备,会不会出现掉后台的情况?

**Comment by GDWGH** [comment]
> 对了,请问是否是Xbox设备,会不会出现掉后台的情况?

并不是 但是我的PC出现了掉后台（太久 无响应）

**Comment by GDWGH** [comment]
> 对了,请问是否是Xbox设备,会不会出现掉后台的情况?

不是 不过我的PC也出现掉后台情况（挂在后台的时候 回去 就无响应 退出了）

**Comment by GDWGH** [comment]
评论区bug：当点进某一首歌的评论区的时候 再回到那首歌所属的歌单的时候 无法回到歌单（我喜欢的歌单和我创建的歌单均有这个bug）

https://user-images.githubusercontent.com/57795156/127823731-dd4f060f-0359-4f34-99a8-9b33c228a064.mp4

**Comment by GDWGH** [comment]
搜索栏的奇怪bug（只能用手机拍 因为录屏和软件的严重滞后）：
This video is too big:  https://ws28.cn/f/61we9pnu5d1 复制链接到浏览器打开

**Comment by kengwang** [comment]
感谢持续的问题反馈,已在调查追踪中

**Comment by kengwang** [comment]
当前所提的问题都以答复,请留意

**Comment by GDWGH** [comment]
所以说会优化吗？
毕竟咱的电脑已经是渣了吧（
![image](https://user-images.githubusercontent.com/57795156/128023697-6ab89ed3-34a6-480d-a207-02e1b2611524.png)

**Comment by GDWGH** [comment]
> 这是什么方面的想法？
> 
> 新增功能
> 
> 这个想法具体是要实现什么？
> 在歌单页面添加 歌单内搜索功能
> 
> 这个想法实现后有什么帮助？
> 更方便找到歌曲
> 
> 是否有具体的实现思路？
> 无
> 
> 补充信息：
> 无

那么这个会考虑吗?

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-891853037
这个后期会改,因为逻辑结构可能要重新改改,到时候会和 #18 一起修

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-891847694
关于优化的话现在正常使用内存占用不到100MB

> 每次挂在后台的时候 忘记切回去 就只能使用键盘自带的多媒体键来调整
这个是想优化哪方面的功能？

**Comment by GDWGH** [comment]
> Re: [#66 (comment)](https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-891847694)
> 关于优化的话现在正常使用内存占用不到100MB
> 
> > 每次挂在后台的时候 忘记切回去 就只能使用键盘自带的多媒体键来调整
> > 这个是想优化哪方面的功能？
CPU 优化什么的吧
![image](https://user-images.githubusercontent.com/57795156/128099913-dcb1ae0d-85f7-4ff0-8b46-97bd58dae5d1.png)
不过 卡顿的地方都在程序开启的时候 切换到歌词页面的时候 和加载另一歌单的时候

**Comment by GDWGH** [comment]
因为长期挂在后台听音乐 一回去就掉前台 和后台（无响应退出） 只能使用键盘的音量调节键 来调整音乐（任务栏也可以 不过不想用 有可能也会掉 前 后台）

**Comment by GDWGH** [comment]
感觉这样的操作有点别扭
![image](https://user-images.githubusercontent.com/57795156/128101740-bb8a06fe-4991-4471-ac7e-28dae0a7f258.png)
当我想滑下去（鼠标滚轮） 但是却触发下面歌单的滚动
可以改成按钮吗？

**Comment by GDWGH** [comment]
前台冻结
![image](https://user-images.githubusercontent.com/57795156/128117874-8ac5a992-14d7-4e0c-b346-afc331add35c.png)

**Comment by kengwang** [comment]
系统版本和设备ID方便提供下吗?

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-892242159
CPU占用问题可以发送下相关歌单 / 歌曲的链接以便追踪

**Comment by GDWGH** [comment]
> 系统版本和设备ID方便提供下吗?

设备 ID	BDD2C8B8-CDBA-4A84-99EC-16C03F1F19E8

版本	Windows 10 专业工作站版
版本号	21H1
安装日期	‎2021/‎07/‎19
操作系统内部版本	19043.1110
体验	Windows Feature Experience Pack 120.2212.3530.0

**Comment by GDWGH** [comment]
> Re: [#66 (comment)](https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-892242159)
> CPU占用问题可以发送下相关歌单 / 歌曲的链接以便追踪

https://music.163.com/#/playlist?id=384577619

**Comment by kengwang** [comment]
> > Re: [#66 (comment)](https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-892242159)
> > CPU占用问题可以发送下相关歌单 / 歌曲的链接以便追踪
> 
> https://music.163.com/#/playlist?id=384577619

好的,我这边试试跑一下,看下能不能优化下占用

**Comment by GDWGH** [comment]
> 设备ID方便提供下吗?

为什么要要求设备id呢？

**Comment by kengwang** [comment]
> > 设备ID方便提供下吗?
> 
> 为什么要要求设备id呢？

我们这边有App Center错误跟踪. 因为隐私问题只有设备ID和错误信息. 提供设备ID可以更快定位错误

**Comment by GDWGH** [comment]
> > 
> 
> 我们这边有App Center错误跟踪. 因为隐私问题只有设备ID和错误信息. 提供设备ID可以更快定位错误

那么app center收集什么呢？（应该放进设置什么的吧。。。）

**Comment by kengwang** [comment]
> > > 
> > 
> > 
> > 我们这边有App Center错误跟踪. 因为隐私问题只有设备ID和错误信息. 提供设备ID可以更快定位错误
> 
> 那么app center收集什么呢？（应该放进设置什么的吧。。。）

错误报告和性能数据：我们收集有关产品性能的数据以及您在使用它们时遇到的任何问题。 此数据有助于我们诊断产品中的问题以及改进产品和提供解决方案。

我们使用以上数据来持续改善本UWP的用户体验，不会向任何第三方分享或透露这些数据。

**Comment by GDWGH** [comment]
> 评论区bug：当点进某一首歌的评论区的时候 再回到那首歌所属的歌单的时候 无法回到歌单（我喜欢的歌单和我创建的歌单均有这个bug）
> 
>  1627890391250.mp4 
> Fixed: [8cbc628](https://github.com/HyPlayer/HyPlayer/commit/8cbc62867184215c3b4e7372a57ead0d3a185c88)

当在歌手页面的时候 还是出现这个bug

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-892497113
两个的问题点一样,同时修复了

**Comment by GDWGH** [comment]
我喜欢的音乐 无法点击前3首（三首都有机率可以选中）
https://user-images.githubusercontent.com/57795156/128268983-a2bf48f4-2579-43f2-9d97-a07880f3e84e.mp4

2.0.19.0

**Comment by GDWGH** [comment]
感觉mini模式的操作按钮没有居中（强迫症）
![image](https://user-images.githubusercontent.com/57795156/128269353-58086023-220b-4b9c-825b-cf5fdf2043f2.png)

开启歌词以后更怪了 
![image](https://user-images.githubusercontent.com/57795156/128269423-2b6c4eaa-d76d-4069-8302-f1696f0c8af2.png)
 感觉把上面的封面缩小一下 再把歌词放在那里（1 / 2 行）

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-893047037
已经在 2.0.20 修复

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-893048153
小窗模式本来就设计为只开一种的,没有专门写两种. 假如这样的话我可以考虑禁止在小窗下两种模式同时开启. 专辑封面下面加个当前歌词显示.

**Comment by GDWGH** [comment]
很奇怪  UI音效每次关闭程序的时候都会恢复默认值（ 即便不关闭程序 都关闭了）

**Comment by GDWGH** [comment]
界面bug：从A页 切换到 本地与下载的时候 再去到 B页    虽然侧边栏选中了B页 但是 页面是空白的本地下载页
2.0.20.0

**Comment by GDWGH** [comment]
> 界面bug：从A页 切换到 本地与下载的时候 再去到 B页 虽然侧边栏选中了B页 但是 页面是空白的本地下载页
> 2.0.20.0
> 录屏：
> 
>  QQ.20210805135010.mp4

这个bug是永久性的 只有关闭程序才能解决

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-893183308
我想起来了,昨天写的BUG,啊啊啊啊啊啊啊啊啊

**Comment by GDWGH** [comment]
> 界面bug：从A页 切换到 本地与下载的时候 再去到 B页 虽然侧边栏选中了B页 但是 页面是空白的本地下载页
> 2.0.20.0
> 录屏：
> 
>  QQ.20210805135010.mp4

又引下来的一个bug 如果打开歌曲详情页 不会显示详情的按钮
![image](https://user-images.githubusercontent.com/57795156/128298514-0228e299-d42d-44a4-a223-8935050c44d7.png)

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-893185036
这个我今天遇到过,但是重启程序后又不能复现了. 很疑惑

**Comment by GDWGH** [comment]
> Re: [#66 (comment)](https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-893185036)
> 这个我今天遇到过,但是重启程序后又不能复现了. 很疑惑

卡出上面的bug 然后点击右下角的按钮

**Comment by GDWGH** [comment]
还要个人感觉进入歌曲详细页 时 加载封面出现的毛玻璃效果 很漂亮 为什么不做进设置呢？

**Comment by kengwang** [comment]
感谢,和之前那个的BUG点一样. 两个都已经在 644b836 修复

**Comment by GDWGH** [comment]
> 还有个人感觉进入歌曲详细页 时 加载封面出现的毛玻璃效果 很漂亮 为什么不做进设置呢？

偏毛玻璃效果：
![image](https://user-images.githubusercontent.com/57795156/128299100-deafdfeb-a4b9-45df-a5fd-a025fb51bba0.png)

载入后（无毛玻璃）：
![image](https://user-images.githubusercontent.com/57795156/128299152-66705284-76b6-4211-9f50-9e160c777122.png)

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-893187699
也就是说那个阴影是吗?

**Comment by GDWGH** [comment]
> Re: [#66 (comment)](https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-893187699)
> 也就是说那个阴影是吗?

就是啊 希望能做进设置里

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-893188819
emm,我放到实验室吧

**Comment by GDWGH** [comment]
还有一个奇怪的问题

**Comment by GDWGH** [comment]
> 还有一个奇怪的问题

我使用了
https://github.com/SeaHOH/GotoX
使用了完全代理（CFW） 和自动代理  但不载入歌曲 
（不像官方那样做一个缓存 即使意外断线 也能继续听 什么的吗？）

**Comment by GDWGH** [comment]
> 还有一个奇怪的问题

我使用了
https://github.com/SeaHOH/GotoX
使用了完全代理（CFW） 和自动代理  但不载入歌曲 
（不像官方那样做一个缓存 即使意外断线 也能继续听 什么的吗？）

**Comment by kengwang** [comment]
关于代理的话: 因为UWP的限制,要让UWP程序走代理要执行一个指令,之后我会贴出
缓存的话这个还没写,假如说要的话我可以下个版本加进去

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/66#issuecomment-893188819
Fixed in 6095d32
