### ISSUE TITLE
程序不断切换歌曲，无法正常使用

### ISSUE THREAD

**Issue by Leonezz** [HyPlayer/HyPlayer#69]
> 感谢您对 HyPlayer 提出建议和反馈,有了您的支持 HyPlayer 将会更好
>
> 在提交Issue时,为了保证您的Issue方便排查,减少沟通成本
>
> 请完善下方的内容, 这段引用起来的文字可以将其删除

## BUG 反馈

**何处触发：**
自电脑启动打开软件就会出现。
这个问题出在程序的哪一个具体功能？

**实际行为描述：**
程序不断切换歌曲，无法正常使用。具体地说，软件在一个列表中播放时会快速地不断切换曲目，无法正常播放
触发问题后造成了什么效果及影响？

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**

怎样才能再次触发这个问题？若无法复现可直接写 无法复现

**配置与环境：**

- 音乐链接：（如果有，请提供一个触发此问题的 音乐）
- HyPlayer 版本：Version 2.0.22.0
- 系统版本：Windows11 21H2（内部版本号：22000.120）

**截图（若有）**
播放本地列表时：

https://user-images.githubusercontent.com/33564074/128460579-03622bc4-bfa2-4b14-9118-f6f1a744d8d5.mp4

播放在线列表时：

https://user-images.githubusercontent.com/33564074/128460743-95edb542-813b-4a8a-858e-322dccb6d4fa.mp4

提供一个此问题触发的截图或报错信息。若没有，则留空。

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

提供尽可能多的相关信息。

**修复思路：**

**Comment by kengwang** [comment]
请问是否开了飞机,如果开了飞机请关闭或者开直链

**Comment by kengwang** [comment]
如果可以的话可以提供下 HyPlayer 设置 - 关于 - 设备识别码

**Comment by Leonezz** [comment]
> 如果可以的话可以提供下 HyPlayer 设置 - 关于 - 设备识别码

设备识别码是：45af85b9-f20a-a15b-0176-b3691a27349b
这个信息框建议做成可选中的

**Comment by kengwang** [comment]
Re: https://github.com/HyPlayer/HyPlayer/issues/69#issuecomment-894014610
确实,手打有点......

**Comment by Leonezz** [comment]
用网易云音乐客户端测试发现，客户端提醒我：未选择输出设备。重新连接蓝牙耳机就正常了
