### ISSUE TITLE
[Feature Request]希望内置支持记录同步到last.fm 之类的音乐记录平台

### ISSUE THREAD

**Issue by Lightmarey** [HyPlayer/HyPlayer#72]
**这是什么方面的想法？**

新增功能

**这个想法具体是要实现什么？**
希望内建提供对last.fm或者listenbrainz 之类的音乐记录网站的 scrobbler，可以自动同步音乐记录。

**这个想法实现后有什么帮助？**
有一个内建的同步插件 方便有需求的用户管理自己的全平台听歌记录，并通过网站的设计过的直观图表获得自己的音乐报告和推荐。

**是否有具体的实现思路？**
……Listen1 音乐播放器中内建了该功能

**Comment by kengwang** [comment]
wontfix

**Comment by kengwang** [comment]
加入考虑议程

**Comment by txyyh** [comment]
个人不建议实现 last.fm 的数据读取分析展示功能，明显这非常偏离本项目的设计方向

实现自动抓取播放曲目到 last.fm 即可

另外搜到个 [.NET 库](https://github.com/inflatablefriends/lastfm)，也许可以看下？

**Comment by kengwang** [comment]
> 个人不建议实现 last.fm 的数据读取分析展示功能，明显这非常偏离本项目的设计方向
> 
> 实现自动抓取播放曲目到 last.fm 即可
> 
> 另外搜到个 [.NET 库](https://github.com/inflatablefriends/lastfm)，也许可以看下？

感谢, 我一会儿看看, 假如好的话将在后续版本实现

**Comment by Raspberry-Monster** [comment]
正在实现此功能

**Comment by Raspberry-Monster** [comment]
Archived in https://github.com/HyPlayer/HyPlayer/pull/274
