### ISSUE TITLE
建议title搞小一点，或者可以自定义大小

### ISSUE THREAD

**Issue by GoldenSep** [HyPlayer/HyPlayer#73]
![image](https://user-images.githubusercontent.com/43335929/128729717-2beafea9-e934-4f91-9c73-7eee4ea5d0a7.png)
![image](https://user-images.githubusercontent.com/43335929/128729906-daab0a9e-1603-483a-8257-6534c5f8a126.png)
很好用，作者幸苦了

**Comment by EP012014** [comment]
这个是参照了Win8/8.1中的Metro设计
Windows 11中“设置”app也重新引入
如果你们不喜欢我们可以考虑设置

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/136662347-f38f8da7-6cec-41c2-aae5-24300e69a43e.png)
这样还行吧

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/136663125-1e0c3a20-3049-4134-af7e-6a5a3440bceb.png)

那就 Closed 了吧

**Comment by GoldenSep** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/30862240/136663125-1e0c3a20-3049-4134-af7e-6a5a3440bceb.png)
> 
> 那就 Closed 了吧

挺好的
