### ISSUE TITLE
希望加入对ModernFlyouts的支持

### ISSUE THREAD

**Issue by GysdfHome** [HyPlayer/HyPlayer#76]
** 希望加入对ModernFlyouts的支持 **
如图
[![hSCJiV.png](https://z3.ax1x.com/2021/08/22/hSCJiV.png)](https://imgtu.com/i/hSCJiV)

附他们的项目链接
https://github.com/ModernFlyouts-Community/ModernFlyouts

**Comment by kengwang** [comment]
我本人也在用 Mordern Flyouts, 已经基本支持,除了进度条

**Comment by kengwang** [comment]
如果进度条刚需的话可以考虑加入

**Comment by GysdfHome** [comment]
期待进度条支持了

**Comment by kengwang** [comment]
进度条在重构版中实现, 为可选支持. 因为开启后可能会导致一部分 CPU 占用

**Comment by chwt163** [comment]
> 进度条在重构版中实现, 为可选支持. 因为开启后可能会导致一部分 CPU 占用

重构版有正式版了吗？在哪里下载呢？

**Comment by kengwang** [comment]
Re:https://github.com/HyPlayer/HyPlayer/issues/76#issuecomment-1038066699
重构版还在开发中

**Comment by kengwang** [comment]
旧版也将在下个版本添加可选支持

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/154028277-1ffdb758-7151-4d64-9c3b-99ca08858797.png)
