### ISSUE TITLE
关于允许屏蔽主页歌单推荐、歌单评论、歌曲视频等功能的 feature request

### ISSUE THREAD

**Issue by RoderickQiu** [HyPlayer/HyPlayer#78]
**这是什么方面的想法？**

新增功能

**这个想法具体是要实现什么？**

添加一个设置项，允许屏蔽主页歌单推荐、歌单评论、歌曲视频等Hy剩余的有休闲属性的功能

**这个想法实现后有什么帮助？**

避免作为背景音乐的播放器占用注意力，导致摸鱼

**是否有具体的实现思路？**

添加一个设置项，打开时相关的按钮和列表项不能被点击

**补充信息：**

这个第三方好棒，有心动模式！

**Comment by RoderickQiu** [comment]
nb啊作者 居然是现高一 作为新高三感到您真是无敌

**Comment by kengwang** [comment]
哈哈哈,这个功能可以有.
之前我一直想在纯净的听歌体验和云村社交中找个平衡点.
于是就有了现在, 默认页面为用户页面, 评论需要点击才显示这些操作.
如果需要屏蔽的话也可以. 可以稍微把剩余的功能或要屏蔽的功能给列举下

**Comment by RoderickQiu** [comment]
大概就是想允许屏蔽探索->主页，某首歌->评论，某首歌->视频，某歌单->评论。谢谢啦

-------

另外，网易云原版允许重新抽心动模式歌曲列表，不知道这个能不能实现。

**Comment by kengwang** [comment]
重新心动的话尝试抓下包,看下是不是调用了一些神奇的接口
