### ISSUE TITLE
xbox最新beta版本bug很多

### ISSUE THREAD

**Issue by imagemlt** [HyPlayer/HyPlayer#79]
## BUG 反馈

没有了光标模式后，设置等等进不去，歌单上浏览时停到歌曲上就自动播放了，操作很不方便。而且播放键也是只要手柄停到上面就自动触发点击，造成了很大的困扰，这个beta版本是没有在xbox上实机测试过吗？
这个问题出在程序的哪一个具体功能？
新的beta版

**Comment by kengwang** [comment]
这个的话我一会儿修
