### ISSUE TITLE
空间图标好像被削了

### ISSUE THREAD

**Issue by heartacker** [HyPlayer/HyPlayer#80]
> 感谢您对 HyPlayer 提出建议和反馈,有了您的支持 HyPlayer 将会更好
>
> 在提交Issue时,为了保证您的Issue方便排查,减少沟通成本
>
> 请完善下方的内容, 这段引用起来的文字可以将其删除

## BUG 反馈

Icon 控件图标好像被剥削了

**何处触发：**

界面

**实际行为描述：**

UI 不好看

**预期的行为：**

**复现步骤：**

**配置与环境：**

- HyPlayer 版本：（2.0.28.0）
- 系统版本：win 11
- 系统缩放：150%

**截图（若有）**

![image](https://user-images.githubusercontent.com/1876302/132143856-c09730c7-2749-4f75-a3cb-3637b06a3755.png)

图标被削了。

**Comment by kengwang** [comment]
这个问题可能是因为UI排版的问题

**Comment by kengwang** [comment]
图标被削问题将会在近期解决, 可能会改变按钮大小
