### ISSUE TITLE
播放列表为空时，无法用 [下一首播放] 添加歌曲至播放列表

### ISSUE THREAD

**Issue by QZLin** [HyPlayer/HyPlayer#82]
## BUG 反馈

**何处触发：**
播放列表为空时（播放列表->清除全部）

**实际行为描述：**
播放列表为空时，点击 [下一首播放] 添加歌曲至播放列表无效

**预期的行为：**
播放列表为空时点击 [下一首播放] 应将歌曲至播放列表

**复现步骤：**
如上

**配置与环境：**

- 音乐链接：任何
- HyPlayer 版本：[`commit 124779487b970d9dc4acf48e7fc172004115629c`](https://github.com/HyPlayer/HyPlayer/commit/124779487b970d9dc4acf48e7fc172004115629c)
以及Microsoft Store下载到的版本也是如此
![image](https://user-images.githubusercontent.com/38138000/133953788-fcbbc6ba-4336-431e-a22d-f5e04f519048.png)

- 系统版本：Windows10 x64, Windows 11 x64

**修复思路：**

**Comment by kengwang** [comment]
已经收到,正在于最新版上测试

**Comment by kengwang** [comment]
已确认问题,将会在下次Commit中修复

**Comment by kengwang** [comment]
Fixed in https://github.com/HyPlayer/HyPlayer/commit/25c057486cd5af99e51e717e281f1ea54b6cc69f

**Comment by kengwang** [comment]
有个问题,就是当前没有播放的话,插入到下一曲也是不播放的
