### ISSUE TITLE
建议增加wasapi或asio音频输出

### ISSUE THREAD

**Issue by kingofotaku** [HyPlayer/HyPlayer#84]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个程序更好。**
> 当你确定你的想法满足以上条件之后，请删除本段文本并继续。

**这是什么方面的想法？**
音频输出
现有内容的优化 / 新增功能 / UI 界面 / 用户体验
新增功能
**这个想法具体是要实现什么？**
增加wasapi或asio音频输出

**这个想法实现后有什么帮助？**

大概能改善音质（吧？）
**是否有具体的实现思路？**

**补充信息：**

**Comment by kengwang** [comment]
目前网上的示例都是C++版本的UWP，再调用到底层API 不知道C#可不可以

**Comment by kengwang** [comment]
wontfix
