### ISSUE TITLE
歌单中歌曲的播放和详情按钮排布出现问题

### ISSUE THREAD

**Issue by Leo-Aug** [HyPlayer/HyPlayer#86]
**实际行为描述：** 使用播放器查看歌单中歌曲的时候每个歌曲的播放按钮和详情按钮不整齐。

**复现步骤：** 随意打开一个歌单

**配置与环境：**

- HyPlayer 版本：2.1.0.0
- 系统版本：Windows10 20H2 内部版本 19042.1237

**截图（若有）**

最大化时：
![image](https://user-images.githubusercontent.com/57796691/134762178-107c4f73-677b-44df-aa1e-13ac6b4b55e3.png)

非最大化时：
![image](https://user-images.githubusercontent.com/57796691/134762194-335661a7-0eae-4a99-acdd-faf87dd61c17.png)

**补充信息：**

设备为Microsoft Surface Pro 7 8G+128G

屏幕分辨率为2736*1824

缩放为200%

**Comment by kengwang** [comment]
fa57c88874846cc564cbf219a720138db566fe62
