### ISSUE TITLE
播放列表异常(消失), 并(几乎)随机报错： Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by chr56** [HyPlayer/HyPlayer#87]
## BUG 反馈

**何处触发：**

`每日推荐` / 空白 `歌单`

**实际行为描述：**

1. 每日推荐歌单(几乎)无法正常加入当前播放列表;
2. 播放列表莫名<del>随机</del>消失;
3. (几乎)随机报错： `Object reference not set to an instance of an object.`

**预期的行为：**

播放列表不消失, 每日推荐歌单可正常加入播放列表

**复现步骤：**

<del>(几乎)随机复现: (</del>
但有几种明确复现方式
1. 最小化HyPlayer后, 再次还原窗口, 播放列表必丢, 然后报错
2. 双击每日推荐歌单内任意歌曲, 播放列表无变化(还是空的), 然后报错
3. 点击(自己的)空白歌单, 报错

**配置与环境：**

 - <del>音乐链接：无</del>
- HyPlayer 版本：Release 2.1.3.0
- 系统版本：21H1 19043.1237

<del>**截图（无）**</del>

**报错信息**

```
Object reference not set to an instance of an object.
Exception of type "System.Exception" was thrown
```

**补充信息：**

清空播放列表可<del>临时</del>恢复, <del>又不是不能用</del>

**修复思路：**
什么问题?
<del>🤔每日推荐页面的播放列表被GC吞了??? 不考虑对播放列表做(彻底的)数据持久化么?</del>
我没开发过UWP…😅

**Comment by kengwang** [comment]
此问题已经在近期Commit中修复，将于之后发布到商店

**Comment by kengwang** [comment]
已发布给 Beta 通道, 正式版通道将会在近期收到更新
