### ISSUE TITLE
今天晚上出现错误

### ISSUE THREAD

**Issue by Maogxer** [HyPlayer/HyPlayer#88]
不能登录也不能读取音乐列表了。

> 
![屏幕截图(3)](https://user-images.githubusercontent.com/84484782/136050902-d71ef8fc-b42a-48cc-a150-2d26321216ac.png)

**Comment by kengwang** [comment]
稍等,我看看

**Comment by kengwang** [comment]
每日歌曲是在新版里面修了的,这种情况可以检查一下 HyPlayer 是否有网络权限

**Comment by kengwang** [comment]
关于登录是报错的问题:
这个问题通常是由于系统的配置问题导致的. 你可以按照以下步骤进行排查:
1. 检查网络是否正常连接.
2. 把你的小飞机降落下来，UWP应用和代理冲突。
3. 如使用 WIFI 连接检查是否允许 HyPlayer 联网:
进入 设置 - WLAN 和 Internet (因为各版本翻译不同,大概这个意思的就行) - WLAN - 选择可以使用 WLAN 数据的应用 - 找到 HyPlayer 并将开关打开
4. 如果你开启了 Windows Defender 可以打开他 - 防火墙和网络保护 - 允许应用通过防火墙 - 允许 HyPlayer
5. 将网络配置改成 公用
6. 假如还是不行可以尝试刷新或更换 DNS, 我推荐使用 114.114.114.114
7. 你也可以试试解除 网络环回
CheckNetIsolation LoopbackExempt -a -n="48848aaaaaaccd.hyplayer_fkcggvf9kbkw0"

**Comment by Maogxer** [comment]
我听着歌突然就这样了.
重启电脑就好了。
