### ISSUE TITLE
歌单歌曲无法删除，删除后刷新仍然存在

### ISSUE THREAD

**Issue by EWinner1** [HyPlayer/HyPlayer#97]
> 感谢您对 HyPlayer 提出建议和反馈,有了您的支持 HyPlayer 将会更好
>
> 在提交Issue时,为了保证您的Issue方便排查,减少沟通成本
>
> 请完善下方的内容, 这段引用起来的文字可以将其删除

## BUG 反馈

**何处触发：**

在歌单中删除歌曲

**实际行为描述： **

在歌单中删除歌曲，歌单是QQ音乐导入的歌单，手机版网易云可以正常收听，在当前软件中尝试删除歌单中的歌曲时无法正常删除

**预期的行为：**

正常删除歌单中选中的歌曲，重新载入不再出现已删除的歌曲

**复现步骤：**

打开歌单，选择三个点，选择删除，然后切换到其他歌单，在切换回来，观察歌单删除情况
**配置与环境：**

- 音乐链接：任何一首歌
- HyPlayer 版本：微软商店下载2.1.5.0
- 
- 系统版本：
- 
![image](https://user-images.githubusercontent.com/38932060/138014794-e82c5e6b-59db-4bf6-b6f2-d84f73882022.png)

**截图（若有）**

**报错信息**

```
请在此处填写报错框中的相关信息
```

**补充信息：**

提供尽可能多的相关信息。

**修复思路：**

**Comment by EWinner1** [comment]
![image](https://user-images.githubusercontent.com/38932060/138015001-c55708f5-4cd8-438d-b4ec-9c73c646a2dc.png)

**Comment by EP012014** [comment]
QQ音乐导入的歌单可能不支持删除，这边测试一下

**Comment by EWinner1** [comment]
> QQ音乐导入的歌单可能不支持删除，这边测试一下

导入的歌单在网易云移动App中正常生成了，且可以删除，操作的数据应该仍然是网易云的数据，理论上可以正常删除

**Comment by kengwang** [comment]
右键可能会出现无法正常选中歌曲但是也会弹出菜单的现象.
